function meta = pe_phase_release_run_meta_vertical(root_dir,options)
%PE_PHASE_RELEASE_RUN_META_VERTICAL Create/load the active phase-RC identity.
%   The fingerprint intentionally covers phase-sensitive source files, not
%   generated results or documentation, so interrupted runs can be resumed
%   only while the implementation that defines their semantics is unchanged.

if nargin<2 || isempty(options), options=struct(); end
if ~isstruct(options), error('options must be a struct.'); end
if ~isfield(options,'create'), options.create=false; end
if ~isfield(options,'run_id'), options.run_id=''; end
if ~isfield(options,'frequency_axis_hz'), options.frequency_axis_hz=[]; end
if ~isfield(options,'seed_definition'), options.seed_definition=struct(); end

state_dir=fullfile(root_dir,'results','validation','pe_phase_release_candidate');
state_file=fullfile(state_dir,'current_run.mat');
fingerprint=local_fingerprint(root_dir);
if options.create
    if ~exist(state_dir,'dir'), mkdir(state_dir); end
    if isempty(options.run_id)
        run_id=['phase_rc_' char(datetime('now','Format','yyyyMMdd_HHmmss'))];
    else
        run_id=options.run_id;
    end
    [status,revision]=system('git rev-parse HEAD');
    if status~=0, revision='unavailable'; else, revision=strtrim(revision); end
    [~,dirty_text]=system('git status --porcelain --untracked-files=no');
    meta=struct( ...
        'schema_version','1.0.0', ...
        'run_id',run_id, ...
        'code_revision',revision, ...
        'code_dirty',~isempty(strtrim(dirty_text)), ...
        'code_fingerprint',fingerprint.sha256, ...
        'code_fingerprint_files',{fingerprint.files}, ...
        'created_at',char(datetime('now','TimeZone','local','Format','yyyy-MM-dd''T''HH:mm:ssXXX')), ...
        'matlab_version',version, ...
        'geometry',struct('z_tx',100,'z_rx',3,'z_surface',0,'c0',1500), ...
        'frequency_axis_hz',options.frequency_axis_hz(:), ...
        'seed_definition',options.seed_definition, ...
        'phase_reference','direct_dsp', ...
        'status','ACTIVE');
    save(state_file,'meta');
else
    if ~exist(state_file,'file')
        error('pe_phase_release_run_meta_vertical:MissingActiveRun', ...
            'Run prepare_pe_phase_reference_release_candidate_vertical first.');
    end
    loaded=load(state_file,'meta'); meta=loaded.meta;
    if ~strcmp(meta.code_fingerprint,fingerprint.sha256)
        error('pe_phase_release_run_meta_vertical:FingerprintChanged', ...
            ['Active run %s was created with fingerprint %s, but current ', ...
            'phase source fingerprint is %s. Archive the partial run and ', ...
            'create a new run_id.'],meta.run_id,meta.code_fingerprint,fingerprint.sha256);
    end
    if ~isempty(options.frequency_axis_hz)
        meta.frequency_axis_hz=options.frequency_axis_hz(:);
    end
    if ~(isstruct(options.seed_definition) && isempty(fieldnames(options.seed_definition)))
        meta.seed_definition=options.seed_definition;
    end
end
end

function fingerprint=local_fingerprint(root_dir)
files={ ...
    'apply_pe_channel_phase_reference_vertical.m'; ...
    'vertical_channel_model.m'; ...
    'vertical_wape_propagator.m'; ...
    'run_cached_joint_kstat_pe_executor_vertical.m'; ...
    'run_adjoint_receiver_projection_vertical.m'; ...
    'contract_kstat_receiver_stats_vertical.m'; ...
    'upgrade_conditional_channel_phase_vertical.m'; ...
    'build_channel_cir_vertical.m'; ...
    'build_communication_taps_vertical.m'; ...
    'validate_phase_neutral_pe_cache_vertical.m'; ...
    fullfile('scripts','validation','validate_pe_channel_phase_reference_vertical.m'); ...
    fullfile('scripts','validation','validate_pe_phase_convention_uniform_vertical.m'); ...
    fullfile('scripts','validation','validate_adjoint_pe_receiver_projection_vertical.m'); ...
    fullfile('scripts','validation','validate_u5_conditional_channel_generator_vertical.m'); ...
    fullfile('scripts','validation','validate_u8_conditional_channel_generator_vertical.m'); ...
    fullfile('scripts','validation','build_u5_u8_conditional_library_vertical.m'); ...
    fullfile('scripts','validation','validate_two_node_communication_vertical.m'); ...
    fullfile('scripts','validation','validate_cached_pe_public_consistency_vertical.m'); ...
    fullfile('scripts','validation','validate_public_channel_modes_vertical.m'); ...
    fullfile('scripts','reporting','generate_pe_propagation_atlas_vertical.m'); ...
    fullfile('scripts','reporting','plot_pe_propagation_atlas_vertical.m')};
md=java.security.MessageDigest.getInstance('SHA-256');
for ii=1:numel(files)
    path=fullfile(root_dir,files{ii});
    if ~exist(path,'file')
        error('pe_phase_release_run_meta_vertical:MissingFingerprintFile', ...
            'Required fingerprint source is missing: %s',path);
    end
    md.update(typecast(uint8(files{ii}),'int8'));
    fid=fopen(path,'rb'); cleanup=onCleanup(@()fclose(fid));
    bytes=fread(fid,Inf,'*uint8'); clear cleanup;
    md.update(typecast(bytes,'int8'));
end
digest=typecast(md.digest(),'uint8');
fingerprint=struct('sha256',lower(reshape(dec2hex(digest,2).',1,[])), ...
    'files',{files});
end
