function [surface_elevation, delta_phi, psi_ref, meta] = ...
    pm_surface_boundary_model(psi_inc, KX, KY, x, y, xw, yw, lambda0, pm_cfg)
%PM_SURFACE_BOUNDARY_MODEL
% PM rough-surface boundary model for spatial Kirchhoff and SSA kernels.

if nargin < 9 || isempty(pm_cfg)
    pm_cfg = struct();
end
if ~isfield(pm_cfg, 'U') || isempty(pm_cfg.U)
    pm_cfg.U = 5.0;
end
if ~isfield(pm_cfg, 'Hs_target') || isempty(pm_cfg.Hs_target)
    pm_cfg.Hs_target = 0.5;
end
if ~isfield(pm_cfg, 'roughness_scale_mode') || isempty(pm_cfg.roughness_scale_mode)
    pm_cfg.roughness_scale_mode = 'target_hs';
end
if ~isfield(pm_cfg, 'seed') || isempty(pm_cfg.seed)
    pm_cfg.seed = 12345;
end
if ~isfield(pm_cfg, 'show_figure') || isempty(pm_cfg.show_figure)
    pm_cfg.show_figure = true;
end
if ~isfield(pm_cfg, 'reflect_coeff') || isempty(pm_cfg.reflect_coeff)
    pm_cfg.reflect_coeff = -1;
end
if ~isfield(pm_cfg, 'phase_mode') || isempty(pm_cfg.phase_mode)
    pm_cfg.phase_mode = 'normal';
end
if ~isfield(pm_cfg, 'oblique_clip') || isempty(pm_cfg.oblique_clip)
    pm_cfg.oblique_clip = [0, 1];
end
if ~isfield(pm_cfg, 'tx_xyz') || isempty(pm_cfg.tx_xyz)
    pm_cfg.tx_xyz = [0, 0, NaN];
end
if ~isfield(pm_cfg, 'rx_xyz') || isempty(pm_cfg.rx_xyz)
    pm_cfg.rx_xyz = [0, 0, NaN];
end
if ~isfield(pm_cfg, 'z_surface') || isempty(pm_cfg.z_surface)
    pm_cfg.z_surface = 0;
end
if ~isfield(pm_cfg, 'boundary_model') || isempty(pm_cfg.boundary_model)
    pm_cfg.boundary_model = 'kirchhoff_spatial';
end
if ~isfield(pm_cfg, 'boundary_check_equivalence') || isempty(pm_cfg.boundary_check_equivalence)
    pm_cfg.boundary_check_equivalence = false;
end
if ~isfield(pm_cfg, 'boundary_debug') || isempty(pm_cfg.boundary_debug)
    pm_cfg.boundary_debug = false;
end
if ~isfield(pm_cfg, 'boundary_equivalence_tol') || isempty(pm_cfg.boundary_equivalence_tol)
    pm_cfg.boundary_equivalence_tol = 1e-10;
end
if ~isfield(pm_cfg, 'boundary_coupling_diagnostics') || isempty(pm_cfg.boundary_coupling_diagnostics)
    pm_cfg.boundary_coupling_diagnostics = false;
end
if ~isfield(pm_cfg, 'boundary_coupling_debug') || isempty(pm_cfg.boundary_coupling_debug)
    pm_cfg.boundary_coupling_debug = false;
end
if ~isfield(pm_cfg, 'boundary_redistribution_diagnostics') || isempty(pm_cfg.boundary_redistribution_diagnostics)
    pm_cfg.boundary_redistribution_diagnostics = false;
end
if ~isfield(pm_cfg, 'boundary_redistribution_debug') || isempty(pm_cfg.boundary_redistribution_debug)
    pm_cfg.boundary_redistribution_debug = false;
end
if ~isfield(pm_cfg, 'ssa_random_scatter') || isempty(pm_cfg.ssa_random_scatter)
    pm_cfg.ssa_random_scatter = true;
end
if ~isfield(pm_cfg, 'ssa_scatter_scale') || isempty(pm_cfg.ssa_scatter_scale)
    pm_cfg.ssa_scatter_scale = 1.0;
end
if ~isfield(pm_cfg, 'ssa_seed_offset') || isempty(pm_cfg.ssa_seed_offset)
    pm_cfg.ssa_seed_offset = 100000;
end
if ~isfield(pm_cfg, 'ssa_kernel_mode') || isempty(pm_cfg.ssa_kernel_mode)
    pm_cfg.ssa_kernel_mode = 'pm_convolution';
end
if ~isfield(pm_cfg, 'ssa_coherent_order') || isempty(pm_cfg.ssa_coherent_order)
    pm_cfg.ssa_coherent_order = 'ssa1';
end
if ~isfield(pm_cfg, 'ssa_frequency_correlation_mode') || isempty(pm_cfg.ssa_frequency_correlation_mode)
    pm_cfg.ssa_frequency_correlation_mode = 'independent';
end
if ~isfield(pm_cfg, 'ssa_frequency_correlation_rho') || isempty(pm_cfg.ssa_frequency_correlation_rho)
    pm_cfg.ssa_frequency_correlation_rho = 0.8;
end
if ~isfield(pm_cfg, 'ssa_geometry_source_id') || isempty(pm_cfg.ssa_geometry_source_id)
    pm_cfg.ssa_geometry_source_id = '';
end
if ~isfield(pm_cfg, 'ssa_kz_branch') || isempty(pm_cfg.ssa_kz_branch)
    pm_cfg.ssa_kz_branch = 'downward_positive_real';
end
if ~isfield(pm_cfg, 'ssa_conv_padding') || isempty(pm_cfg.ssa_conv_padding)
    pm_cfg.ssa_conv_padding = 'periodic';
end
if ~isfield(pm_cfg, 'kstat_random_scatter') || isempty(pm_cfg.kstat_random_scatter)
    pm_cfg.kstat_random_scatter = true;
end
if ~isfield(pm_cfg, 'kstat_seed_offset') || isempty(pm_cfg.kstat_seed_offset)
    pm_cfg.kstat_seed_offset = 200000;
end
if ~isfield(pm_cfg, 'kstat_conv_padding') || isempty(pm_cfg.kstat_conv_padding)
    pm_cfg.kstat_conv_padding = 'periodic';
end
if ~isfield(pm_cfg, 'kstat_trusted_angle_deg') || isempty(pm_cfg.kstat_trusted_angle_deg)
    pm_cfg.kstat_trusted_angle_deg = NaN;
end
if ~isfield(pm_cfg, 'frequency_index') || isempty(pm_cfg.frequency_index)
    pm_cfg.frequency_index = 1;
end

if ~(isscalar(pm_cfg.reflect_coeff) && isnumeric(pm_cfg.reflect_coeff) && isfinite(pm_cfg.reflect_coeff))
    error('pm_cfg.reflect_coeff must be a finite scalar (real or complex).');
end
if isstring(pm_cfg.phase_mode)
    pm_cfg.phase_mode = char(pm_cfg.phase_mode);
end
phase_mode = lower(pm_cfg.phase_mode);
if ~ischar(phase_mode) || (~strcmp(phase_mode, 'normal') && ~strcmp(phase_mode, 'oblique'))
    error('pm_cfg.phase_mode must be ''normal'' or ''oblique''.');
end
if ~(isnumeric(pm_cfg.oblique_clip) && numel(pm_cfg.oblique_clip) == 2 && all(isfinite(pm_cfg.oblique_clip(:))))
    error('pm_cfg.oblique_clip must be a finite 1x2 numeric range.');
end
clip_pair = sort(pm_cfg.oblique_clip(:).');
if clip_pair(1) < 0 || clip_pair(2) > 1
    error('pm_cfg.oblique_clip must stay within [0,1].');
end
if ~(isnumeric(pm_cfg.tx_xyz) && numel(pm_cfg.tx_xyz) == 3 && all(isfinite(pm_cfg.tx_xyz(:))))
    error('pm_cfg.tx_xyz must be a finite [x,y,z].');
end
if ~(isnumeric(pm_cfg.rx_xyz) && numel(pm_cfg.rx_xyz) == 3 && all(isfinite(pm_cfg.rx_xyz(:))))
    error('pm_cfg.rx_xyz must be a finite [x,y,z].');
end
boundary_model = local_normalize_choice(pm_cfg.boundary_model, 'pm_cfg.boundary_model');
if ~any(strcmp(boundary_model, {'kirchhoff_spatial', 'kirchhoff_kdomain', 'ssa_stat_kernel', 'kirchhoff_kstat'}))
    error('pm_cfg.boundary_model must be ''kirchhoff_spatial'', ''kirchhoff_kdomain'', ''ssa_stat_kernel'', or ''kirchhoff_kstat''.');
end
roughness_scale_mode = local_normalize_choice(pm_cfg.roughness_scale_mode, 'pm_cfg.roughness_scale_mode');
if ~any(strcmp(roughness_scale_mode, {'target_hs', 'raw_pm'}))
    error('pm_cfg.roughness_scale_mode must be ''target_hs'' or ''raw_pm''.');
end
if ~isscalar(pm_cfg.boundary_check_equivalence)
    error('pm_cfg.boundary_check_equivalence must be a scalar logical flag.');
end
boundary_check_equivalence = logical(pm_cfg.boundary_check_equivalence);
if ~isscalar(pm_cfg.boundary_debug)
    error('pm_cfg.boundary_debug must be a scalar logical flag.');
end
boundary_debug = logical(pm_cfg.boundary_debug);
if ~(isscalar(pm_cfg.boundary_equivalence_tol) && isnumeric(pm_cfg.boundary_equivalence_tol) && ...
     isfinite(pm_cfg.boundary_equivalence_tol) && pm_cfg.boundary_equivalence_tol > 0)
    error('pm_cfg.boundary_equivalence_tol must be a positive finite scalar.');
end
boundary_equivalence_tol = pm_cfg.boundary_equivalence_tol;
if ~isscalar(pm_cfg.boundary_coupling_diagnostics)
    error('pm_cfg.boundary_coupling_diagnostics must be a scalar logical flag.');
end
boundary_coupling_diagnostics = logical(pm_cfg.boundary_coupling_diagnostics);
if ~isscalar(pm_cfg.boundary_coupling_debug)
    error('pm_cfg.boundary_coupling_debug must be a scalar logical flag.');
end
boundary_coupling_debug = logical(pm_cfg.boundary_coupling_debug);
if ~isscalar(pm_cfg.boundary_redistribution_diagnostics)
    error('pm_cfg.boundary_redistribution_diagnostics must be a scalar logical flag.');
end
boundary_redistribution_diagnostics = logical(pm_cfg.boundary_redistribution_diagnostics);
if ~isscalar(pm_cfg.boundary_redistribution_debug)
    error('pm_cfg.boundary_redistribution_debug must be a scalar logical flag.');
end
boundary_redistribution_debug = logical(pm_cfg.boundary_redistribution_debug);
if ~isscalar(pm_cfg.ssa_random_scatter)
    error('pm_cfg.ssa_random_scatter must be a scalar logical flag.');
end
ssa_random_scatter = logical(pm_cfg.ssa_random_scatter);
if ~(isscalar(pm_cfg.ssa_scatter_scale) && isnumeric(pm_cfg.ssa_scatter_scale) && ...
     isfinite(pm_cfg.ssa_scatter_scale) && pm_cfg.ssa_scatter_scale >= 0)
    error('pm_cfg.ssa_scatter_scale must be a nonnegative finite scalar.');
end
ssa_scatter_scale = pm_cfg.ssa_scatter_scale;
ssa_seed_offset = local_force_int(pm_cfg.ssa_seed_offset, 'pm_cfg.ssa_seed_offset');
if ssa_seed_offset < 0
    error('pm_cfg.ssa_seed_offset must be nonnegative.');
end
ssa_kernel_mode = local_normalize_choice(pm_cfg.ssa_kernel_mode, 'pm_cfg.ssa_kernel_mode');
if ~any(strcmp(ssa_kernel_mode, {'pm_convolution', 'ssa1_geometry', 'ssa1_debug_dense'}))
    error('pm_cfg.ssa_kernel_mode must be ''pm_convolution'', ''ssa1_geometry'', or ''ssa1_debug_dense''.');
end
ssa_coherent_order = local_normalize_choice(pm_cfg.ssa_coherent_order, 'pm_cfg.ssa_coherent_order');
if ~any(strcmp(ssa_coherent_order, {'ssa1', 'ssa2_broschat_coherent'}))
    error('pm_cfg.ssa_coherent_order must be ''ssa1'' or ''ssa2_broschat_coherent''.');
end
ssa_frequency_correlation_mode = local_normalize_choice(pm_cfg.ssa_frequency_correlation_mode, 'pm_cfg.ssa_frequency_correlation_mode');
if ~any(strcmp(ssa_frequency_correlation_mode, {'independent', 'shared_seed_phase', 'ar1_frequency'}))
    error('pm_cfg.ssa_frequency_correlation_mode must be ''independent'', ''shared_seed_phase'', or ''ar1_frequency''.');
end
if ~(isscalar(pm_cfg.ssa_frequency_correlation_rho) && isnumeric(pm_cfg.ssa_frequency_correlation_rho) && ...
     isfinite(pm_cfg.ssa_frequency_correlation_rho) && pm_cfg.ssa_frequency_correlation_rho >= 0 && ...
     pm_cfg.ssa_frequency_correlation_rho < 1)
    error('pm_cfg.ssa_frequency_correlation_rho must satisfy 0 <= rho < 1.');
end
ssa_frequency_correlation_rho = pm_cfg.ssa_frequency_correlation_rho;
if isstring(pm_cfg.ssa_geometry_source_id)
    pm_cfg.ssa_geometry_source_id = char(pm_cfg.ssa_geometry_source_id);
end
if ~ischar(pm_cfg.ssa_geometry_source_id)
    error('pm_cfg.ssa_geometry_source_id must be a char vector or string scalar.');
end
ssa_geometry_source_id = pm_cfg.ssa_geometry_source_id;
ssa_kz_branch = local_normalize_choice(pm_cfg.ssa_kz_branch, 'pm_cfg.ssa_kz_branch');
if ~strcmp(ssa_kz_branch, 'downward_positive_real')
    error('pm_cfg.ssa_kz_branch currently supports only ''downward_positive_real''.');
end
ssa_conv_padding = local_normalize_choice(pm_cfg.ssa_conv_padding, 'pm_cfg.ssa_conv_padding');
if ~any(strcmp(ssa_conv_padding, {'periodic', 'zero_padded'}))
    error('pm_cfg.ssa_conv_padding must be ''periodic'' or ''zero_padded''.');
end
if ~isscalar(pm_cfg.kstat_random_scatter)
    error('pm_cfg.kstat_random_scatter must be a scalar logical flag.');
end
kstat_random_scatter = logical(pm_cfg.kstat_random_scatter);
kstat_seed_offset = local_force_int(pm_cfg.kstat_seed_offset, 'pm_cfg.kstat_seed_offset');
if kstat_seed_offset < 0
    error('pm_cfg.kstat_seed_offset must be nonnegative.');
end
kstat_conv_padding = local_normalize_choice(pm_cfg.kstat_conv_padding, 'pm_cfg.kstat_conv_padding');
if ~any(strcmp(kstat_conv_padding, {'periodic', 'zero_padded'}))
    error('pm_cfg.kstat_conv_padding must be ''periodic'' or ''zero_padded''.');
end
if ~(isscalar(pm_cfg.kstat_trusted_angle_deg) && isnumeric(pm_cfg.kstat_trusted_angle_deg) && ...
     (isnan(pm_cfg.kstat_trusted_angle_deg) || ...
      (isfinite(pm_cfg.kstat_trusted_angle_deg) && pm_cfg.kstat_trusted_angle_deg >= 0 && pm_cfg.kstat_trusted_angle_deg <= 90)))
    error('pm_cfg.kstat_trusted_angle_deg must be NaN or a finite scalar in [0,90].');
end
kstat_trusted_angle_deg = pm_cfg.kstat_trusted_angle_deg;
frequency_index = local_force_int(pm_cfg.frequency_index, 'pm_cfg.frequency_index');
if frequency_index < 1
    error('pm_cfg.frequency_index must be positive.');
end

% -----------------------------
% 1) PM spectrum and boundary phase geometry
% -----------------------------
pm_spectrum = local_pm_spectrum(KX, KY, xw, yw, pm_cfg.U);
U = pm_spectrum.U;          % m/s
g = pm_spectrum.g;          % m/s^2
alpha_PM = pm_spectrum.alpha_PM;
beta_PM = pm_spectrum.beta_PM;
K = pm_spectrum.K;
E1D = pm_spectrum.E1D;
Phi2D = pm_spectrum.Phi2D;
mask = pm_spectrum.mask;
dkx = pm_spectrum.dkx;
dky = pm_spectrum.dky;
Hs_target = pm_cfg.Hs_target; % m
if ~(isscalar(Hs_target) && isnumeric(Hs_target) && isfinite(Hs_target) && Hs_target >= 0)
    error('pm_cfg.Hs_target must be a nonnegative finite scalar.');
end
pm_variance_raw_discrete_m2 = sum(Phi2D(:)) * dkx * dky;
sigma_eta_raw_discrete_m = sqrt(max(pm_variance_raw_discrete_m2, 0));
Hs_raw_discrete_m = 4 * sigma_eta_raw_discrete_m;
pm_variance_raw_continuous_m2 = pm_variance_raw_discrete_m2 / (2*pi)^2;
sigma_eta_raw_continuous_m = sqrt(max(pm_variance_raw_continuous_m2, 0));
Hs_raw_continuous_m = 4 * sigma_eta_raw_continuous_m;
k0 = 2*pi / lambda0;
[X, Y] = meshgrid(x, y);
phase_factor = local_surface_phase_factor( ...
    phase_mode, X, Y, pm_cfg.tx_xyz, pm_cfg.rx_xyz, pm_cfg.z_surface, clip_pair);
kstat_disabled_roughness_mode = roughness_scale_mode;
ssa_meta = local_disabled_ssa_stat_kernel_meta(Hs_target, ssa_seed_offset, roughness_scale_mode);
kstat_meta = local_disabled_kirchhoff_kstat_meta(Hs_target, kstat_seed_offset, ...
    kstat_conv_padding, kstat_trusted_angle_deg, kstat_disabled_roughness_mode);
sigma_eta_raw_m = NaN;
Hs_raw_m = NaN;

% -----------------------------
% 2) Surface boundary operator
% -----------------------------
surface_realization_generated = any(strcmp(boundary_model, {'kirchhoff_spatial', 'kirchhoff_kdomain'}));
if surface_realization_generated
    A = sqrt(Phi2D .* dkx .* dky);
    rng(pm_cfg.seed, 'twister')
    N = (randn(size(K)) + 1i*randn(size(K))) / sqrt(2);
    Zk = A .* N;

    eta_raw = real(ifft2(Zk));
    eta_raw = eta_raw * numel(eta_raw); % compensate MATLAB ifft2 normalization
    eta_raw = sqrt(2) * eta_raw; % real part of unconstrained complex spectrum carries half the target variance

    % Calibrate to target Hs by default; raw_pm keeps the PM realization amplitude.
    Hs_raw = 4 * std(eta_raw(:));
    switch roughness_scale_mode
        case 'target_hs'
            if Hs_raw > 0
                scale_factor = Hs_target / Hs_raw;
            else
                scale_factor = 0;
            end
        case 'raw_pm'
            scale_factor = 1;
    end
    sigma_eta_raw_m = Hs_raw / 4;
    Hs_raw_m = Hs_raw;
    surface_elevation = eta_raw * scale_factor;
    Hs_scaled = 4 * std(surface_elevation(:));

    % Kirchhoff phase screen: delta_phi = k0*(cos_i+cos_r)*eta.
    % In normal incidence phase_factor=2, so delta_phi=2*k0*eta.
    delta_phi = k0 * surface_elevation .* phase_factor;
    G_xy = pm_cfg.reflect_coeff .* exp(1i * delta_phi);
    [coupling_diag, coupling_debug] = local_boundary_coupling_diagnostics( ...
        G_xy, KX, KY, boundary_coupling_diagnostics, boundary_coupling_debug);
    [psi_ref, boundary_meta] = local_apply_kirchhoff_boundary( ...
        psi_inc, G_xy, boundary_model, boundary_check_equivalence, ...
        boundary_debug, boundary_equivalence_tol);
    [redistribution_diag, redistribution_debug] = local_boundary_redistribution_diagnostics( ...
        psi_inc, psi_ref, pm_cfg.reflect_coeff .* psi_inc, KX, KY, k0, ...
        boundary_redistribution_diagnostics, boundary_redistribution_debug);
elseif strcmp(boundary_model, 'ssa_stat_kernel')
    surface_elevation = [];
    delta_phi = [];
    spectral_variance = sum(Phi2D(:)) * dkx * dky;
    sigma_eta_raw_m = sqrt(max(spectral_variance, 0));
    Hs_raw_m = 4 * sigma_eta_raw_m;
    Hs_raw = Hs_raw_m;
    switch roughness_scale_mode
        case 'target_hs'
            sigma_eta = Hs_target / 4;
            if spectral_variance > 0 && sigma_eta > 0
                scale_factor = sigma_eta / sqrt(spectral_variance);
            else
                scale_factor = 0;
            end
        case 'raw_pm'
            sigma_eta = sigma_eta_raw_m;
            scale_factor = 1;
    end
    Hs_scaled = 4 * sigma_eta;
    W_eta = Phi2D * scale_factor^2;

    seed_ssa = pm_cfg.seed + ssa_seed_offset + frequency_index - 1;
    [psi_ref, boundary_meta, ssa_meta] = local_apply_ssa_stat_kernel( ...
        psi_inc, W_eta, KX, KY, phase_factor, dkx, dky, k0, pm_cfg.reflect_coeff, ...
        ssa_scatter_scale, ssa_random_scatter, seed_ssa, ssa_seed_offset, ...
        Hs_target, sigma_eta, boundary_equivalence_tol, ssa_kernel_mode, ...
        ssa_coherent_order, ssa_frequency_correlation_mode, ...
        ssa_frequency_correlation_rho, frequency_index, ...
        ssa_geometry_source_id, ssa_kz_branch, ssa_conv_padding);
    coupling_diag = local_disabled_coupling_diagnostics();
    coupling_debug = struct();
    [redistribution_diag, redistribution_debug] = local_boundary_redistribution_diagnostics( ...
        psi_inc, psi_ref, ssa_meta.R_coh .* psi_inc, KX, KY, k0, ...
        boundary_redistribution_diagnostics, boundary_redistribution_debug);
else
    surface_elevation = [];
    delta_phi = [];
    spectral_variance = sum(Phi2D(:)) * dkx * dky;
    sigma_eta_raw_m = sqrt(max(spectral_variance, 0));
    Hs_raw_m = 4 * sigma_eta_raw_m;
    Hs_raw = Hs_raw_m;
    switch roughness_scale_mode
        case 'target_hs'
            sigma_eta_target = Hs_target / 4;
            spectral_variance_continuous = sum(Phi2D(:)) * dkx * dky / (2*pi)^2;
            if spectral_variance_continuous > 0 && sigma_eta_target > 0
                scale_factor = sigma_eta_target / sqrt(spectral_variance_continuous);
            else
                scale_factor = 0;
            end
        case 'raw_pm'
            sigma_eta_target = sigma_eta_raw_m;
            scale_factor = 2*pi;
    end
    Hs_scaled = 4 * sigma_eta_target;
    W_eta = Phi2D * scale_factor^2;

    seed_kstat = pm_cfg.seed + kstat_seed_offset + frequency_index - 1;
    [psi_ref, boundary_meta, kstat_meta] = local_apply_kirchhoff_kstat( ...
        psi_inc, W_eta, KX, KY, xw, yw, dkx, dky, k0, pm_cfg.reflect_coeff, ...
        kstat_random_scatter, seed_kstat, kstat_seed_offset, Hs_target, ...
        boundary_equivalence_tol, kstat_conv_padding, kstat_trusted_angle_deg, ...
        roughness_scale_mode, sigma_eta_raw_m, Hs_raw_m, scale_factor);
    coupling_diag = local_disabled_coupling_diagnostics();
    coupling_debug = struct();
    [redistribution_diag, redistribution_debug] = local_boundary_redistribution_diagnostics( ...
        psi_inc, psi_ref, kstat_meta.R_coh .* psi_inc, KX, KY, k0, ...
        boundary_redistribution_diagnostics, boundary_redistribution_debug);
end

% -----------------------------
% 3) Sanity-check visualization
% -----------------------------
if pm_cfg.show_figure
    figure(15); clf
    subplot(1,2,1)
    if surface_realization_generated
        surf(X, Y, surface_elevation, 'EdgeColor', 'none')
        view(40, 35)
        axis tight
        xlabel('x (m)')
        ylabel('y (m)')
        zlabel('\xi(x,y) (m)')
        title('PM rough sea surface elevation')
    else
        imagesc(fftshift(log10(max(W_eta, realmin))))
        axis xy tight
        xlabel('k_x index')
        ylabel('k_y index')
        title('log10 W_\eta(K_x,K_y), no surface realization')
    end
    colorbar

    subplot(1,2,2)
    imagesc(x, y, angle(psi_ref))
    axis xy tight
    xlabel('x (m)')
    ylabel('y (m)')
    title(sprintf('Phase of reflected field angle(\\psi_{ref}), mode=%s, boundary=%s', ...
        phase_mode, boundary_model))
    colorbar
end

E_from_Phi = zeros(size(K));
E_from_Phi(mask) = Phi2D(mask) .* 2*pi .* K(mask);
rel_err = abs(E_from_Phi(mask) - E1D(mask)) ./ max(abs(E1D(mask)), eps);

meta = struct();
meta.U = U;
meta.g = g;
meta.alpha_PM = alpha_PM;
meta.beta_PM = beta_PM;
meta.dkx = dkx;
meta.dky = dky;
meta.spectrum_definition = 'E1D(K)=alpha/(2K^3)exp(-beta g^2/(U^4 K^2)); Phi2D(Kx,Ky)=E1D(K)/(2*pi*K)';
meta.E1D = local_field_stats(E1D(mask));
meta.Phi2D = local_field_stats(Phi2D(mask));
meta.phi2d_transform_error = struct( ...
    'max_rel', max(rel_err(:), [], 'omitnan'), ...
    'mean_rel', mean(rel_err(:), 'omitnan'));
meta.Hs_target = Hs_target;
meta.Hs_target_m = Hs_target;
meta.roughness_scale_mode = roughness_scale_mode;
meta.sigma_eta_raw_m = sigma_eta_raw_m;
meta.Hs_raw_m = Hs_raw_m;
meta.pm_variance_raw_discrete_m2 = pm_variance_raw_discrete_m2;
meta.sigma_eta_raw_discrete_m = sigma_eta_raw_discrete_m;
meta.Hs_raw_discrete_m = Hs_raw_discrete_m;
meta.pm_variance_raw_continuous_m2 = pm_variance_raw_continuous_m2;
meta.sigma_eta_raw_continuous_m = sigma_eta_raw_continuous_m;
meta.Hs_raw_continuous_m = Hs_raw_continuous_m;
meta.Hs_raw = Hs_raw;
meta.Hs_scaled = Hs_scaled;
meta.scale_factor = scale_factor;
meta.seed = pm_cfg.seed;
meta.reflection_coeff_used = pm_cfg.reflect_coeff;
meta.surface_realization_generated = surface_realization_generated;
meta.phase_mode_used = phase_mode;
meta.phase_factor_stats = struct( ...
    'min', min(phase_factor(:)), ...
    'max', max(phase_factor(:)), ...
    'mean', mean(phase_factor(:)));
meta.kirchhoff_phase_screen_formula = ...
    'delta_phi=k0*(cos_i+cos_r)*eta; normal incidence gives delta_phi=2*k0*eta';
meta.kirchhoff_phase_screen_legacy_note = ...
    'Before the phase-factor correction this path used 2*k0*(cos_i+cos_r)*eta, giving 4*k0*eta in normal incidence.';
meta.oblique_clip_used = clip_pair;
meta.show_figure = logical(pm_cfg.show_figure);
meta.enabled = true;
meta.boundary_model = boundary_meta.boundary_model;
meta.boundary_operator_form = boundary_meta.boundary_operator_form;
meta.boundary_dense_matrix_used = boundary_meta.boundary_dense_matrix_used;
meta.boundary_fft_convention = boundary_meta.boundary_fft_convention;
meta.boundary_equivalence_error = boundary_meta.boundary_equivalence_error;
meta.boundary_coupling_diagnostics = coupling_diag;
meta.boundary_coupling_debug = coupling_debug;
meta.boundary_redistribution_diagnostics = redistribution_diag;
meta.boundary_redistribution_debug = redistribution_debug;
meta.boundary_debug_stats = boundary_meta.boundary_debug_stats;
meta.ssa_stat_kernel_meta = ssa_meta;
meta.kirchhoff_kstat_meta = kstat_meta;
if surface_realization_generated
    meta.W_eta = local_field_stats([]);
else
    meta.W_eta = local_field_stats(W_eta(mask));
end

end

function spec = local_pm_spectrum(KX, KY, xw, yw, U)
if ~(isscalar(U) && isnumeric(U) && isfinite(U) && U > 0)
    error('pm_cfg.U must be a positive finite wind speed.');
end

g = 9.81;
alpha_PM = 8.10e-3;
beta_PM = 0.74;
K = sqrt(KX.^2 + KY.^2);
E1D = zeros(size(K));
Phi2D = zeros(size(K));

mask = (K > 0);
K_nonzero = K(mask);
E1D(mask) = (alpha_PM ./ (2 .* K_nonzero.^3)) .* ...
            exp(-beta_PM * (g^2) ./ (U^4 .* K_nonzero.^2));
Phi2D(mask) = E1D(mask) ./ (2*pi*K_nonzero);

spec = struct( ...
    'U', U, ...
    'g', g, ...
    'alpha_PM', alpha_PM, ...
    'beta_PM', beta_PM, ...
    'K', K, ...
    'E1D', E1D, ...
    'Phi2D', Phi2D, ...
    'mask', mask, ...
    'dkx', 2*pi / xw, ...
    'dky', 2*pi / yw);
end

function phase_factor = local_surface_phase_factor( ...
    phase_mode, X, Y, tx_xyz, rx_xyz, z_surface, clip_pair)
switch phase_mode
    case 'normal'
        phase_factor = 2 * ones(size(X));
    case 'oblique'
        tx_xyz = tx_xyz(:).';
        rx_xyz = rx_xyz(:).';

        dz_i = tx_xyz(3) - z_surface;
        dz_r = rx_xyz(3) - z_surface;
        if dz_i <= 0 || dz_r < 0
            error('For oblique mode, tx/rx must be at or below the surface: z >= z_surface.');
        end

        dx_i = X - tx_xyz(1);
        dy_i = Y - tx_xyz(2);
        Ri = sqrt(dx_i.^2 + dy_i.^2 + dz_i.^2);
        cos_i = dz_i ./ max(Ri, eps);

        dx_r = X - rx_xyz(1);
        dy_r = Y - rx_xyz(2);
        Rr = sqrt(dx_r.^2 + dy_r.^2 + dz_r.^2);
        cos_r = dz_r ./ max(Rr, eps);

        cos_i = min(max(cos_i, clip_pair(1)), clip_pair(2));
        cos_r = min(max(cos_r, clip_pair(1)), clip_pair(2));
        phase_factor = cos_i + cos_r;
    otherwise
        error('Unsupported phase_mode: %s', phase_mode);
end
end

function [psi_ref_xy, boundary_meta, meta] = local_apply_ssa_stat_kernel( ...
    psi_inc_xy, W_eta, KX, KY, phase_factor, dkx, dky, k0, R0, scatter_scale, ...
    random_enabled, seed_ssa, seed_offset, Hs_target, sigma_eta, equivalence_tol, ...
    kernel_mode, coherent_order, frequency_correlation_mode, frequency_correlation_rho, ...
    frequency_index, geometry_source_id, kz_branch, conv_padding)

boundary_meta = local_boundary_meta_base('ssa_stat_kernel', equivalence_tol);
boundary_meta.boundary_operator_form = sprintf( ...
    'ssa_stat_kernel:%s coherent scalar reflection plus statistical scatter power', kernel_mode);

Psi_inc_k = fft2(psi_inc_xy);
P_inc = abs(Psi_inc_k).^2;
E_inc = sum(P_inc(:));
[kz_grid, propagating_mask, propagating_bin_fraction] = local_compute_vertical_wavenumber( ...
    KX, KY, k0, kz_branch);

inc_weight = abs(psi_inc_xy).^2;
if sum(inc_weight(:)) > 0
    phase_factor_eff = sum(phase_factor(:) .* inc_weight(:)) / sum(inc_weight(:));
else
    phase_factor_eff = mean(phase_factor(:));
end

coherent_vertical_factor_eff = phase_factor_eff;
coherent_gamma_sum_eff_rad_per_m = k0 * coherent_vertical_factor_eff;
coherent_info = local_compute_ssa_coherent_reflection( ...
    W_eta, KX, KY, dkx, dky, k0, R0, sigma_eta, ...
    coherent_gamma_sum_eff_rad_per_m, coherent_vertical_factor_eff, coherent_order);
coherent_exponent = coherent_info.coherent_exponent;
R_coh_raw = coherent_info.R_coh_selected_raw;
Psi_coh_k = R_coh_raw .* Psi_inc_k;
E_coh_raw = sum(abs(Psi_coh_k(:)).^2);
coherent_energy_scale_applied = 1;
if E_inc > 0 && E_coh_raw > E_inc
    coherent_energy_scale_applied = sqrt(E_inc / E_coh_raw);
    Psi_coh_k = coherent_energy_scale_applied .* Psi_coh_k;
end
R_coh = coherent_energy_scale_applied .* R_coh_raw;
E_coh = sum(abs(Psi_coh_k(:)).^2);

[P_sca_raw, kernel_detail] = local_compute_ssa_scatter_power( ...
    kernel_mode, W_eta, P_inc, KX, KY, kz_grid, propagating_mask, ...
    dkx, dky, k0, R0, scatter_scale, phase_factor_eff, ...
    geometry_source_id, conv_padding);
E_sca_raw = sum(P_sca_raw(:));

E_sca_limit = max(E_inc - E_coh, 0);
if E_sca_raw > 0
    energy_scale_applied = min(1, E_sca_limit / E_sca_raw);
else
    energy_scale_applied = 1;
end
P_sca = P_sca_raw .* energy_scale_applied;
E_sca_limited = sum(P_sca(:));
E_sca_target = E_sca_limited;

Psi_sca_k = complex(zeros(size(Psi_inc_k)));
seed_ssa_used = local_rng_seed(seed_ssa);
random_spectrum_meta = local_empty_ssa_random_spectrum_meta( ...
    frequency_correlation_mode, frequency_correlation_rho, frequency_index, seed_ssa_used);
random_realization_energy_scale_applied = 1;
total_field_energy_scale_applied = 1;
if random_enabled && E_sca_target > 0
    [z_rand, random_spectrum_meta] = local_generate_ssa_random_spectrum( ...
        size(P_sca), seed_ssa, frequency_index, ...
        frequency_correlation_mode, frequency_correlation_rho);
    Psi_sca_k = sqrt(P_sca) .* z_rand;

    E_sca_realized = sum(abs(Psi_sca_k(:)).^2);
    if E_sca_realized > E_sca_limit && E_sca_realized > 0
        random_realization_energy_scale_applied = sqrt(E_sca_limit / E_sca_realized);
        Psi_sca_k = random_realization_energy_scale_applied .* Psi_sca_k;
    end

    E_ref = sum(abs(Psi_coh_k(:) + Psi_sca_k(:)).^2);
    if E_ref > E_inc && sum(abs(Psi_sca_k(:)).^2) > 0
        total_field_energy_scale_applied = local_scatter_scale_for_total_energy( ...
            Psi_coh_k, Psi_sca_k, E_inc);
        Psi_sca_k = total_field_energy_scale_applied .* Psi_sca_k;
    end
end

E_sca = sum(abs(Psi_sca_k(:)).^2);
Psi_ref_k = Psi_coh_k + Psi_sca_k;
psi_ref_xy = ifft2(Psi_ref_k);
E_ref = sum(abs(Psi_ref_k(:)).^2);
energy_conservation_error = max(E_ref - E_inc, 0) / max(E_inc, eps);
energy_limit_applied = E_sca_raw > 0 && energy_scale_applied < 1;
DeltaK = sqrt(KX.^2 + KY.^2);
incident_spectrum_stats = local_spectrum_redistribution_stats(P_inc, KX, KY, DeltaK);
coherent_spectrum_stats = local_spectrum_redistribution_stats(abs(Psi_coh_k).^2, KX, KY, DeltaK);
scatter_power_spectrum_stats = local_spectrum_redistribution_stats(P_sca, KX, KY, DeltaK);
reflected_spectrum_stats = local_spectrum_redistribution_stats(abs(Psi_ref_k).^2, KX, KY, DeltaK);
[W_eta_variance_target, W_eta_variance_discrete, W_eta_variance_rel_error] = ...
    local_w_eta_variance_audit(W_eta, dkx, dky, sigma_eta);

meta = struct( ...
    'enabled', true, ...
    'model', 'ssa_stat_kernel_v2_interface', ...
    'surface_realization_generated', false, ...
    'random_scatter_enabled', logical(random_enabled), ...
    'kernel_mode', kernel_mode, ...
    'coherent_order', coherent_order, ...
    'frequency_correlation_mode', frequency_correlation_mode, ...
    'frequency_correlation_rho', frequency_correlation_rho, ...
    'geometry_source_id', geometry_source_id, ...
    'kz_branch', kz_branch, ...
    'conv_padding', conv_padding, ...
    'conv_operator', local_get_detail_field(kernel_detail, 'conv_operator', 'not_recorded'), ...
    'conv_padding_size', local_get_detail_field(kernel_detail, 'conv_padding_size', [NaN, NaN]), ...
    'conv_crop_start_index', local_get_detail_field(kernel_detail, 'conv_crop_start_index', [NaN, NaN]), ...
    'conv_crop_end_index', local_get_detail_field(kernel_detail, 'conv_crop_end_index', [NaN, NaN]), ...
    'conv_crop_rule', local_get_detail_field(kernel_detail, 'conv_crop_rule', 'not_recorded'), ...
    'phase_scale_corrected_rad_per_m', local_get_detail_field(kernel_detail, 'phase_scale_corrected_rad_per_m', NaN), ...
    'phase_scale_legacy_rad_per_m', local_get_detail_field(kernel_detail, 'phase_scale_legacy_rad_per_m', NaN), ...
    'phase_scale_formula', local_get_detail_field(kernel_detail, 'phase_scale_formula', 'not_applicable'), ...
    'phase_scale_legacy_formula', local_get_detail_field(kernel_detail, 'phase_scale_legacy_formula', 'not_applicable'), ...
    'kz_stats', local_real_stats(kz_grid), ...
    'propagating_bin_fraction', propagating_bin_fraction, ...
    'formula_source', local_get_detail_field(kernel_detail, 'formula_source', 'not_applicable'), ...
    'boundary_condition', local_get_detail_field(kernel_detail, 'boundary_condition', 'not_applicable'), ...
    'evanescent_included', local_get_detail_field(kernel_detail, 'evanescent_included', false), ...
    'sigma_eta_m', sigma_eta, ...
    'Hs_target_m', Hs_target, ...
    'R_coh', R_coh, ...
    'R_coh_raw', R_coh_raw, ...
    'R_coh_ssa1', coherent_info.R_coh_ssa1, ...
    'R_coh_ssa2', coherent_info.R_coh_ssa2, ...
    'abs_R_coh_ssa1', coherent_info.abs_R_coh_ssa1, ...
    'abs_R_coh_ssa2', coherent_info.abs_R_coh_ssa2, ...
    'coherent_loss_ssa1_db', coherent_info.coherent_loss_ssa1_db, ...
    'coherent_loss_ssa2_db', coherent_info.coherent_loss_ssa2_db, ...
    'coherent_loss_delta_db', coherent_info.coherent_loss_delta_db, ...
    'delta_R_abs', coherent_info.delta_R_abs, ...
    'delta_R_rel', coherent_info.delta_R_rel, ...
    'phase_factor_eff', phase_factor_eff, ...
    'coherent_exponent', coherent_exponent, ...
    'coherent_gamma_sum_eff_rad_per_m', coherent_gamma_sum_eff_rad_per_m, ...
    'coherent_vertical_factor_eff', coherent_vertical_factor_eff, ...
    'coherent_reflection_formula', coherent_info.coherent_reflection_formula, ...
    'phase_factor_eff_legacy_note', 'phase_factor_eff is cos_i+cos_s; corrected Kirchhoff phase screen uses k0*xi*phase_factor, while SSA coherent reflection uses k0*phase_factor_eff directly as gamma_i+gamma_s.', ...
    'ssa2_correction_integral', coherent_info.ssa2_correction_integral, ...
    'ssa2_correction_integral_real', coherent_info.ssa2_correction_integral_real, ...
    'ssa2_correction_integral_imag', coherent_info.ssa2_correction_integral_imag, ...
    'ssa2_gamma_i_eff_rad_per_m', coherent_info.ssa2_gamma_i_eff_rad_per_m, ...
    'ssa2_K_i_eff_rad_per_m', coherent_info.ssa2_K_i_eff_rad_per_m, ...
    'ssa2_sqrt_branch', coherent_info.ssa2_sqrt_branch, ...
    'ssa2_formula', coherent_info.ssa2_formula, ...
    'ssa2_formula_source', coherent_info.ssa2_formula_source, ...
    'ssa2_limitations', coherent_info.ssa2_limitations, ...
    'ssa2_evanescent_handling', coherent_info.ssa2_evanescent_handling, ...
    'ssa2_propagating_integral', coherent_info.ssa2_propagating_integral, ...
    'ssa2_evanescent_integral', coherent_info.ssa2_evanescent_integral, ...
    'ssa2_evanescent_fraction_abs', coherent_info.ssa2_evanescent_fraction_abs, ...
    'W_eta_variance_target', W_eta_variance_target, ...
    'W_eta_variance_discrete', W_eta_variance_discrete, ...
    'W_eta_variance_rel_error', W_eta_variance_rel_error, ...
    'scatter_scale', scatter_scale, ...
    'P_sca', local_power_stats(P_sca), ...
    'P_sca_raw', local_power_stats(P_sca_raw), ...
    'E_inc', E_inc, ...
    'E_coh_raw', E_coh_raw, ...
    'E_coh', E_coh, ...
    'E_sca_raw', E_sca_raw, ...
    'E_sca_limited', E_sca_limited, ...
    'E_sca_target', E_sca_target, ...
    'E_sca', E_sca, ...
    'E_ref', E_ref, ...
    'E_sca_limit', E_sca_limit, ...
    'incident_spectrum_stats', incident_spectrum_stats, ...
    'coherent_spectrum_stats', coherent_spectrum_stats, ...
    'scatter_power_spectrum_stats', scatter_power_spectrum_stats, ...
    'reflected_spectrum_stats', reflected_spectrum_stats, ...
    'energy_scale_applied', energy_scale_applied, ...
    'energy_limit_applied', energy_limit_applied, ...
    'energy_conservation_error', energy_conservation_error, ...
    'coherent_energy_scale_applied', coherent_energy_scale_applied, ...
    'random_realization_energy_scale_applied', random_realization_energy_scale_applied, ...
    'total_field_energy_scale_applied', total_field_energy_scale_applied, ...
    'seed_ssa', seed_ssa_used, ...
    'seed_ssa_requested', seed_ssa, ...
    'random_spectrum_seed_base', random_spectrum_meta.random_spectrum_seed_base, ...
    'random_spectrum_seed_innovation', random_spectrum_meta.random_spectrum_seed_innovation, ...
    'random_spectrum_frequency_index', random_spectrum_meta.random_spectrum_frequency_index, ...
    'random_spectrum_generation_rule', random_spectrum_meta.random_spectrum_generation_rule, ...
    'seed_offset', seed_offset, ...
    'kernel_detail', kernel_detail, ...
    'kernel_formula', kernel_detail.kernel_formula, ...
    'normalization_note', ['W_eta is scaled so sum(W_eta)*dkx*dky=sigma_eta^2; ', ...
        'P_sca is energy-limited before random scatter synthesis; strict SSA modes require an external formula source.'], ...
    'limitations', kernel_detail.limitations);
end

function [psi_ref_xy, boundary_meta, meta] = local_apply_kirchhoff_kstat( ...
    psi_inc_xy, W_eta, KX, KY, xw, yw, dkx, dky, k0, R0, ...
    random_enabled, seed_kstat, seed_offset, Hs_target, equivalence_tol, ...
    conv_padding, trusted_angle_deg, roughness_scale_mode, sigma_eta_raw_m, ...
    Hs_raw_m, scale_factor)

boundary_meta = local_boundary_meta_base('kirchhoff_kstat', equivalence_tol);
boundary_meta.boundary_operator_form = ...
    'kirchhoff_kstat: coherent phase-screen mean plus statistical incoherent K-domain scatter power';

[ny, nx] = size(W_eta);
dx = xw / nx;
dy = yw / ny;
grid_count = numel(W_eta);
fourier_area_scale = dkx * dky / (2*pi)^2;

Psi_inc_k = fft2(psi_inc_xy);
P_inc = abs(Psi_inc_k).^2;
E_inc = sum(P_inc(:));

C_eta_xy = real(ifft2(W_eta)) * grid_count * fourier_area_scale;
sigma_eta2 = max(real(C_eta_xy(1, 1)), 0);
sigma_eta = sqrt(sigma_eta2);
alpha_rad_per_m = 2 * k0;
alpha2 = alpha_rad_per_m^2;
G_mean = exp(-0.5 * alpha2 * sigma_eta2);
R_coh = R0 .* G_mean;
Psi_coh_k = R_coh .* Psi_inc_k;

C_eta_max_excess_m2 = max(real(C_eta_xy(:))) - sigma_eta2;
C_deltaG_xy = exp(alpha2 .* (real(C_eta_xy) - sigma_eta2)) - exp(-alpha2 * sigma_eta2);
C_deltaG_xy = real(C_deltaG_xy);
S_deltaG_complex = fft2(C_deltaG_xy) * dx * dy;
S_deltaG_raw = real(S_deltaG_complex);
S_deltaG_imag_max_abs = max(abs(imag(S_deltaG_complex(:))));
S_deltaG_negative_mask = S_deltaG_raw < 0;
S_deltaG_negative_sum_abs = sum(abs(S_deltaG_raw(S_deltaG_negative_mask)));
S_deltaG_negative_min = min(S_deltaG_raw(:));
S_deltaG = max(S_deltaG_raw, 0);

phase_screen_incoherent_energy_raw = sum(S_deltaG_raw(:)) * fourier_area_scale;
phase_screen_incoherent_energy = sum(S_deltaG(:)) * fourier_area_scale;
phase_screen_energy_closure_raw = abs(G_mean)^2 + phase_screen_incoherent_energy_raw;
phase_screen_energy_closure = abs(G_mean)^2 + phase_screen_incoherent_energy;
phase_screen_energy_error_raw = abs(phase_screen_energy_closure_raw - 1);
phase_screen_energy_error = abs(phase_screen_energy_closure - 1);

[conv_power, conv_meta] = local_fft_convolution_on_k_grid(S_deltaG, P_inc, conv_padding);
P_sca_raw = abs(R0)^2 .* conv_power .* fourier_area_scale;
P_sca_negative_mask = P_sca_raw < 0;
P_sca_negative_sum_abs = sum(abs(P_sca_raw(P_sca_negative_mask)));
P_sca = max(real(P_sca_raw), 0);

Psi_sca_k = complex(zeros(size(Psi_inc_k)));
seed_kstat_used = local_rng_seed(seed_kstat);
random_generation_rule = 'not_realized: random_scatter disabled or zero scatter power';
if random_enabled && any(P_sca(:) > 0)
    rng(seed_kstat_used, 'twister')
    Z = local_complex_white_noise(size(P_sca));
    Psi_sca_k = sqrt(P_sca) .* Z;
    random_generation_rule = ...
        'independent: seed_kstat=sea_seed+surface_kstat_seed_offset+frequency_index-1';
end

Psi_ref_k = Psi_coh_k + Psi_sca_k;
psi_ref_xy = ifft2(Psi_ref_k);

Kmag = sqrt(KX.^2 + KY.^2);
propagating_mask = Kmag <= k0;
if isfinite(trusted_angle_deg)
    trusted_k_radius = k0 * sind(trusted_angle_deg);
    trusted_mask = Kmag <= trusted_k_radius;
else
    trusted_k_radius = NaN;
    trusted_mask = false(size(Kmag));
end

phase_screen_incoherent_energy_propagating = sum(S_deltaG(propagating_mask)) * fourier_area_scale;
P_sca_propagating_sum = sum(P_sca(propagating_mask));
if isfinite(trusted_angle_deg)
    phase_screen_incoherent_energy_trusted = sum(S_deltaG(trusted_mask)) * fourier_area_scale;
    P_sca_trusted_sum = sum(P_sca(trusted_mask));
else
phase_screen_incoherent_energy_trusted = NaN;
P_sca_trusted_sum = NaN;
end

if strcmp(roughness_scale_mode, 'target_hs')
    W_eta_variance_target_m2 = (Hs_target / 4)^2;
else
    W_eta_variance_target_m2 = sigma_eta2;
end
W_eta_variance_rel_error = abs(sigma_eta2 - W_eta_variance_target_m2) / ...
    max(W_eta_variance_target_m2, eps);

DeltaK = Kmag;
incident_spectrum_stats = local_spectrum_redistribution_stats(P_inc, KX, KY, DeltaK);
coherent_spectrum_stats = local_spectrum_redistribution_stats(abs(Psi_coh_k).^2, KX, KY, DeltaK);
scatter_power_spectrum_stats = local_spectrum_redistribution_stats(P_sca, KX, KY, DeltaK);
reflected_spectrum_stats = local_spectrum_redistribution_stats(abs(Psi_ref_k).^2, KX, KY, DeltaK);

E_coh = sum(abs(Psi_coh_k(:)).^2);
E_sca_expected = sum(P_sca(:));
E_sca_realized = sum(abs(Psi_sca_k(:)).^2);
E_ref = sum(abs(Psi_ref_k(:)).^2);

meta = struct( ...
    'enabled', true, ...
    'model', 'kirchhoff_kstat_phase_screen_v1', ...
    'surface_realization_generated', false, ...
    'random_scatter_enabled', logical(random_enabled), ...
    'conv_padding', conv_padding, ...
    'conv_operator', conv_meta.conv_operator, ...
    'conv_padding_size', conv_meta.conv_padding_size, ...
    'conv_crop_start_index', conv_meta.conv_crop_start_index, ...
    'conv_crop_end_index', conv_meta.conv_crop_end_index, ...
    'conv_crop_rule', conv_meta.conv_crop_rule, ...
    'trusted_angle_deg', trusted_angle_deg, ...
    'trusted_k_radius_rad_per_m', trusted_k_radius, ...
    'k0_rad_per_m', k0, ...
    'Hs_target_m', Hs_target, ...
    'roughness_scale_mode', roughness_scale_mode, ...
    'sigma_eta_raw_m', sigma_eta_raw_m, ...
    'Hs_raw_m', Hs_raw_m, ...
    'scale_factor', scale_factor, ...
    'sigma_eta2_m2', sigma_eta2, ...
    'sigma_eta_m', sigma_eta, ...
    'alpha_rad_per_m', alpha_rad_per_m, ...
    'G_mean', G_mean, ...
    'abs_G_mean2', abs(G_mean)^2, ...
    'R_coh', R_coh, ...
    'R_coh_pressure_release_normal_formula', -exp(-2 * k0^2 * sigma_eta2), ...
    'coherent_reflection_formula', ...
        '<G>=exp(-0.5*(2*k0)^2*sigma_eta^2); R_coh=R0*<G>; pressure-release R0=-1 gives -exp(-2*k0^2*sigma_eta^2)', ...
    'C_eta', local_power_stats(real(C_eta_xy)), ...
    'C_eta_zero_lag_m2', sigma_eta2, ...
    'C_eta_max_excess_m2', C_eta_max_excess_m2, ...
    'C_deltaG', local_power_stats(C_deltaG_xy), ...
    'S_deltaG', local_power_stats(S_deltaG), ...
    'S_deltaG_raw', local_power_stats(S_deltaG_raw), ...
    'S_deltaG_imag_max_abs', S_deltaG_imag_max_abs, ...
    'S_deltaG_negative_bin_count', nnz(S_deltaG_negative_mask), ...
    'S_deltaG_negative_sum_abs_before_clip', S_deltaG_negative_sum_abs, ...
    'S_deltaG_negative_min_before_clip', S_deltaG_negative_min, ...
    'P_sca', local_power_stats(P_sca), ...
    'P_sca_raw', local_power_stats(P_sca_raw), ...
    'P_sca_negative_bin_count', nnz(P_sca_negative_mask), ...
    'P_sca_negative_sum_abs_before_clip', P_sca_negative_sum_abs, ...
    'phase_screen_incoherent_energy_raw', phase_screen_incoherent_energy_raw, ...
    'phase_screen_incoherent_energy', phase_screen_incoherent_energy, ...
    'phase_screen_energy_closure_raw', phase_screen_energy_closure_raw, ...
    'phase_screen_energy_closure', phase_screen_energy_closure, ...
    'phase_screen_energy_error_raw', phase_screen_energy_error_raw, ...
    'phase_screen_energy_error', phase_screen_energy_error, ...
    'phase_screen_incoherent_energy_propagating', phase_screen_incoherent_energy_propagating, ...
    'phase_screen_incoherent_energy_trusted_angle', phase_screen_incoherent_energy_trusted, ...
    'P_sca_propagating_sum', P_sca_propagating_sum, ...
    'P_sca_trusted_angle_sum', P_sca_trusted_sum, ...
    'propagating_bin_fraction', nnz(propagating_mask) / numel(propagating_mask), ...
    'trusted_angle_bin_fraction', nnz(trusted_mask) / numel(trusted_mask), ...
    'E_inc', E_inc, ...
    'E_coh', E_coh, ...
    'E_sca_expected', E_sca_expected, ...
    'E_sca_realized', E_sca_realized, ...
    'E_ref', E_ref, ...
    'realized_surface_energy_ratio', E_ref / max(E_inc, eps), ...
    'incident_spectrum_stats', incident_spectrum_stats, ...
    'coherent_spectrum_stats', coherent_spectrum_stats, ...
    'scatter_power_spectrum_stats', scatter_power_spectrum_stats, ...
    'reflected_spectrum_stats', reflected_spectrum_stats, ...
    'seed_kstat', seed_kstat_used, ...
    'seed_kstat_requested', seed_kstat, ...
    'seed_offset', seed_offset, ...
    'random_spectrum_generation_rule', random_generation_rule, ...
    'fft_normalization_note', ['C_eta=ifft2(W_eta)*numel(W_eta)*dkx*dky/(2*pi)^2; ', ...
        'S_deltaG=fft2(C_deltaG)*dx*dy; P_sca=|R0|^2*circconv(S_deltaG,abs(Psi_inc_k).^2)*dkx*dky/(2*pi)^2.'], ...
    'W_eta_variance_target_m2', W_eta_variance_target_m2, ...
    'W_eta_variance_discrete_m2', sigma_eta2, ...
    'W_eta_variance_rel_error', W_eta_variance_rel_error, ...
    'kernel_formula', ['Kirchhoff statistical phase screen: C_deltaG(rho)=', ...
        'exp(-(2*k0)^2*sigma_eta^2)*(exp((2*k0)^2*C_eta(rho))-1); ', ...
        'P_sca(Ks)=|R0|^2/(2*pi)^2 int S_deltaG(Ks-Ki)|Psi_inc(Ki)|^2 dKi.'], ...
    'limitations', ['Near-vertical Kirchhoff / Gaussian statistical phase-screen model. ', ...
        'No explicit eta realization, SSA/NLSSA T-matrix, impedance boundary, multiple scattering, ', ...
        'or calibrated scattering cross section is introduced. Propagation-window energy is diagnostic only and is not renormalized.']);
end

function info = local_compute_ssa_coherent_reflection( ...
    W_eta, KX, KY, dkx, dky, k0, R0, sigma_eta, ...
    coherent_gamma_sum_eff_rad_per_m, coherent_vertical_factor_eff, coherent_order)

coherent_exponent = -0.5 * coherent_gamma_sum_eff_rad_per_m^2 * sigma_eta^2;
R_coh_ssa1 = R0 .* exp(coherent_exponent);

R_coh_ssa2 = complex(NaN, NaN);
ssa2_correction_integral = complex(NaN, NaN);
ssa2_propagating_integral = complex(NaN, NaN);
ssa2_evanescent_integral = complex(NaN, NaN);
ssa2_evanescent_fraction_abs = NaN;
gamma_i_eff = NaN;
K_i_eff = [NaN, NaN];
ssa2_limitations = ['not_evaluated: Broschat-style SSA2 coherent correction ', ...
    'requires pressure-release / Dirichlet R0=-1.'];

is_dirichlet = abs(R0 + 1) <= 1e-12;
if strcmp(coherent_order, 'ssa2_broschat_coherent') && ~is_dirichlet
    error('pm_surface_boundary_model:Ssa2DirichletReflectCoeffRequired', ...
        ['surface_ssa_coherent_order=''ssa2_broschat_coherent'' implements a ', ...
         'Broschat-style pressure-release / Dirichlet coherent correction and ', ...
         'requires surface_reflect_coeff=-1.']);
end

if is_dirichlet
    gamma_i_eff = 0.5 * real(coherent_gamma_sum_eff_rad_per_m);
    gamma_i_eff = min(max(gamma_i_eff, 0), k0);
    K_i_mag_eff = sqrt(max(k0^2 - gamma_i_eff^2, 0));
    K_i_eff = [K_i_mag_eff, 0];

    K_shift_x = K_i_eff(1) + KX;
    K_shift_y = K_i_eff(2) + KY;
    gamma_arg = k0^2 - (K_shift_x.^2 + K_shift_y.^2);
    gamma_shifted = sqrt(complex(gamma_arg, 0));
    correction_kernel = W_eta .* (gamma_shifted - gamma_i_eff);
    ssa2_correction_integral = sum(correction_kernel(:)) * dkx * dky;

    propagating_mask = gamma_arg >= 0;
    if any(propagating_mask(:))
        ssa2_propagating_integral = sum(correction_kernel(propagating_mask)) * dkx * dky;
    else
        ssa2_propagating_integral = complex(0, 0);
    end
    ssa2_evanescent_integral = ssa2_correction_integral - ssa2_propagating_integral;
    if abs(ssa2_correction_integral) > 0
        ssa2_evanescent_fraction_abs = abs(ssa2_evanescent_integral) / ...
            max(abs(ssa2_correction_integral), eps);
    else
        ssa2_evanescent_fraction_abs = 0;
    end

    ssa1_dirichlet = -exp(-2 * gamma_i_eff^2 * sigma_eta^2);
    R_coh_ssa2 = ssa1_dirichlet + 2 * gamma_i_eff * ...
        exp(-2 * gamma_i_eff^2 * sigma_eta^2) * ssa2_correction_integral;
    ssa2_limitations = ['Broschat 1993 one-dimensional Dirichlet coherent ', ...
        'reflection correction extended here to the project two-dimensional PM spectrum. ', ...
        'This is not second-order incoherent P_sca, a full SSA2 T-matrix, NLSSA, ', ...
        'an impedance boundary model, or an experimentally calibrated cross section. ', ...
        'For oblique mode the effective incident azimuth is assumed along +kx; ', ...
        'primary conclusions should use normal / near-vertical cases.'];
end

switch coherent_order
    case 'ssa1'
        R_coh_selected_raw = R_coh_ssa1;
    case 'ssa2_broschat_coherent'
        R_coh_selected_raw = R_coh_ssa2;
    otherwise
        error('Unsupported SSA coherent order: %s', coherent_order);
end

coherent_loss_ssa1_db = -20 * log10(max(abs(R_coh_ssa1), eps));
coherent_loss_ssa2_db = -20 * log10(max(abs(R_coh_ssa2), eps));
coherent_loss_delta_db = coherent_loss_ssa2_db - coherent_loss_ssa1_db;
delta_R_abs = abs(R_coh_ssa2 - R_coh_ssa1);
delta_R_rel = delta_R_abs / max(abs(R_coh_ssa1), eps);

info = struct( ...
    'coherent_order', coherent_order, ...
    'R_coh_selected_raw', R_coh_selected_raw, ...
    'R_coh_ssa1', R_coh_ssa1, ...
    'R_coh_ssa2', R_coh_ssa2, ...
    'abs_R_coh_ssa1', abs(R_coh_ssa1), ...
    'abs_R_coh_ssa2', abs(R_coh_ssa2), ...
    'coherent_loss_ssa1_db', coherent_loss_ssa1_db, ...
    'coherent_loss_ssa2_db', coherent_loss_ssa2_db, ...
    'coherent_loss_delta_db', coherent_loss_delta_db, ...
    'delta_R_abs', delta_R_abs, ...
    'delta_R_rel', delta_R_rel, ...
    'coherent_exponent', coherent_exponent, ...
    'coherent_reflection_formula', ['ssa1: R1=R0*exp(-0.5*(gamma_i+gamma_s)^2*sigma_eta^2); ', ...
        'normal pressure-release: R1=-exp(-2*k0^2*sigma_eta^2). ', ...
        'ssa2_broschat_coherent replaces only R_coh using the Broschat-style coherent correction.'], ...
    'ssa2_correction_integral', ssa2_correction_integral, ...
    'ssa2_correction_integral_real', real(ssa2_correction_integral), ...
    'ssa2_correction_integral_imag', imag(ssa2_correction_integral), ...
    'ssa2_gamma_i_eff_rad_per_m', gamma_i_eff, ...
    'ssa2_K_i_eff_rad_per_m', K_i_eff, ...
    'ssa2_sqrt_branch', 'sqrt(complex(k0^2-|K_i+q|^2,0)); positive real root for propagating bins and positive imaginary root for evanescent bins', ...
    'ssa2_formula', ['R2=R1+2*gamma_i*exp(-2*gamma_i^2*sigma_eta^2)*', ...
        'sum(W_eta(q)*(gamma(K_i+q)-gamma_i))*dkx*dky'], ...
    'ssa2_formula_source', 'Broschat 1993 one-dimensional Dirichlet coherent reflection coefficient; two-dimensional project extension supplied by user', ...
    'ssa2_limitations', ssa2_limitations, ...
    'ssa2_evanescent_handling', 'full complex branch integral is used; propagating-only and evanescent contributions are recorded for diagnostics', ...
    'ssa2_propagating_integral', ssa2_propagating_integral, ...
    'ssa2_evanescent_integral', ssa2_evanescent_integral, ...
    'ssa2_evanescent_fraction_abs', ssa2_evanescent_fraction_abs, ...
    'coherent_vertical_factor_eff', coherent_vertical_factor_eff);
end

function [P_sca_raw, detail] = local_compute_ssa_scatter_power( ...
    kernel_mode, W_eta, P_inc, KX, KY, kz_grid, propagating_mask, ...
    dkx, dky, k0, R0, scatter_scale, phase_factor_eff, ...
    geometry_source_id, conv_padding)

switch kernel_mode
    case 'pm_convolution'
        [conv_power, conv_meta] = local_fft_convolution_on_k_grid(W_eta, P_inc, conv_padding);
        conv_power = max(conv_power, 0);
        corrected_phase_scale_rad_per_m = k0 * phase_factor_eff;
        legacy_phase_scale_rad_per_m = 2 * k0 * phase_factor_eff;
        P_sca_raw = scatter_scale * abs(R0)^2 * corrected_phase_scale_rad_per_m^2 * ...
            dkx * dky * conv_power;
        P_sca_raw = max(real(P_sca_raw), 0);
        detail = struct( ...
            'kernel_mode', kernel_mode, ...
            'geometry_source_id', geometry_source_id, ...
            'formula_source', 'not_applicable: engineering PM convolution baseline', ...
            'boundary_condition', 'engineering scalar reflection coefficient', ...
            'evanescent_included', false, ...
            'conv_padding', conv_padding, ...
            'conv_operator', conv_meta.conv_operator, ...
            'conv_padding_size', conv_meta.conv_padding_size, ...
            'conv_crop_start_index', conv_meta.conv_crop_start_index, ...
            'conv_crop_end_index', conv_meta.conv_crop_end_index, ...
            'conv_crop_rule', conv_meta.conv_crop_rule, ...
            'uses_strict_geometry_factor', false, ...
            'uses_dense_matrix', false, ...
            'phase_scale_corrected_rad_per_m', corrected_phase_scale_rad_per_m, ...
            'phase_scale_legacy_rad_per_m', legacy_phase_scale_rad_per_m, ...
            'phase_scale_formula', 'corrected pm_convolution baseline uses k0*phase_factor_eff, where phase_factor_eff=cos_i+cos_s', ...
            'phase_scale_legacy_formula', 'legacy pm_convolution used 2*k0*phase_factor_eff and over-counted the already two-way phase factor', ...
            'G_SSA1_formula', 'not_applicable', ...
            'kernel_formula', ['pm_convolution baseline: ', ...
                'P_sca_raw=scatter_scale*abs(R0)^2*(k0*phase_factor_eff)^2*dkx*dky*', ...
                'circconv(W_eta,abs(Psi_inc_k).^2).'], ...
            'limitations', ['Engineering PM-spectrum convolution baseline. ', ...
                'No strict G_SSA(K,K'';f), angular calibration, or calibrated scattering cross section is implemented.']);
    case 'ssa1_geometry'
        local_require_dirichlet_reflect_coeff(R0, kernel_mode);
        G_note = local_compute_ssa1_geometry_factor(KX, KY, kz_grid, propagating_mask, ...
            k0, R0, geometry_source_id);
        A_inc = kz_grid .* P_inc;
        A_inc(~propagating_mask) = 0;
        [conv_power, conv_meta] = local_fft_convolution_on_k_grid(W_eta, A_inc, conv_padding);
        conv_power = max(conv_power, 0);
        P_sca_raw = 4 * scatter_scale * kz_grid .* conv_power * dkx * dky;
        P_sca_raw(~propagating_mask) = 0;
        P_sca_raw = max(real(P_sca_raw), 0);
        detail = struct( ...
            'kernel_mode', kernel_mode, ...
            'geometry_source_id', geometry_source_id, ...
            'formula_source', local_ssa1_formula_source(geometry_source_id), ...
            'boundary_condition', 'pressure-release / Dirichlet', ...
            'evanescent_included', false, ...
            'conv_padding', conv_padding, ...
            'conv_operator', conv_meta.conv_operator, ...
            'conv_padding_size', conv_meta.conv_padding_size, ...
            'conv_crop_start_index', conv_meta.conv_crop_start_index, ...
            'conv_crop_end_index', conv_meta.conv_crop_end_index, ...
            'conv_crop_rule', conv_meta.conv_crop_rule, ...
            'uses_strict_geometry_factor', true, ...
            'uses_dense_matrix', false, ...
            'G_SSA1_formula', G_note.G_SSA1_formula, ...
            'kernel_formula', ['ssa1_geometry: P_sca_raw(K)=4*C_norm*gamma(K)*', ...
                'circconv(W_eta,gamma(Kprime)*abs(Psi_inc(Kprime))^2)*dkx*dky, ', ...
                'with C_norm=surface_ssa_scatter_scale.'], ...
            'limitations', ['First-order Dirichlet SSA / perturbation-limit geometry from SSA.md. ', ...
                'No NLSSA, multiple scattering, impedance boundary, experimental calibration, or evanescent scattering is included.']);
    case 'ssa1_debug_dense'
        if ~strcmp(conv_padding, 'periodic')
            error('pm_surface_boundary_model:SsaConvPaddingNotImplemented', ...
                ['surface_ssa_conv_padding=''%s'' is not implemented for ssa1_debug_dense. ', ...
                 'Use ''periodic'' because the dense debug path validates the periodic FFT convolution.'], conv_padding);
        end
        [P_sca_raw, detail] = local_compute_scatter_power_dense( ...
            W_eta, P_inc, KX, KY, kz_grid, propagating_mask, ...
            dkx, dky, k0, R0, scatter_scale, geometry_source_id);
    otherwise
        error('Unsupported SSA kernel mode: %s', kernel_mode);
end
end

function [target_variance, discrete_variance, rel_error] = local_w_eta_variance_audit(W_eta, dkx, dky, sigma_eta)
target_variance = sigma_eta^2;
discrete_variance = sum(W_eta(:)) * dkx * dky;
if target_variance == 0
    rel_error = abs(discrete_variance);
else
    rel_error = abs(discrete_variance - target_variance) / max(abs(target_variance), eps);
end
end

function [conv_power, conv_meta] = local_fft_convolution_on_k_grid(W_eta, A_inc, conv_padding)
switch conv_padding
    case 'periodic'
        conv_power = real(ifft2(fft2(W_eta) .* fft2(A_inc)));
        conv_meta = struct( ...
            'conv_operator', 'periodic_fft_circular', ...
            'conv_padding_size', size(W_eta), ...
            'conv_crop_start_index', [1, 1], ...
            'conv_crop_end_index', size(W_eta), ...
            'conv_crop_rule', 'none: output is the native circular convolution grid');
    case 'zero_padded'
        [ny, nx] = size(W_eta);
        pad_size = [2*ny - 1, 2*nx - 1];
        W_centered = fftshift(W_eta);
        A_centered = fftshift(A_inc);
        conv_full = real(ifft2(fft2(W_centered, pad_size(1), pad_size(2)) .* ...
            fft2(A_centered, pad_size(1), pad_size(2))));

        crop_start = [floor(ny/2) + 1, floor(nx/2) + 1];
        crop_end = crop_start + [ny - 1, nx - 1];
        conv_centered = conv_full(crop_start(1):crop_end(1), crop_start(2):crop_end(2));
        conv_power = ifftshift(conv_centered);
        conv_meta = struct( ...
            'conv_operator', 'linear_fft_zero_padded', ...
            'conv_padding_size', pad_size, ...
            'conv_crop_start_index', crop_start, ...
            'conv_crop_end_index', crop_end, ...
            'conv_crop_rule', ['fftshift inputs to signed-k order; compute full zero-padded ', ...
                'linear convolution; crop the original signed-k support; ifftshift back to FFT order']);
    otherwise
        error('pm_surface_boundary_model:SsaConvPaddingUnsupported', ...
            'Unsupported surface_ssa_conv_padding=''%s''.', conv_padding);
end
conv_power = max(real(conv_power), 0);
end

function G = local_compute_ssa1_geometry_factor( ...
    KX, KY, kz_grid, propagating_mask, k0, R0, geometry_source_id) %#ok<INUSD>
gamma_valid = kz_grid(propagating_mask);
if isempty(gamma_valid)
    gamma_min = NaN;
    gamma_max = NaN;
else
    gamma_min = min(gamma_valid);
    gamma_max = max(gamma_valid);
end
G = struct( ...
    'G_SSA1_formula', 'G_SSA1(K,Kprime;f)=4*gamma(Kprime,f)*gamma(K,f)', ...
    'formula_source', local_ssa1_formula_source(geometry_source_id), ...
    'propagating_bin_fraction', nnz(propagating_mask) / numel(propagating_mask), ...
    'gamma_min', gamma_min, ...
    'gamma_max', gamma_max);
end

function [P_sca_raw, detail] = local_compute_scatter_power_dense( ...
    W_eta, P_inc, KX, KY, kz_grid, propagating_mask, ...
    dkx, dky, k0, R0, scatter_scale, geometry_source_id) %#ok<INUSD>
local_require_dirichlet_reflect_coeff(R0, 'ssa1_debug_dense');
n_bin = numel(P_inc);
if n_bin > 4096
    error('pm_surface_boundary_model:SsaDenseGridTooLarge', ...
        'ssa1_debug_dense is limited to <=4096 spectral bins. Use nx=ny<=64 for dense validation.');
end

P_sca_raw = zeros(size(P_inc));
[ny, nx] = size(P_inc);
for out_idx = 1:n_bin
    if ~propagating_mask(out_idx)
        continue
    end
    [iy_out, ix_out] = ind2sub(size(P_inc), out_idx);
    gamma_s = kz_grid(out_idx);
    acc = 0;
    for in_idx = 1:n_bin
        if ~propagating_mask(in_idx)
            continue
        end
        [iy_in, ix_in] = ind2sub(size(P_inc), in_idx);
        qy_idx = mod(iy_out - iy_in, ny) + 1;
        qx_idx = mod(ix_out - ix_in, nx) + 1;
        gamma_i = kz_grid(in_idx);
        acc = acc + W_eta(qy_idx, qx_idx) * gamma_i * P_inc(in_idx);
    end
    P_sca_raw(out_idx) = 4 * scatter_scale * gamma_s * acc * dkx * dky;
end
P_sca_raw = max(real(P_sca_raw), 0);
detail = struct( ...
    'kernel_mode', 'ssa1_debug_dense', ...
    'geometry_source_id', geometry_source_id, ...
    'formula_source', local_ssa1_formula_source(geometry_source_id), ...
    'boundary_condition', 'pressure-release / Dirichlet', ...
    'evanescent_included', false, ...
    'conv_padding', 'periodic_dense', ...
    'conv_operator', 'explicit_periodic_dense_sum', ...
    'conv_padding_size', size(W_eta), ...
    'conv_crop_start_index', [1, 1], ...
    'conv_crop_end_index', size(W_eta), ...
    'conv_crop_rule', 'none: explicit dense sum uses the same periodic index rule as periodic FFT', ...
    'uses_strict_geometry_factor', true, ...
    'uses_dense_matrix', true, ...
    'G_SSA1_formula', 'G_SSA1(K,Kprime;f)=4*gamma(Kprime,f)*gamma(K,f)', ...
    'kernel_formula', ['ssa1_debug_dense: explicit periodic sum P_sca_raw(K)=', ...
        '4*C_norm*gamma(K)*sum_Kprime W_eta(K-Kprime)*gamma(Kprime)*abs(Psi_inc(Kprime))^2*dkx*dky.'], ...
    'limitations', ['Dense debug implementation for small grids only. ', ...
        'No NLSSA, multiple scattering, impedance boundary, experimental calibration, or evanescent scattering is included.']);
end

function local_require_dirichlet_reflect_coeff(R0, kernel_mode)
if abs(R0 + 1) > 1e-12
    error('pm_surface_boundary_model:SsaDirichletReflectCoeffRequired', ...
        ['surface_ssa_kernel_mode=''%s'' uses the pressure-release / Dirichlet ', ...
         'SSA1 geometry from SSA.md and currently requires surface_reflect_coeff=-1.'], ...
        kernel_mode);
end
end

function value = local_get_detail_field(detail, field_name, default_value)
if isfield(detail, field_name)
    value = detail.(field_name);
else
    value = default_value;
end
end

function source = local_ssa1_formula_source(geometry_source_id)
if nargin < 1 || isempty(geometry_source_id)
    source = ['SSA.md; Thorsos & Broschat 1995 JASA, ', ...
        'Dirichlet SSA first-order / perturbation-limit geometry'];
else
    source = geometry_source_id;
end
end

function [kz_grid, propagating_mask, propagating_bin_fraction] = local_compute_vertical_wavenumber( ...
    KX, KY, k0, kz_branch)
if ~strcmp(kz_branch, 'downward_positive_real')
    error('Unsupported SSA kz branch: %s', kz_branch);
end
Kmag2 = KX.^2 + KY.^2;
propagating_mask = Kmag2 <= k0^2;
kz_grid = zeros(size(KX));
kz_grid(propagating_mask) = sqrt(max(k0^2 - Kmag2(propagating_mask), 0));
propagating_bin_fraction = nnz(propagating_mask) / numel(propagating_mask);
end

function scale = local_scatter_scale_for_total_energy(Psi_coh_k, Psi_sca_k, E_limit)
a = sum(abs(Psi_sca_k(:)).^2);
if a <= 0
    scale = 0;
    return
end
b = 2 * real(sum(conj(Psi_coh_k(:)) .* Psi_sca_k(:)));
c = sum(abs(Psi_coh_k(:)).^2) - E_limit;
disc = max(b^2 - 4*a*c, 0);
roots_scale = [(-b - sqrt(disc)) / (2*a), (-b + sqrt(disc)) / (2*a)];
valid = roots_scale(isfinite(roots_scale) & roots_scale >= 0 & roots_scale <= 1);
if isempty(valid)
    scale = 0;
else
    scale = max(valid);
end
end

function seed = local_rng_seed(seed_requested)
seed = mod(round(seed_requested), 2^32);
end

function meta = local_empty_ssa_random_spectrum_meta(mode, rho, frequency_index, seed_ssa_used)
meta = struct( ...
    'frequency_correlation_mode', mode, ...
    'frequency_correlation_rho', rho, ...
    'random_spectrum_seed_base', seed_ssa_used, ...
    'random_spectrum_seed_innovation', seed_ssa_used, ...
    'random_spectrum_frequency_index', frequency_index, ...
    'random_spectrum_generation_rule', 'not_realized: random_scatter disabled or zero scatter budget');
end

function [z_rand, meta] = local_generate_ssa_random_spectrum( ...
    array_size, seed_ssa_requested, frequency_index, mode, rho)

seed_current = local_rng_seed(seed_ssa_requested);
seed_base = local_rng_seed(seed_ssa_requested - frequency_index + 1);
switch mode
    case 'independent'
        rng(seed_current, 'twister')
        z_rand = local_complex_white_noise(array_size);
        seed_innovation = seed_current;
        rule = ['independent: seed_ssa=sea_seed+seed_offset+frequency_index-1; ', ...
            'matches the legacy ssa_stat_kernel random scatter realization.'];
    case 'shared_seed_phase'
        rng(seed_base, 'twister')
        z_rand = local_complex_white_noise(array_size);
        seed_innovation = seed_base;
        rule = ['shared_seed_phase: all frequencies use the same complex Gaussian ', ...
            'spectrum seed while P_sca and propagation remain frequency dependent.'];
    case 'ar1_frequency'
        rng(seed_base, 'twister')
        z_rand = local_complex_white_noise(array_size);
        seed_innovation = seed_base;
        for idx = 2:frequency_index
            seed_innovation = local_rng_seed(seed_base + idx - 1);
            rng(seed_innovation, 'twister')
            z_innovation = local_complex_white_noise(array_size);
            z_rand = rho .* z_rand + sqrt(max(1 - rho^2, 0)) .* z_innovation;
        end
        rule = ['ar1_frequency: deterministic complex Gaussian AR(1) sequence ', ...
            'over frequency_index with target adjacent innovation correlation rho.'];
    otherwise
        error('Unsupported SSA frequency correlation mode: %s', mode);
end
meta = struct( ...
    'frequency_correlation_mode', mode, ...
    'frequency_correlation_rho', rho, ...
    'random_spectrum_seed_base', seed_base, ...
    'random_spectrum_seed_innovation', seed_innovation, ...
    'random_spectrum_frequency_index', frequency_index, ...
    'random_spectrum_generation_rule', rule);
end

function z = local_complex_white_noise(array_size)
z = (randn(array_size) + 1i*randn(array_size)) / sqrt(2);
end

function meta = local_disabled_ssa_stat_kernel_meta(Hs_target, seed_offset, roughness_scale_mode)
meta = struct( ...
    'enabled', false, ...
    'model', 'off', ...
    'surface_realization_generated', false, ...
    'random_scatter_enabled', false, ...
    'kernel_mode', 'not_executed', ...
    'coherent_order', 'not_executed', ...
    'frequency_correlation_mode', 'not_executed', ...
    'frequency_correlation_rho', NaN, ...
    'geometry_source_id', '', ...
    'kz_branch', 'not_executed', ...
    'conv_padding', 'not_executed', ...
    'conv_operator', 'not_executed', ...
    'conv_padding_size', [NaN, NaN], ...
    'conv_crop_start_index', [NaN, NaN], ...
    'conv_crop_end_index', [NaN, NaN], ...
    'conv_crop_rule', 'not_executed', ...
    'phase_scale_corrected_rad_per_m', NaN, ...
    'phase_scale_legacy_rad_per_m', NaN, ...
    'phase_scale_formula', 'not_executed', ...
    'phase_scale_legacy_formula', 'not_executed', ...
    'kz_stats', local_real_stats([]), ...
    'propagating_bin_fraction', NaN, ...
    'formula_source', 'not_executed', ...
    'boundary_condition', 'not_executed', ...
    'evanescent_included', false, ...
    'sigma_eta_m', NaN, ...
    'Hs_target_m', Hs_target, ...
    'roughness_scale_mode', roughness_scale_mode, ...
    'R_coh', complex(NaN, NaN), ...
    'R_coh_raw', complex(NaN, NaN), ...
    'R_coh_ssa1', complex(NaN, NaN), ...
    'R_coh_ssa2', complex(NaN, NaN), ...
    'abs_R_coh_ssa1', NaN, ...
    'abs_R_coh_ssa2', NaN, ...
    'coherent_loss_ssa1_db', NaN, ...
    'coherent_loss_ssa2_db', NaN, ...
    'coherent_loss_delta_db', NaN, ...
    'delta_R_abs', NaN, ...
    'delta_R_rel', NaN, ...
    'coherent_exponent', NaN, ...
    'coherent_gamma_sum_eff_rad_per_m', NaN, ...
    'coherent_vertical_factor_eff', NaN, ...
    'coherent_reflection_formula', 'not_executed', ...
    'phase_factor_eff', NaN, ...
    'phase_factor_eff_legacy_note', 'not_executed', ...
    'ssa2_correction_integral', complex(NaN, NaN), ...
    'ssa2_correction_integral_real', NaN, ...
    'ssa2_correction_integral_imag', NaN, ...
    'ssa2_gamma_i_eff_rad_per_m', NaN, ...
    'ssa2_K_i_eff_rad_per_m', [NaN, NaN], ...
    'ssa2_sqrt_branch', 'not_executed', ...
    'ssa2_formula', 'not_executed', ...
    'ssa2_formula_source', 'not_executed', ...
    'ssa2_limitations', 'not_executed', ...
    'ssa2_evanescent_handling', 'not_executed', ...
    'ssa2_propagating_integral', complex(NaN, NaN), ...
    'ssa2_evanescent_integral', complex(NaN, NaN), ...
    'ssa2_evanescent_fraction_abs', NaN, ...
    'W_eta_variance_target', NaN, ...
    'W_eta_variance_discrete', NaN, ...
    'W_eta_variance_rel_error', NaN, ...
    'P_sca', local_power_stats([]), ...
    'E_inc', NaN, ...
    'E_coh', NaN, ...
    'E_sca_raw', NaN, ...
    'E_sca_limited', NaN, ...
    'E_sca', NaN, ...
    'E_ref', NaN, ...
    'incident_spectrum_stats', local_empty_spectrum_stats(), ...
    'coherent_spectrum_stats', local_empty_spectrum_stats(), ...
    'scatter_power_spectrum_stats', local_empty_spectrum_stats(), ...
    'reflected_spectrum_stats', local_empty_spectrum_stats(), ...
    'energy_scale_applied', NaN, ...
    'energy_limit_applied', false, ...
    'energy_conservation_error', NaN, ...
    'seed_ssa', NaN, ...
    'random_spectrum_seed_base', NaN, ...
    'random_spectrum_seed_innovation', NaN, ...
    'random_spectrum_frequency_index', NaN, ...
    'random_spectrum_generation_rule', 'not_executed', ...
    'seed_offset', seed_offset, ...
    'kernel_detail', struct(), ...
    'kernel_formula', 'not_executed', ...
    'limitations', 'not_executed');
end

function meta = local_disabled_kirchhoff_kstat_meta(Hs_target, seed_offset, conv_padding, ...
    trusted_angle_deg, roughness_scale_mode)
meta = struct( ...
    'enabled', false, ...
    'model', 'off', ...
    'surface_realization_generated', false, ...
    'random_scatter_enabled', false, ...
    'conv_padding', conv_padding, ...
    'conv_operator', 'not_executed', ...
    'conv_padding_size', [NaN, NaN], ...
    'conv_crop_start_index', [NaN, NaN], ...
    'conv_crop_end_index', [NaN, NaN], ...
    'conv_crop_rule', 'not_executed', ...
    'trusted_angle_deg', trusted_angle_deg, ...
    'trusted_k_radius_rad_per_m', NaN, ...
    'k0_rad_per_m', NaN, ...
    'Hs_target_m', Hs_target, ...
    'roughness_scale_mode', roughness_scale_mode, ...
    'sigma_eta_raw_m', NaN, ...
    'Hs_raw_m', NaN, ...
    'scale_factor', NaN, ...
    'sigma_eta2_m2', NaN, ...
    'sigma_eta_m', NaN, ...
    'alpha_rad_per_m', NaN, ...
    'G_mean', complex(NaN, NaN), ...
    'abs_G_mean2', NaN, ...
    'R_coh', complex(NaN, NaN), ...
    'R_coh_pressure_release_normal_formula', complex(NaN, NaN), ...
    'coherent_reflection_formula', 'not_executed', ...
    'C_eta', local_power_stats([]), ...
    'C_eta_zero_lag_m2', NaN, ...
    'C_eta_max_excess_m2', NaN, ...
    'C_deltaG', local_power_stats([]), ...
    'S_deltaG', local_power_stats([]), ...
    'S_deltaG_raw', local_power_stats([]), ...
    'S_deltaG_imag_max_abs', NaN, ...
    'S_deltaG_negative_bin_count', 0, ...
    'S_deltaG_negative_sum_abs_before_clip', NaN, ...
    'S_deltaG_negative_min_before_clip', NaN, ...
    'P_sca', local_power_stats([]), ...
    'P_sca_raw', local_power_stats([]), ...
    'P_sca_negative_bin_count', 0, ...
    'P_sca_negative_sum_abs_before_clip', NaN, ...
    'phase_screen_incoherent_energy_raw', NaN, ...
    'phase_screen_incoherent_energy', NaN, ...
    'phase_screen_energy_closure_raw', NaN, ...
    'phase_screen_energy_closure', NaN, ...
    'phase_screen_energy_error_raw', NaN, ...
    'phase_screen_energy_error', NaN, ...
    'phase_screen_incoherent_energy_propagating', NaN, ...
    'phase_screen_incoherent_energy_trusted_angle', NaN, ...
    'P_sca_propagating_sum', NaN, ...
    'P_sca_trusted_angle_sum', NaN, ...
    'propagating_bin_fraction', NaN, ...
    'trusted_angle_bin_fraction', NaN, ...
    'E_inc', NaN, ...
    'E_coh', NaN, ...
    'E_sca_expected', NaN, ...
    'E_sca_realized', NaN, ...
    'E_ref', NaN, ...
    'realized_surface_energy_ratio', NaN, ...
    'incident_spectrum_stats', local_empty_spectrum_stats(), ...
    'coherent_spectrum_stats', local_empty_spectrum_stats(), ...
    'scatter_power_spectrum_stats', local_empty_spectrum_stats(), ...
    'reflected_spectrum_stats', local_empty_spectrum_stats(), ...
    'seed_kstat', NaN, ...
    'seed_kstat_requested', NaN, ...
    'seed_offset', seed_offset, ...
    'random_spectrum_generation_rule', 'not_executed', ...
    'fft_normalization_note', 'not_executed', ...
    'W_eta_variance_target_m2', (Hs_target / 4)^2, ...
    'W_eta_variance_discrete_m2', NaN, ...
    'W_eta_variance_rel_error', NaN, ...
    'kernel_formula', 'not_executed', ...
    'limitations', 'not_executed');
end

function stats = local_empty_spectrum_stats()
stats = struct( ...
    'total_energy', NaN, ...
    'centroid_kx_rad_per_m', NaN, ...
    'centroid_ky_rad_per_m', NaN, ...
    'rms_delta_k_rad_per_m', NaN, ...
    'energy_radius_50_rad_per_m', NaN, ...
    'energy_radius_90_rad_per_m', NaN, ...
    'energy_radius_95_rad_per_m', NaN, ...
    'energy_radius_99_rad_per_m', NaN, ...
    'max_nonzero_k_radius_rad_per_m', NaN);
end

function stats = local_power_stats(P)
if isempty(P)
    stats = struct('min', NaN, 'max', NaN, 'mean', NaN, 'std', NaN, 'sum', NaN, 'finite_count', 0);
    return
end
valid = isfinite(P(:));
if ~any(valid)
    stats = struct('min', NaN, 'max', NaN, 'mean', NaN, 'std', NaN, 'sum', NaN, 'finite_count', 0);
    return
end
v = P(valid);
stats = struct( ...
    'min', min(v), ...
    'max', max(v), ...
    'mean', mean(v), ...
    'std', std(v), ...
    'sum', sum(v), ...
    'finite_count', nnz(valid));
end

function stats = local_real_stats(x)
if isempty(x)
    stats = struct('min', NaN, 'max', NaN, 'mean', NaN, 'std', NaN, 'finite_count', 0);
    return
end
valid = isfinite(x(:));
if ~any(valid)
    stats = struct('min', NaN, 'max', NaN, 'mean', NaN, 'std', NaN, 'finite_count', 0);
    return
end
v = real(x(valid));
stats = struct( ...
    'min', min(v), ...
    'max', max(v), ...
    'mean', mean(v), ...
    'std', std(v), ...
    'finite_count', nnz(valid));
end

function [diag, debug] = local_boundary_redistribution_diagnostics( ...
    psi_inc_xy, psi_ref_xy, psi_flat_ref_xy, KX, KY, k0, enabled, debug_enabled)
diag = local_disabled_redistribution_diagnostics();
debug = struct();
if ~enabled
    return
end

Psi_inc_k = fft2(psi_inc_xy);
Psi_ref_k = fft2(psi_ref_xy);
Psi_flat_ref_k = fft2(psi_flat_ref_xy);
P_inc = abs(Psi_inc_k).^2;
P_ref = abs(Psi_ref_k).^2;
P_flat = abs(Psi_flat_ref_k).^2;
DeltaK = sqrt(KX.^2 + KY.^2);

inc_stats = local_spectrum_redistribution_stats(P_inc, KX, KY, DeltaK);
ref_stats = local_spectrum_redistribution_stats(P_ref, KX, KY, DeltaK);
flat_stats = local_spectrum_redistribution_stats(P_flat, KX, KY, DeltaK);

high_k_threshold = inc_stats.energy_radius_90_rad_per_m;
reflect_high_k_fraction = local_high_k_fraction(P_ref, DeltaK, high_k_threshold);
flat_high_k_fraction = local_high_k_fraction(P_flat, DeltaK, high_k_threshold);
incident_evanescent_fraction = local_high_k_fraction(P_inc, DeltaK, k0);
reflect_evanescent_fraction = local_high_k_fraction(P_ref, DeltaK, k0);
flat_evanescent_fraction = local_high_k_fraction(P_flat, DeltaK, k0);

centroid_shift_kx = ref_stats.centroid_kx_rad_per_m - inc_stats.centroid_kx_rad_per_m;
centroid_shift_ky = ref_stats.centroid_ky_rad_per_m - inc_stats.centroid_ky_rad_per_m;
incident_centroid_k_radius = hypot(inc_stats.centroid_kx_rad_per_m, inc_stats.centroid_ky_rad_per_m);

diag = struct( ...
    'enabled', true, ...
    'diagnostic_target', 'incident and reflected boundary spectra', ...
    'spectrum_quantity', 'P_k = abs(fft2(psi_xy)).^2', ...
    'angle_definition', 'theta_deg = asind(min(K_h/k0,1)), where K_h=sqrt(Kx^2+Ky^2) and theta is measured from the vertical propagation axis', ...
    'k0_rad_per_m', k0, ...
    'incident_total_energy', inc_stats.total_energy, ...
    'incident_centroid_kx_rad_per_m', inc_stats.centroid_kx_rad_per_m, ...
    'incident_centroid_ky_rad_per_m', inc_stats.centroid_ky_rad_per_m, ...
    'incident_centroid_k_radius_rad_per_m', incident_centroid_k_radius, ...
    'incident_rms_delta_k_rad_per_m', inc_stats.rms_delta_k_rad_per_m, ...
    'incident_energy_radius_50_rad_per_m', inc_stats.energy_radius_50_rad_per_m, ...
    'incident_energy_radius_90_rad_per_m', inc_stats.energy_radius_90_rad_per_m, ...
    'incident_energy_radius_95_rad_per_m', inc_stats.energy_radius_95_rad_per_m, ...
    'incident_energy_radius_99_rad_per_m', inc_stats.energy_radius_99_rad_per_m, ...
    'incident_max_nonzero_k_radius_rad_per_m', inc_stats.max_nonzero_k_radius_rad_per_m, ...
    'incident_angle_50_deg', local_k_radius_to_angle_deg(inc_stats.energy_radius_50_rad_per_m, k0), ...
    'incident_angle_90_deg', local_k_radius_to_angle_deg(inc_stats.energy_radius_90_rad_per_m, k0), ...
    'incident_angle_95_deg', local_k_radius_to_angle_deg(inc_stats.energy_radius_95_rad_per_m, k0), ...
    'incident_angle_99_deg', local_k_radius_to_angle_deg(inc_stats.energy_radius_99_rad_per_m, k0), ...
    'incident_rms_angle_deg', local_k_radius_to_angle_deg(inc_stats.rms_delta_k_rad_per_m, k0), ...
    'incident_centroid_angle_deg', local_k_radius_to_angle_deg(incident_centroid_k_radius, k0), ...
    'incident_evanescent_high_k_fraction', incident_evanescent_fraction, ...
    'reflect_total_energy', ref_stats.total_energy, ...
    'reflect_centroid_kx_rad_per_m', ref_stats.centroid_kx_rad_per_m, ...
    'reflect_centroid_ky_rad_per_m', ref_stats.centroid_ky_rad_per_m, ...
    'reflect_rms_delta_k_rad_per_m', ref_stats.rms_delta_k_rad_per_m, ...
    'reflect_energy_radius_50_rad_per_m', ref_stats.energy_radius_50_rad_per_m, ...
    'reflect_energy_radius_90_rad_per_m', ref_stats.energy_radius_90_rad_per_m, ...
    'reflect_energy_radius_95_rad_per_m', ref_stats.energy_radius_95_rad_per_m, ...
    'reflect_energy_radius_99_rad_per_m', ref_stats.energy_radius_99_rad_per_m, ...
    'reflect_max_nonzero_k_radius_rad_per_m', ref_stats.max_nonzero_k_radius_rad_per_m, ...
    'reflect_evanescent_high_k_fraction', reflect_evanescent_fraction, ...
    'rms_delta_k_increase_rad_per_m', ref_stats.rms_delta_k_rad_per_m - inc_stats.rms_delta_k_rad_per_m, ...
    'centroid_shift_kx_rad_per_m', centroid_shift_kx, ...
    'centroid_shift_ky_rad_per_m', centroid_shift_ky, ...
    'centroid_shift_mag_rad_per_m', hypot(centroid_shift_kx, centroid_shift_ky), ...
    'high_k_threshold_rad_per_m', high_k_threshold, ...
    'reflect_high_k_fraction', reflect_high_k_fraction, ...
    'flat_ref_rms_delta_k_rad_per_m', flat_stats.rms_delta_k_rad_per_m, ...
    'flat_ref_energy_radius_50_rad_per_m', flat_stats.energy_radius_50_rad_per_m, ...
    'flat_ref_energy_radius_90_rad_per_m', flat_stats.energy_radius_90_rad_per_m, ...
    'flat_ref_energy_radius_95_rad_per_m', flat_stats.energy_radius_95_rad_per_m, ...
    'flat_ref_energy_radius_99_rad_per_m', flat_stats.energy_radius_99_rad_per_m, ...
    'flat_ref_max_nonzero_k_radius_rad_per_m', flat_stats.max_nonzero_k_radius_rad_per_m, ...
    'flat_ref_high_k_fraction', flat_high_k_fraction, ...
    'flat_ref_evanescent_high_k_fraction', flat_evanescent_fraction, ...
    'rough_vs_flat_rms_delta_k_increase_rad_per_m', ref_stats.rms_delta_k_rad_per_m - flat_stats.rms_delta_k_rad_per_m, ...
    'rough_vs_flat_energy_radius_90_increase_rad_per_m', ref_stats.energy_radius_90_rad_per_m - flat_stats.energy_radius_90_rad_per_m, ...
    'rough_vs_flat_high_k_fraction_increase', reflect_high_k_fraction - flat_high_k_fraction, ...
    'interpretation', ['Compares the current incident angular spectrum with the boundary-reflected spectrum. ', ...
        'Incident angle fields estimate the main propagating support of psi_inc at the sea surface; ', ...
        'larger reflected rms_delta_k, centroid shift, and high-k fraction indicate stronger spectrum redistribution for this incident field.'], ...
    'limitations', ['Diagnostic only: these are incident-weighted spectrum moments under the selected boundary operator, ', ...
        'K_h>k0 is reported as evanescent/high-k and is clipped to 90 degrees only for angle summaries; ', ...
        'not T-matrix entries, SSA/NLSSA terms, scattering cross sections, or statistical channel generation.']);

if debug_enabled
    debug = struct( ...
        'high_k_threshold_rad_per_m', high_k_threshold, ...
        'incident', local_redistribution_debug(P_inc, DeltaK, KX, KY, k0), ...
        'reflect', local_redistribution_debug(P_ref, DeltaK, KX, KY, k0), ...
        'flat_ref', local_redistribution_debug(P_flat, DeltaK, KX, KY, k0));
end
end

function stats = local_spectrum_redistribution_stats(P_k, KX, KY, DeltaK)
total_energy = sum(P_k(:));
den = max(total_energy, eps);
nonzero_mask = isfinite(P_k) & P_k > 0 & isfinite(DeltaK);
if any(nonzero_mask(:))
    max_nonzero_k_radius = max(DeltaK(nonzero_mask));
else
    max_nonzero_k_radius = NaN;
end
stats = struct( ...
    'total_energy', total_energy, ...
    'centroid_kx_rad_per_m', sum(KX(:) .* P_k(:)) / den, ...
    'centroid_ky_rad_per_m', sum(KY(:) .* P_k(:)) / den, ...
    'rms_delta_k_rad_per_m', sqrt(sum((DeltaK(:).^2) .* P_k(:)) / den), ...
    'energy_radius_50_rad_per_m', local_weighted_radius(DeltaK(:), P_k(:), 0.50), ...
    'energy_radius_90_rad_per_m', local_weighted_radius(DeltaK(:), P_k(:), 0.90), ...
    'energy_radius_95_rad_per_m', local_weighted_radius(DeltaK(:), P_k(:), 0.95), ...
    'energy_radius_99_rad_per_m', local_weighted_radius(DeltaK(:), P_k(:), 0.99), ...
    'max_nonzero_k_radius_rad_per_m', max_nonzero_k_radius);
end

function theta_deg = local_k_radius_to_angle_deg(k_radius, k0)
theta_deg = NaN(size(k_radius));
if ~(isfinite(k0) && k0 > 0)
    return
end
valid = isfinite(k_radius);
theta_deg(valid) = asind(min(max(k_radius(valid) / k0, 0), 1));
end

function frac = local_high_k_fraction(P_k, DeltaK, threshold)
total_energy = sum(P_k(:));
if ~(isfinite(threshold) && total_energy > 0)
    frac = NaN;
    return
end
frac = sum(P_k(DeltaK > threshold)) / max(total_energy, eps);
end

function diag = local_disabled_redistribution_diagnostics()
diag = struct( ...
    'enabled', false, ...
    'diagnostic_target', 'incident and reflected boundary spectra', ...
    'spectrum_quantity', 'P_k = abs(fft2(psi_xy)).^2', ...
    'angle_definition', 'theta_deg = asind(min(K_h/k0,1)), where K_h=sqrt(Kx^2+Ky^2) and theta is measured from the vertical propagation axis', ...
    'k0_rad_per_m', NaN, ...
    'incident_total_energy', NaN, ...
    'incident_centroid_kx_rad_per_m', NaN, ...
    'incident_centroid_ky_rad_per_m', NaN, ...
    'incident_centroid_k_radius_rad_per_m', NaN, ...
    'incident_rms_delta_k_rad_per_m', NaN, ...
    'incident_energy_radius_50_rad_per_m', NaN, ...
    'incident_energy_radius_90_rad_per_m', NaN, ...
    'incident_energy_radius_95_rad_per_m', NaN, ...
    'incident_energy_radius_99_rad_per_m', NaN, ...
    'incident_max_nonzero_k_radius_rad_per_m', NaN, ...
    'incident_angle_50_deg', NaN, ...
    'incident_angle_90_deg', NaN, ...
    'incident_angle_95_deg', NaN, ...
    'incident_angle_99_deg', NaN, ...
    'incident_rms_angle_deg', NaN, ...
    'incident_centroid_angle_deg', NaN, ...
    'incident_evanescent_high_k_fraction', NaN, ...
    'reflect_total_energy', NaN, ...
    'reflect_centroid_kx_rad_per_m', NaN, ...
    'reflect_centroid_ky_rad_per_m', NaN, ...
    'reflect_rms_delta_k_rad_per_m', NaN, ...
    'reflect_energy_radius_50_rad_per_m', NaN, ...
    'reflect_energy_radius_90_rad_per_m', NaN, ...
    'reflect_energy_radius_95_rad_per_m', NaN, ...
    'reflect_energy_radius_99_rad_per_m', NaN, ...
    'reflect_max_nonzero_k_radius_rad_per_m', NaN, ...
    'reflect_evanescent_high_k_fraction', NaN, ...
    'rms_delta_k_increase_rad_per_m', NaN, ...
    'centroid_shift_kx_rad_per_m', NaN, ...
    'centroid_shift_ky_rad_per_m', NaN, ...
    'centroid_shift_mag_rad_per_m', NaN, ...
    'high_k_threshold_rad_per_m', NaN, ...
    'reflect_high_k_fraction', NaN, ...
    'flat_ref_rms_delta_k_rad_per_m', NaN, ...
    'flat_ref_energy_radius_50_rad_per_m', NaN, ...
    'flat_ref_energy_radius_90_rad_per_m', NaN, ...
    'flat_ref_energy_radius_95_rad_per_m', NaN, ...
    'flat_ref_energy_radius_99_rad_per_m', NaN, ...
    'flat_ref_max_nonzero_k_radius_rad_per_m', NaN, ...
    'flat_ref_high_k_fraction', NaN, ...
    'flat_ref_evanescent_high_k_fraction', NaN, ...
    'rough_vs_flat_rms_delta_k_increase_rad_per_m', NaN, ...
    'rough_vs_flat_energy_radius_90_increase_rad_per_m', NaN, ...
    'rough_vs_flat_high_k_fraction_increase', NaN, ...
    'interpretation', 'not_executed', ...
    'limitations', 'not_executed');
end

function debug = local_redistribution_debug(P_k, DeltaK, KX, KY, k0)
nbin = 16;
max_delta_k = max(DeltaK(:));
if max_delta_k <= 0 || ~isfinite(max_delta_k)
    bin_edges = zeros(1, nbin + 1);
    radial_energy = zeros(1, nbin);
else
    bin_edges = linspace(0, max_delta_k, nbin + 1);
    radial_energy = zeros(1, nbin);
    for ib = 1:nbin
        if ib == nbin
            mask_bin = DeltaK >= bin_edges(ib) & DeltaK <= bin_edges(ib + 1);
        else
            mask_bin = DeltaK >= bin_edges(ib) & DeltaK < bin_edges(ib + 1);
        end
        radial_energy(ib) = sum(P_k(mask_bin));
    end
end

total_energy = sum(P_k(:));
top_n = min(8, numel(P_k));
[top_energy, top_idx] = maxk(P_k(:), top_n);
debug = struct( ...
    'radial_bin_edges_rad_per_m', bin_edges, ...
    'radial_energy_fraction', radial_energy / max(total_energy, eps), ...
    'top_peak_energy', top_energy(:).', ...
    'top_peak_fraction', top_energy(:).' / max(total_energy, eps), ...
    'top_peak_kx_rad_per_m', KX(top_idx).', ...
    'top_peak_ky_rad_per_m', KY(top_idx).', ...
    'top_peak_delta_k_rad_per_m', DeltaK(top_idx).', ...
    'top_peak_angle_deg', local_k_radius_to_angle_deg(DeltaK(top_idx).', k0), ...
    'top_peak_evanescent_mask', DeltaK(top_idx).' > k0);
end

function [diag, debug] = local_boundary_coupling_diagnostics(G_xy, KX, KY, enabled, debug_enabled)
diag = local_disabled_coupling_diagnostics();
debug = struct();
if ~enabled
    return
end

G_hat_k = fft2(G_xy);
P_k = abs(G_hat_k).^2;
DeltaK = sqrt(KX.^2 + KY.^2);

total_energy = sum(P_k(:));
zero_energy = P_k(1, 1);
nonzero_energy = max(total_energy - zero_energy, 0);
nonzero_mask = true(size(P_k));
nonzero_mask(1, 1) = false;

nonzero_fraction = nonzero_energy / max(total_energy, eps);
rms_delta_k = sqrt(sum((DeltaK(:).^2) .* P_k(:)) / max(total_energy, eps));
if nonzero_energy > 0
    rms_delta_k_nonzero = sqrt(sum((DeltaK(nonzero_mask).^2) .* P_k(nonzero_mask)) / nonzero_energy);
else
    rms_delta_k_nonzero = NaN;
end

diag = struct( ...
    'enabled', true, ...
    'diagnostic_target', 'Kirchhoff boundary screen G_xy', ...
    'spectrum_quantity', 'P_k = abs(fft2(G_xy)).^2', ...
    'total_spectral_energy', total_energy, ...
    'zero_wavenumber_energy', zero_energy, ...
    'nonzero_wavenumber_energy', nonzero_energy, ...
    'nonzero_power_fraction', nonzero_fraction, ...
    'rms_delta_k_rad_per_m', rms_delta_k, ...
    'rms_delta_k_nonzero_rad_per_m', rms_delta_k_nonzero, ...
    'energy_radius_50_rad_per_m', local_weighted_radius(DeltaK(:), P_k(:), 0.50), ...
    'energy_radius_90_rad_per_m', local_weighted_radius(DeltaK(:), P_k(:), 0.90), ...
    'energy_radius_95_rad_per_m', local_weighted_radius(DeltaK(:), P_k(:), 0.95), ...
    'nonzero_energy_radius_90_rad_per_m', local_weighted_radius( ...
        DeltaK(nonzero_mask), P_k(nonzero_mask), 0.90), ...
    'interpretation', ['Larger nonzero_power_fraction and rms_delta_k indicate a less uniform ', ...
        'Kirchhoff screen and stronger potential off-diagonal Kprime-to-K coupling in the implicit convolution.'], ...
    'limitations', ['Diagnostic only: these are spectrum metrics of the Kirchhoff phase screen, ', ...
        'not T-matrix entries, SSA/NLSSA terms, scattering cross sections, or statistical channel generation.']);

if debug_enabled
    debug = local_boundary_coupling_debug(P_k, DeltaK, KX, KY, nonzero_mask);
end
end

function diag = local_disabled_coupling_diagnostics()
diag = struct( ...
    'enabled', false, ...
    'diagnostic_target', 'Kirchhoff boundary screen G_xy', ...
    'spectrum_quantity', 'P_k = abs(fft2(G_xy)).^2', ...
    'total_spectral_energy', NaN, ...
    'zero_wavenumber_energy', NaN, ...
    'nonzero_wavenumber_energy', NaN, ...
    'nonzero_power_fraction', NaN, ...
    'rms_delta_k_rad_per_m', NaN, ...
    'rms_delta_k_nonzero_rad_per_m', NaN, ...
    'energy_radius_50_rad_per_m', NaN, ...
    'energy_radius_90_rad_per_m', NaN, ...
    'energy_radius_95_rad_per_m', NaN, ...
    'nonzero_energy_radius_90_rad_per_m', NaN, ...
    'interpretation', 'not_executed', ...
    'limitations', 'not_executed');
end

function radius = local_weighted_radius(radius_values, weights, fraction)
radius_values = radius_values(:);
weights = weights(:);
valid = isfinite(radius_values) & isfinite(weights) & weights >= 0;
radius_values = radius_values(valid);
weights = weights(valid);
if isempty(weights) || sum(weights) <= 0
    radius = NaN;
    return
end

[radius_sorted, order] = sort(radius_values);
weights_sorted = weights(order);
cum_weights = cumsum(weights_sorted);
target = max(0, min(1, fraction)) * cum_weights(end);
idx = find(cum_weights >= target, 1, 'first');
radius = radius_sorted(idx);
end

function debug = local_boundary_coupling_debug(P_k, DeltaK, KX, KY, nonzero_mask)
nbin = 16;
max_delta_k = max(DeltaK(:));
if max_delta_k <= 0 || ~isfinite(max_delta_k)
    bin_edges = zeros(1, nbin + 1);
    radial_energy = zeros(1, nbin);
else
    bin_edges = linspace(0, max_delta_k, nbin + 1);
    radial_energy = zeros(1, nbin);
    for ib = 1:nbin
        if ib == nbin
            mask_bin = DeltaK >= bin_edges(ib) & DeltaK <= bin_edges(ib + 1);
        else
            mask_bin = DeltaK >= bin_edges(ib) & DeltaK < bin_edges(ib + 1);
        end
        radial_energy(ib) = sum(P_k(mask_bin));
    end
end

total_energy = sum(P_k(:));
radial_energy_fraction = radial_energy / max(total_energy, eps);

nonzero_power = P_k;
nonzero_power(~nonzero_mask) = -Inf;
top_n = min(8, nnz(nonzero_mask));
[top_energy, top_idx] = maxk(nonzero_power(:), top_n);
finite_top = isfinite(top_energy);
top_energy = top_energy(finite_top);
top_idx = top_idx(finite_top);

debug = struct( ...
    'radial_bin_edges_rad_per_m', bin_edges, ...
    'radial_energy_fraction', radial_energy_fraction, ...
    'top_nonzero_peak_energy', top_energy(:).', ...
    'top_nonzero_peak_fraction', (top_energy(:).' / max(total_energy, eps)), ...
    'top_nonzero_peak_kx_rad_per_m', KX(top_idx).', ...
    'top_nonzero_peak_ky_rad_per_m', KY(top_idx).', ...
    'top_nonzero_peak_delta_k_rad_per_m', DeltaK(top_idx).');
end

function [psi_ref_xy, boundary_meta] = local_apply_kirchhoff_boundary( ...
    psi_inc_xy, G_xy, boundary_model, check_equivalence, debug_flag, equivalence_tol)
%LOCAL_APPLY_KIRCHHOFF_BOUNDARY Apply the phase screen through the selected interface.

boundary_meta = local_boundary_meta_base(boundary_model, equivalence_tol);

switch boundary_model
    case 'kirchhoff_spatial'
        psi_ref_xy = G_xy .* psi_inc_xy;
        boundary_meta.boundary_operator_form = ...
            'spatial_pointwise: psi_ref_xy = G_xy .* psi_inc_xy';

        if check_equivalence
            psi_ref_kdomain_xy = local_apply_kdomain_boundary(psi_inc_xy, G_xy);
            boundary_meta.boundary_equivalence_error = local_boundary_equivalence_error( ...
                psi_ref_xy, psi_ref_kdomain_xy, equivalence_tol, true, ...
                'kirchhoff_spatial', 'kirchhoff_kdomain');
        end

    case 'kirchhoff_kdomain'
        psi_ref_xy = local_apply_kdomain_boundary(psi_inc_xy, G_xy);
        boundary_meta.boundary_operator_form = ...
            'implicit_fft_convolution: Psi_inc_k -> fft2(G_xy .* ifft2(Psi_inc_k)) -> Psi_ref_k';

        if check_equivalence
            psi_ref_spatial_xy = G_xy .* psi_inc_xy;
            boundary_meta.boundary_equivalence_error = local_boundary_equivalence_error( ...
                psi_ref_spatial_xy, psi_ref_xy, equivalence_tol, true, ...
                'kirchhoff_spatial', 'kirchhoff_kdomain');
        end

    otherwise
        error('Unsupported boundary_model: %s', boundary_model);
end

if debug_flag
    Psi_inc_k = fft2(psi_inc_xy);
    Psi_ref_k = fft2(psi_ref_xy);
    G_hat_k = fft2(G_xy);
    boundary_meta.boundary_debug_stats = struct( ...
        'ny', size(psi_inc_xy, 1), ...
        'nx', size(psi_inc_xy, 2), ...
        'psi_inc_norm_l2', norm(psi_inc_xy(:)), ...
        'psi_ref_norm_l2', norm(psi_ref_xy(:)), ...
        'Psi_inc_k_norm_l2', norm(Psi_inc_k(:)), ...
        'Psi_ref_k_norm_l2', norm(Psi_ref_k(:)), ...
        'G_abs_min', min(abs(G_xy(:))), ...
        'G_abs_max', max(abs(G_xy(:))), ...
        'G_hat_norm_l2', norm(G_hat_k(:)));
end
end

function psi_ref_xy = local_apply_kdomain_boundary(psi_inc_xy, G_xy)
Psi_inc_k = fft2(psi_inc_xy);
Psi_ref_k = fft2(G_xy .* ifft2(Psi_inc_k));
psi_ref_xy = ifft2(Psi_ref_k);
end

function boundary_meta = local_boundary_meta_base(boundary_model, equivalence_tol)
boundary_meta = struct( ...
    'boundary_model', boundary_model, ...
    'boundary_operator_form', '', ...
    'boundary_dense_matrix_used', false, ...
    'boundary_fft_convention', local_boundary_fft_convention(), ...
    'boundary_equivalence_error', local_boundary_equivalence_error( ...
        [], [], equivalence_tol, false, '', ''), ...
    'boundary_debug_stats', struct());
end

function err = local_boundary_equivalence_error(ref_xy, test_xy, tol, enabled, ref_model, test_model)
if ~enabled
    err = struct( ...
        'enabled', false, ...
        'reference_model', ref_model, ...
        'comparison_model', test_model, ...
        'max_abs', NaN, ...
        'rel_l2', NaN, ...
        'tol', tol, ...
        'passed', false);
    return
end

diff_xy = test_xy - ref_xy;
max_abs = max(abs(diff_xy(:)));
rel_l2 = norm(diff_xy(:)) / max(norm(ref_xy(:)), eps);
err = struct( ...
    'enabled', true, ...
    'reference_model', ref_model, ...
    'comparison_model', test_model, ...
    'max_abs', max_abs, ...
    'rel_l2', rel_l2, ...
    'tol', tol, ...
    'passed', rel_l2 <= tol);
end

function convention = local_boundary_fft_convention()
convention = ['MATLAB fft2 forward transform is unnormalized; ifft2 includes 1/(nx*ny). ', ...
    'Transverse wavenumbers use [0:N/2-1,-N/2:-1]*2*pi/L in x and y. ', ...
    'The implicit boundary operator is represented by circular convolution on the periodic transverse grid.'];
end

function out = local_normalize_choice(v, name)
if isstring(v)
    v = char(v);
end
if ~ischar(v)
    error('%s must be a string or char.', name);
end
out = lower(v);
end

function out = local_force_int(v, name)
if ~isscalar(v) || ~isfinite(v)
    error('%s must be a finite scalar.', name);
end
out = round(v);
if abs(out - v) > 1e-9
    error('%s must be an integer.', name);
end
end

function stats = local_field_stats(v)
if isempty(v)
    stats = struct('min', NaN, 'max', NaN, 'mean', NaN, 'std', NaN);
    return
end
stats = struct( ...
    'min', min(v(:)), ...
    'max', max(v(:)), ...
    'mean', mean(v(:)), ...
    'std', std(v(:)));
end
