function info = setup_vertical_project()
%SETUP_VERTICAL_PROJECT Add the project implementation to the MATLAB path.
%   This function is idempotent and does not change the current directory.

project_root = fileparts(mfilename('fullpath'));
relative_paths = { ...
    '', ...
    'src/channel', ...
    'src/propagation', ...
    'src/surface', ...
    'src/receiver', ...
    'src/statistics', ...
    'src/communication', ...
    'src/bubble', ...
    'examples', ...
    'scripts', ...
    'scripts/validation', ...
    'scripts/validation/support', ...
    'scripts/comparisons', ...
    'scripts/experiments', ...
    'scripts/reporting'};

absolute_paths = cell(size(relative_paths));
for ii = 1:numel(relative_paths)
    absolute_paths{ii} = fullfile(project_root, relative_paths{ii});
    if ~isfolder(absolute_paths{ii})
        error('setup_vertical_project:MissingDirectory', ...
            'Required project directory is missing: %s', absolute_paths{ii});
    end
end
addpath(absolute_paths{:});

if nargout > 0
    info = struct( ...
        'project_root', project_root, ...
        'paths_added', {absolute_paths}, ...
        'current_directory_unchanged', true);
end
end
