function atlas = generate_pe_propagation_atlas_vertical()
%GENERATE_PE_PROPAGATION_ATLAS_VERTICAL Build the validation-only PE visual atlas.
%   PE_ATLAS_MODE=smoke uses PE64/PM128/F9. The default full mode reuses the
%   accepted PE128/PM256/F64 cache and joint model. No public defaults change.

root_dir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(root_dir, fullfile(root_dir,'scripts'), ...
    fullfile(root_dir,'scripts','validation'), fullfile(root_dir,'scripts','reporting'));
mode = lower(strtrim(getenv('PE_ATLAS_MODE')));
if isempty(mode), mode = 'full'; end
if ~ismember(mode,{'smoke','full'})
    error('PE_ATLAS_MODE must be smoke or full.');
end
out_dir = project_result_dir('visualization','pe_propagation_atlas');
seed = 780001;

[cache,joint_model,pm_spec] = local_load_case(root_dir,mode);
[projection,projection_meta] = build_adjoint_receiver_projection_vertical(cache,pm_spec);
spatial_cfg = cache.cfg;
spatial_cfg.f_axis_hz = 6000;
spatial_cache = build_cached_joint_kstat_pe_executor_vertical(spatial_cfg,pm_spec);
[spatial_projection,spatial_projection_meta] = ...
    build_adjoint_receiver_projection_vertical(spatial_cache,pm_spec);

% Explicit raw-PM surface and joint-kstat realization on the same PM/PE map.
[eta_pm,eta_meta] = sample_raw_pm_surface_vertical(pm_spec,seed);
eta_pe = eta_pm(cache.pm_mapping.iy,cache.pm_mapping.ix);
[eta_joint_pm,eta_joint_meta] = sample_raw_pm_surface_vertical(pm_spec,seed+1);
[delta_joint_pm,joint_sample_meta] = sample_kirchhoff_kstat_factor_model_vertical( ...
    joint_model,1,seed+1,'joint');
F = numel(cache.f_axis_hz);
delta_explicit_pm = complex(zeros(pm_spec.ny,pm_spec.nx,F));
for ff = 1:F
    alpha = 4*pi*cache.f_axis_hz(ff)/cache.cfg.c0;
    delta_explicit_pm(:,:,ff) = cache.cfg.reflect_coeff.*exp(1i*alpha.*eta_pm) - ...
        cache.R_coh_f(ff);
end
[explicit_receiver,explicit_meta] = run_cached_joint_kstat_pe_executor_vertical( ...
    cache,delta_explicit_pm);
[joint_receiver,joint_meta] = run_cached_joint_kstat_pe_executor_vertical( ...
    cache,delta_joint_pm);
[joint_projection,joint_projection_meta] = run_adjoint_receiver_projection_vertical( ...
    projection,delta_joint_pm);

inc_ref = spatial_cache.incident_surface_xy_f(:,:,1);
alpha_ref = 4*pi*6000/spatial_cache.cfg.c0;
delta_joint_ref_pm = spatial_cache.cfg.reflect_coeff.*exp(1i*alpha_ref.*eta_joint_pm) - ...
    spatial_cache.R_coh_f(1);
delta_joint_ref = delta_joint_ref_pm(spatial_cache.pm_mapping.iy, ...
    spatial_cache.pm_mapping.ix);
spatial_joint_forward_xy = apply_forward_surface_to_receiver_vertical( ...
    spatial_cache,double(inc_ref.*delta_joint_ref),1);
spatial_joint_forward = spatial_joint_forward_xy(spatial_cache.iy_rx,spatial_cache.ix_rx);
spatial_joint_projected = sum(conj(spatial_projection.a_pe_xy_f(:,:,1)).* ...
    double(delta_joint_ref),'all');
surface = struct();
surface.eta_pm_m = eta_pm;
surface.eta_pe_m = eta_pe;
surface.incident_xy = inc_ref;
surface.flat_xy = spatial_cache.cfg.reflect_coeff.*inc_ref;
surface.coherent_xy = spatial_cache.R_coh_f(1).*inc_ref;
surface.explicit_xy = spatial_cache.cfg.reflect_coeff.*exp(1i*alpha_ref.*eta_pe).*inc_ref;
surface.explicit_scatter_xy = surface.explicit_xy-surface.coherent_xy;
surface.joint_scatter_xy = double(inc_ref.*delta_joint_ref);
surface.joint_xy = surface.coherent_xy+surface.joint_scatter_xy;

% A scalar public run supplies direct, incident, and reflected PE slices.
public_on = vertical_channel_model(local_public_params(cache,seed,true,'kirchhoff_kdomain'));
public_off = vertical_channel_model(local_public_params(cache,seed,false,'kirchhoff_kdomain'));
ssa = vertical_channel_model(local_public_params(cache,seed,true,'ssa1_geometry'));
surface.ssa1_xy = ssa.surface_wavefield_meta.surface_reflected_xy;

receiver = struct();
receiver.direct_xy = public_on.psifinal_xy;
receiver.flat_xy = apply_forward_surface_to_receiver_vertical(spatial_cache,double(surface.flat_xy),1);
receiver.coherent_xy = apply_forward_surface_to_receiver_vertical(spatial_cache,double(surface.coherent_xy),1);
receiver.explicit_scatter_xy = apply_forward_surface_to_receiver_vertical( ...
    spatial_cache,double(surface.explicit_scatter_xy),1);
receiver.explicit_xy = receiver.coherent_xy+receiver.explicit_scatter_xy;
receiver.joint_scatter_xy = apply_forward_surface_to_receiver_vertical( ...
    spatial_cache,double(surface.joint_scatter_xy),1);
receiver.joint_xy = receiver.coherent_xy+receiver.joint_scatter_xy;
receiver.total_joint_xy = receiver.direct_xy+receiver.joint_xy;
receiver.ssa1_xy = apply_forward_surface_to_receiver_vertical(spatial_cache,double(surface.ssa1_xy),1);

% Accepted second-order statistics, conditional models, and LFM diagnostics.
saved = local_load_saved_results(root_dir,mode);
[conditional_samples,conditional_sample_meta] = sample_conditional_channel_vertical( ...
    saved.model5,2000,seed+2,struct('path','auto','rank','full','return_total',true));

% Numerical closure checks.
checks = struct();
checks.public_diagnostics_H_relative_error = local_rel( ...
    public_on.H_f-public_off.H_f,public_off.H_f);
checks.incident_surface_endpoint_relative_error = local_rel( ...
    public_on.surface_wavefield_meta.incident_field_slice(:,end)- ...
    local_center_slice(public_on.surface_wavefield_meta.surface_incident_xy), ...
    local_center_slice(public_on.surface_wavefield_meta.surface_incident_xy));
checks.reflected_surface_endpoint_relative_error = local_rel( ...
    public_on.surface_wavefield_meta.reflected_field_slice(:,1)- ...
    local_center_slice(public_on.surface_wavefield_meta.surface_reflected_xy), ...
    local_center_slice(public_on.surface_wavefield_meta.surface_reflected_xy));
checks.surface_joint_component_relative_error = local_rel( ...
    surface.coherent_xy+surface.joint_scatter_xy-surface.joint_xy,surface.joint_xy);
checks.receiver_joint_component_relative_error = local_rel( ...
    receiver.coherent_xy+receiver.joint_scatter_xy-receiver.joint_xy,receiver.joint_xy);
checks.receiver_total_component_relative_error = local_rel( ...
    receiver.direct_xy+receiver.joint_xy-receiver.total_joint_xy,receiver.total_joint_xy);
checks.cached_adjoint_relative_error = local_rel( ...
    joint_receiver.H_ref_sca_fm-joint_projection.H_ref_sca_fm, ...
    joint_receiver.H_ref_sca_fm);
checks.receiver_sample_cached_adjoint_relative_error = local_rel( ...
    spatial_joint_forward-spatial_joint_projected,spatial_joint_forward);
checks.all_pass = checks.public_diagnostics_H_relative_error<=1e-12 && ...
    checks.incident_surface_endpoint_relative_error<=1e-10 && ...
    checks.reflected_surface_endpoint_relative_error<=1e-10 && ...
    checks.surface_joint_component_relative_error<=1e-12 && ...
    checks.receiver_joint_component_relative_error<=1e-12 && ...
    checks.receiver_total_component_relative_error<=1e-12 && ...
    checks.cached_adjoint_relative_error<=1e-10 && ...
    checks.receiver_sample_cached_adjoint_relative_error<=1e-10;
if ~checks.all_pass
    error('PE atlas numerical closure checks failed.');
end

atlas = struct();
atlas.kind = 'pe_propagation_visual_atlas_v1';
atlas.created_at = char(datetime('now','Format','yyyy-MM-dd HH:mm:ss'));
atlas.mode = mode;
atlas.scope = 'uniform CPU double; U=5; one nearest-grid receiver; no bubbles or Doppler';
atlas.cfg = cache.cfg;
atlas.pm = struct('nx',pm_spec.nx,'ny',pm_spec.ny,'dx_m',pm_spec.dx_m, ...
    'dy_m',pm_spec.dy_m,'sigma_eta2_m2',pm_spec.sigma_eta_discrete2_m2, ...
    'mapping',cache.pm_mapping);
atlas.seed = seed;
atlas.reference_frequency_hz = 6000;
atlas.reference_frequency_index = 1;
atlas.x_m = cache.x;
atlas.y_m = cache.y;
atlas.surface = surface;
atlas.receiver = receiver;
atlas.public = struct('x_m',public_on.x,'y_m',public_on.y,'z_track_m',public_on.z_track, ...
    'direct_xz',public_on.Axz,'wavefield_meta',public_on.surface_wavefield_meta, ...
    'H_direct_f',public_on.H_direct_f,'H_reflect_f',public_on.H_reflect_f, ...
    'H_total_f',public_on.H_f);
atlas.ssa = struct('surface_meta',ssa.surface_wavefield_meta, ...
    'H_reflect_f',ssa.H_reflect_f);
atlas.projection = struct('q_xy',spatial_projection.q_surface_xy_f(:,:,1), ...
    'a_xy',spatial_projection.a_pe_xy_f(:,:,1),'build_meta',projection_meta, ...
    'spatial_build_meta',spatial_projection_meta, ...
    'H_cached_scatter_f',joint_receiver.H_ref_sca_fm, ...
    'H_projected_scatter_f',joint_projection.H_ref_sca_fm, ...
    'H_ref_coh_f',cache.H_ref_coh_f, ...
    'H_explicit_reflect_f',explicit_receiver.H_ref_coh_f+explicit_receiver.H_ref_sca_fm, ...
    'H_joint_reflect_f',joint_receiver.H_ref_coh_f+joint_receiver.H_ref_sca_fm, ...
    'H_joint_total_f',joint_receiver.H_total_fm);
atlas.stats = saved.adjoint_stats;
atlas.model5 = local_model_summary(saved.model5,saved.validation5);
atlas.model8 = local_model_summary(saved.model8,saved.validation8);
atlas.distribution = struct('H_scatter_fm',conditional_samples.H_ref_sca_f, ...
    'sample_meta',conditional_sample_meta);
atlas.lfm_saved = saved.lfm;
atlas.metadata = struct('eta',eta_meta,'joint_eta',eta_joint_meta, ...
    'joint_sample',joint_sample_meta, ...
    'explicit_executor',explicit_meta,'joint_executor',joint_meta, ...
    'joint_projection',joint_projection_meta, ...
    'common_db_limits',[-50 0],'phase_mask_db',-40, ...
    'complex_envelope_note','PE fields are complex envelopes.', ...
    'carrier_note','Animation is nominal-c0 carrier reconstruction, not a time-domain PE solve.', ...
    'comparison_note','Explicit and joint single realizations are illustrative, not pointwise validation.');
atlas.checks = checks;

% Save the collected data before rendering so plot-only failures can be
% corrected without repeating PE propagation and accepted-result loading.
save(fullfile(out_dir,'pe_propagation_atlas_data.mat'),'atlas','-v7.3');
plot_pe_propagation_atlas_vertical(atlas,out_dir);
local_write_summary(atlas,out_dir);
local_write_manifest(atlas,out_dir);
local_validate_outputs(out_dir);
fprintf('PE propagation atlas (%s) saved to %s\n',mode,out_dir);
end

function [cache,model,spec] = local_load_case(root_dir,mode)
if strcmp(mode,'full')
    cache_file = fullfile(root_dir,'results','validation','u5_conditional_channel_f64', ...
        'f64_joint_pe_cache.mat');
    model_file = fullfile(root_dir,'results','validation','u5_conditional_channel_f64', ...
        'f64_joint_streaming_model_u5.mat');
    local_require({cache_file,model_file});
    a = load(cache_file,'cache'); b = load(model_file,'joint_model');
    cache = a.cache; model = b.joint_model;
    spec = raw_pm_spectrum_grid_vertical(5,256,256,100,100);
else
    f = (4000:500:8000).';
    cfg = struct('f_axis_hz',f,'c0',1500,'xw',25,'yw',25,'nx',64,'ny',64, ...
        'x_tx',0,'y_tx',0,'z_tx',100,'x_rx',0,'y_rx',0,'z_rx',3, ...
        'sigma_src_m',0.4,'stepz_lamb',0.5,'sponge_ratio',0.12, ...
        'alpha_max_np_per_m',0.15,'reflect_coeff',-1,'env_mode','uniform', ...
        'enable_bubbles',false);
    spec = raw_pm_spectrum_grid_vertical(5,128,128,50,50);
    cache = build_cached_joint_kstat_pe_executor_vertical(cfg,spec);
    model = build_kirchhoff_kstat_joint_model_streaming_vertical( ...
        spec,f,cfg.c0,cfg.reflect_coeff);
end
end

function params = local_public_params(cache,seed,diagnostics,model)
cfg = cache.cfg;
params = struct('f0',6000,'enable_wideband',false,'c0',cfg.c0, ...
    'z_max',cfg.z_tx,'z_tx',cfg.z_tx,'z_rx',cfg.z_rx,'xw',cfg.xw,'yw',cfg.yw, ...
    'nx',cfg.nx,'ny',cfg.ny,'x_tx',cfg.x_tx,'y_tx',cfg.y_tx, ...
    'x_rx',cfg.x_rx,'y_rx',cfg.y_rx,'sigma_src_m',cfg.sigma_src_m, ...
    'stepz_lamb',cfg.stepz_lamb,'sponge_ratio',cfg.sponge_ratio, ...
    'alpha_max_np_per_m',cfg.alpha_max_np_per_m,'env_mode','uniform', ...
    'enable_bubbles',false,'enable_surface_reflection',true, ...
    'surface_reflect_coeff',cfg.reflect_coeff,'surface_roughness_scale_mode','raw_pm', ...
    'sea_wind_speed',5,'sea_seed',seed,'show_figures',false, ...
    'enforce_1_over_R',false,'save_mode','slice','use_gpu',false, ...
    'surface_wavefield_diagnostics',diagnostics,'surface_wavefield_slice_axis','x', ...
    'surface_wavefield_max_z_samples',192);
if strcmp(model,'ssa1_geometry')
    params.surface_boundary_model = 'ssa_stat_kernel';
    params.surface_ssa_kernel_mode = 'ssa1_geometry';
    params.surface_ssa_random_scatter = true;
    params.surface_ssa_conv_padding = 'zero_padded';
    params.surface_ssa_geometry_source_id = ...
        'SSA.md; first-order pressure-release / Dirichlet geometry';
else
    params.surface_boundary_model = 'kirchhoff_kdomain';
end
end

function saved = local_load_saved_results(root_dir,mode)
files = struct( ...
    'adjoint',fullfile(root_dir,'results','validation','adjoint_pe_receiver_projection', ...
        'adjoint_pe_receiver_projection_full.mat'), ...
    'model5',fullfile(root_dir,'results','validation','u5_conditional_channel_f64', ...
        'u5_conditional_channel_model_f64_full.mat'), ...
    'model8',fullfile(root_dir,'results','validation','u8_conditional_channel_f64', ...
        'u8_conditional_channel_model_f64_full.mat'), ...
    'validation5',fullfile(root_dir,'results','validation','u5_conditional_channel_f64', ...
        'u5_conditional_channel_validation_f64_full.mat'), ...
    'validation8',fullfile(root_dir,'results','validation','u8_conditional_channel_f64', ...
        'u8_conditional_channel_validation_f64_full.mat'), ...
    'lfm',fullfile(root_dir,'results','validation', ...
        'validate_kstat_vs_kdomain_lfm_channel_vertical_result.mat'));
local_require(struct2cell(files));
a = load(files.adjoint,'validation');
if strcmp(mode,'full'), saved.adjoint_stats = a.validation.f64; ...
else, saved.adjoint_stats = a.validation.f9; end
b = load(files.model5,'model'); saved.model5 = b.model;
b = load(files.model8,'model'); saved.model8 = b.model;
b = load(files.validation5,'result'); saved.validation5 = b.result;
b = load(files.validation8,'result'); saved.validation8 = b.result;
b = load(files.lfm,'lfm','case_results'); saved.lfm = b;
end

function summary = local_model_summary(model,validation)
summary = struct('condition',model.condition,'frequency_axis',model.frequency_axis, ...
    'H_direct_f',model.H_direct_f,'H_ref_coh_f',model.H_ref_coh_f, ...
    'mu_scatter_f',model.stats.mu_scatter_f,'C_scatter_f',model.stats.C_scatter_f, ...
    'P_scatter_f',model.stats.P_scatter_f,'eigenvalues',model.stats.eigenvalues, ...
    'cumulative_variance',model.stats.cumulative_variance, ...
    'rank_candidates',model.stats.rank_candidates,'rank_selected',model.stats.rank_selected, ...
    'properness_ratio',model.stats.properness_ratio, ...
    'pdp',validation.receiver.joint_temporal.pdp, ...
    'delay_axis_s',validation.receiver.joint_temporal.delay_axis_s);
end

function slice = local_center_slice(field)
slice = field(floor(size(field,1)/2)+1,:).';
end

function value = local_rel(delta,reference)
value = norm(delta(:))/max(norm(reference(:)),eps);
end

function local_require(paths)
for ii = 1:numel(paths)
    if ~isfile(paths{ii})
        error('Required accepted result is missing: %s',paths{ii});
    end
end
end

function local_write_summary(atlas,out_dir)
path = fullfile(out_dir,'pe_propagation_atlas_summary.txt');
fid = fopen(path,'w'); cleanup = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'PE propagation visual atlas (%s)\n',atlas.mode);
fprintf(fid,'reference frequency %.0f Hz, PE %dx%d, PM %dx%d\n', ...
    atlas.reference_frequency_hz,atlas.cfg.nx,atlas.cfg.ny,atlas.pm.nx,atlas.pm.ny);
names = fieldnames(atlas.checks);
for ii = 1:numel(names)
    value = atlas.checks.(names{ii});
    if islogical(value), fprintf(fid,'%s %d\n',names{ii},value); ...
    else, fprintf(fid,'%s %.12g\n',names{ii},value); end
end
fprintf(fid,'Complex fields are PE envelopes. MP4 is carrier reconstruction, not time-domain PE.\n');
end

function local_write_manifest(atlas,out_dir)
path = fullfile(out_dir,'pe_propagation_atlas_manifest.md');
fid = fopen(path,'w'); cleanup = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'# PE Propagation Visual Atlas\n\n');
fprintf(fid,'Mode: `%s`; reference frequency: `%.0f Hz`; PE: `%d x %d`; PM: `%d x %d`.\n\n', ...
    atlas.mode,atlas.reference_frequency_hz,atlas.cfg.nx,atlas.cfg.ny,atlas.pm.nx,atlas.pm.ny);
fprintf(fid,'All spatial magnitude panels use a common `[-50,0] dB` envelope reference. ');
fprintf(fid,'Phase is masked below `-40 dB`. `z` is positive downward.\n\n');
items = { ...
    '01_geometry_and_paths.png','Geometry, directions, windows, sponge, transmitter and receiver.','Formal cache/configuration and public scalar diagnostic.'; ...
    '02_pe_xz_propagation.png','Direct, Tx-to-surface incident, and surface-to-Rx reflected PE slices.','Public `Axz/psifinal_xy/surface_wavefield_meta` at 6 kHz.'; ...
    '03_surface_boundary_fields.png','Raw-PM elevation and incident/coherent/reflected/scatter surface fields.','Cached incidence, explicit raw-PM surface, and one joint-kstat realization.'; ...
    '04_surface_angular_spectra.png','Incident/reflected/scatter angular spectra on a shared scale.','Unshifted stored fields; spectra derived with centered `fft2` only for display.'; ...
    '05_physical_boundary_branches.png','Flat, explicit Kirchhoff, joint-kstat, and SSA1 illustrative fields.','Same incident field where defined; SSA1 public scalar reference.'; ...
    '06_receiver_plane_components.png','Direct/coherent/scatter/reflected/total receiver-depth planes.','Shared cached surface-to-receiver forward primitive.'; ...
    '07_receiver_transverse_profiles.png','Receiver-centred x/y profiles.','Cuts through the same receiver planes and nearest-grid sample.'; ...
    '08_cached_vs_adjoint.png','Same-input cached PE and exact adjoint projection plus sensitivity kernels.','Cached executor and `q=A^H r`, `a=conj(psi_inc).*q`.'; ...
    '09_receiver_frequency_response.png','Reflected-only response and group delay.','Same explicit/joint samples plus accepted analytic scatter RMS.'; ...
    '10_receiver_cp_heatmaps.png','Analytic/sample covariance and pseudo-covariance.','Accepted adjoint F=64 validation; common absolute `|C|` reference.'; ...
    '11_pdp_eigenspectrum_distribution.png','PDP, covariance modes, IQ and amplitude distribution.','Accepted analytic/projected PDP and deterministic conditional U=5 samples.'; ...
    '12_u5_u8_statistical_contrast.png','Validated U=5/U=8 receiver statistics; no wind interpolation.','Saved full conditional models and validation results.'; ...
    '13_lfm_and_matched_filter.png','Noiseless channel-level LFM and matched-filter diagnostics.','Prior public LFM validation plus current accepted joint analytic/sample statistics.'; ...
    '14_pe_carrier_reconstruction.mp4','Nominal-c0 carrier reconstruction; not time-domain PE.','Stored complex-envelope center slices multiplied by carrier phase.'};
fprintf(fid,'| File | Meaning | Data source / normalization |\n|---|---|---|\n');
for ii = 1:size(items,1), fprintf(fid,'| `%s` | %s | %s |\n',items{ii,1},items{ii,2},items{ii,3}); end
fprintf(fid,'\nExplicit and joint single realizations are illustrative and are not compared pointwise. ');
fprintf(fid,'The adjoint kernel is receiver sensitivity, not reciprocal or inverse propagation. ');
fprintf(fid,'Analytic FFT C/P and conditional models are receiver-statistics paths, not spatial-field generators. ');
fprintf(fid,'Total-channel panels are contextual; validation metrics remain reflected-scatter based.\n');
end

function local_validate_outputs(out_dir)
files = [arrayfun(@(ii)sprintf('%02d_',ii),1:13,'UniformOutput',false),{'14_'}];
listing = dir(out_dir);
for ii = 1:numel(files)
    hit = startsWith({listing.name},files{ii});
    if ~any(hit), error('Missing atlas output with prefix %s.',files{ii}); end
    sizes = [listing(hit).bytes];
    if isempty(sizes) || max(sizes)<1024, error('Atlas output %s is unexpectedly small.',files{ii}); end
end
end
