%% U=8 raw-PM aperture convergence and center-crop audit
clear; close all; clc;
root=fileparts(fileparts(fileparts(mfilename('fullpath')))); addpath(root); setup_vertical_project();
folder=fullfile(root,'results','validation','u8_conditional_channel_f64');
if ~exist(folder,'dir'), mkdir(folder); end
U=8; aperture=[100,150,200]; grid=[256,384,512]; seeds=2300001+(0:127); pe_n=128; dx=50/128;
rows=struct([]); samples=cell(numel(aperture),1); total_timer=tic;
for kk=1:numel(aperture)
    timer=tic; spec=raw_pm_spectrum_grid_vertical(U,grid(kk),grid(kk),aperture(kk),aperture(kk));
    full=zeros(numel(seeds),1); crop=full; demean=full; local_mean=full;
    slope_x_mean=full; slope_y_mean=full; slope_x_rms=full; slope_y_rms=full;
    i0=floor((grid(kk)-pe_n)/2)+1; ind=i0:(i0+pe_n-1);
    for mm=1:numel(seeds)
        eta=sample_raw_pm_surface_vertical(spec,seeds(mm)); eta_pe=eta(ind,ind);
        full(mm)=mean(eta(:).^2); crop(mm)=mean(eta_pe(:).^2); demean(mm)=var(eta_pe(:),1);
        local_mean(mm)=mean(eta_pe(:));
        [gx,gy]=gradient(eta_pe,dx,dx); slope_x_mean(mm)=mean(gx(:)); slope_y_mean(mm)=mean(gy(:));
        slope_x_rms(mm)=sqrt(mean(gx(:).^2)); slope_y_rms(mm)=sqrt(mean(gy(:).^2));
    end
    ratio=crop./full; ratio_demean=demean./full; hw=1.96*std(ratio)/sqrt(numel(ratio));
    row=struct('U_mps',U,'aperture_m',aperture(kk),'grid_n',grid(kk), ...
        'K_min_rad_per_m',spec.K_min_rad_per_m,'K_peak_rad_per_m',spec.K_peak_rad_per_m, ...
        'K_nyquist_rad_per_m',spec.K_nyquist_axis_rad_per_m, ...
        'K_peak_over_K_min',spec.K_peak_rad_per_m/spec.K_min_rad_per_m, ...
        'sigma_discrete2_m2',spec.sigma_eta_discrete2_m2, ...
        'sigma_infinite2_m2',spec.sigma_eta_infinite2_m2, ...
        'Hs_implied_m',spec.Hs_implied_discrete_m, ...
        'capture_ratio',spec.capture_ratio_discrete_to_infinite, ...
        'radial_capture_ratio',spec.capture_ratio_radial_support_idealized, ...
        'crop_energy_ratio_mean',mean(ratio),'crop_energy_ratio_std',std(ratio), ...
        'crop_energy_ratio_ci95_low',mean(ratio)-hw,'crop_energy_ratio_ci95_high',mean(ratio)+hw, ...
        'demeaned_energy_ratio_mean',mean(ratio_demean), ...
        'demeaning_loss_fraction',mean((crop-demean)./max(crop,eps)), ...
        'local_mean_height_mean_m',mean(local_mean),'local_mean_height_std_m',std(local_mean), ...
        'slope_x_mean',mean(slope_x_mean),'slope_y_mean',mean(slope_y_mean), ...
        'slope_x_rms_mean',mean(slope_x_rms),'slope_y_rms_mean',mean(slope_y_rms), ...
        'audit_wall_s',toc(timer));
    if isempty(rows), rows=row; else, rows(end+1)=row; end %#ok<SAGROW>
    samples{kk}=struct('full_energy',full,'crop_energy',crop,'demeaned_energy',demean, ...
        'local_mean_height',local_mean,'slope_x_rms',slope_x_rms,'slope_y_rms',slope_y_rms); %#ok<SAGROW>
end
T=struct2table(rows); hs=T.Hs_implied_m; convergence=[NaN;abs(diff(hs))./hs(2:end)]; T.Hs_change_from_previous=convergence;
eligible=T.capture_ratio>=.98 & T.K_peak_over_K_min>=2 & ([false;convergence(2:end)<.02]);
idx=find(eligible,1,'first'); if isempty(idx), idx=height(T); end
result=struct();
result.table=T;
result.samples=samples;
result.seed_list=seeds;
result.selected_row=T(idx,:);
result.selection_rule='capture>=0.98, Kpeak/Kmin>=2, Hs change from previous aperture<2%';
result.total_wall_s=toc(total_timer);
save(fullfile(folder,'u8_raw_pm_aperture_audit.mat'),'result','-v7.3');
writetable(T,fullfile(folder,'u8_raw_pm_aperture_audit.csv'));
disp(T); fprintf('Selected %.0f m / %d^2; capture %.6f Hs %.6f m crop %.6f CI [%.6f %.6f]\n', ...
    T.aperture_m(idx),T.grid_n(idx),T.capture_ratio(idx),T.Hs_implied_m(idx), ...
    T.crop_energy_ratio_mean(idx),T.crop_energy_ratio_ci95_low(idx),T.crop_energy_ratio_ci95_high(idx));
