%% PE carrier-phase reference and migration validation
clear; close all; clc;
root_dir=fileparts(fileparts(fileparts(mfilename('fullpath')))); addpath(root_dir); setup_vertical_project();
out_dir=fullfile(root_dir,'results','validation','pe_channel_phase_reference');
if ~exist(out_dir,'dir'), mkdir(out_dir); end
validation_run_meta=pe_phase_release_run_meta_vertical(root_dir,struct( ...
    'frequency_axis_hz',(4000:62.5:8000).','seed_definition', ...
    struct('phase_random_field',810001,'migration_sample',810002)));
result=struct('created_at',char(datetime('now')), ...
    'physical_time_convention','exp(-1i*omega*t)', ...
    'public_default_reference','direct_dsp');

%% Analytic phase and delay checks: F=65 is required for the 4 ms audit.
f65=(4000:62.5:8000).';
geometry=struct('z_tx',100,'z_rx',3,'z_surface',0,'c0',1500);
reduced=struct('direct_f',ones(size(f65)),'reflect_fm',0.5*ones(size(f65)));
[dsp,phase_meta]=apply_pe_channel_phase_reference_vertical( ...
    f65,reduced,geometry,'direct_dsp');
[physical,physical_meta]=apply_pe_channel_phase_reference_vertical( ...
    f65,reduced,geometry,'absolute_physical');
direct_cir=build_channel_cir_vertical(dsp.direct_f,f65, ...
    struct('input_reference','direct_dsp','zero_padding_factor',16));
reflect_cir=build_channel_cir_vertical(dsp.reflect_fm,f65, ...
    struct('input_reference','direct_dsp','zero_padding_factor',16));
[~,id]=max(abs(direct_cir.h_tau)); [~,ir]=max(abs(reflect_cir.h_tau));
direct_delay=direct_cir.delay_axis_s(id); reflect_delay=reflect_cir.delay_axis_s(ir);
delay_error=abs((reflect_delay-direct_delay)-phase_meta.relative_delay_s);
f9=(4000:500:8000).';
[~,phase9]=apply_pe_channel_phase_reference_vertical(f9, ...
    struct('direct_f',ones(size(f9)),'reflect_fm',ones(size(f9))),geometry,'direct_dsp');
result.analytic=struct('phase_meta',phase_meta,'physical_meta',physical_meta, ...
    'direct_delay_s',direct_delay,'reflect_delay_s',reflect_delay, ...
    'relative_delay_error_s',delay_error, ...
    'magnitude_error',max(abs(abs(dsp.reflect_fm)-abs(reduced.reflect_fm))), ...
    'direct_dsp_roundtrip_error',local_rel(reduced.reflect_fm, ...
        dsp.reflect_fm./phase_meta.reflect_dsp_factor_f), ...
    'physical_roundtrip_error',local_rel(reduced.reflect_fm, ...
        physical.reflect_fm./physical_meta.reflect_physical_factor_f), ...
    'f9_alias_factor_error_from_unity',max(abs(phase9.reflect_dsp_factor_f-1)), ...
    'f65_unambiguous_delay_s',direct_cir.maximum_unambiguous_delay_s);

%% Public surface branches and legacy-reduced regression.
base=local_public_params([4000 6000 8000]);
models={'kirchhoff_spatial','kirchhoff_kdomain','ssa_stat_kernel','kirchhoff_kstat'};
public=cell(numel(models),1);
for ii=1:numel(models)
    p=base; p.surface_boundary_model=models{ii};
    p.surface_ssa_random_scatter=false; p.surface_kstat_random_scatter=false;
    out=vertical_channel_model(p);
    expected=out.phase_reference_meta.reflect_dsp_factor_f.*out.H_reflect_reduced_f;
    public{ii}=struct('model',models{ii}, ...
        'phase_error',max(abs(out.H_reflect_f-expected)), ...
        'component_error',max(abs(out.H_f-out.H_direct_f-out.H_reflect_f)), ...
        'physical_component_error',max(abs(out.H_physical_f- ...
        out.H_direct_physical_f-out.H_reflect_physical_f)), ...
        'magnitude_error',max(abs(abs(out.H_reflect_f)-abs(out.H_reflect_reduced_f))));
end
public=vertcat(public{:});
p=base; p.surface_boundary_model='kirchhoff_spatial'; p.channel_phase_reference='legacy_reduced';
legacy=vertical_channel_model(p);
p.channel_phase_reference='direct_dsp'; current=vertical_channel_model(p);
result.public=struct('branches',public, ...
    'legacy_reproduction_error',max(abs(legacy.H_f-current.H_total_reduced_f)));
p=local_public_params(6000); p.enable_surface_reflection=false;
direct_only=vertical_channel_model(p);
result.public.direct_only_component_error=max(abs(direct_only.H_f-direct_only.H_direct_f));

%% Cached, adjoint, and dense/FFT statistics on the approved fixed path.
f3=[4000;6000;8000];
cfg=local_cached_cfg(f3,8,3.125); pm=raw_pm_spectrum_grid_vertical(5,16,16,6.25,6.25);
cache=build_cached_joint_kstat_pe_executor_vertical(cfg,pm);
[projection,~]=build_adjoint_receiver_projection_vertical(cache,pm);
rng(810001,'twister'); delta=complex(randn(16,16,3,3),randn(16,16,3,3));
forward=run_cached_joint_kstat_pe_executor_vertical(cache,delta);
projected=run_adjoint_receiver_projection_vertical(projection,delta);
dense=contract_kstat_receiver_stats_vertical(pm,projection,struct('method','dense'));
fft_stats=contract_kstat_receiver_stats_vertical(pm,projection,struct('method','fft'));
d=dense.phase_reference_meta.reflect_dsp_factor_f;
result.research=struct( ...
    'forward_projection_reduced_error',local_rel( ...
    forward.H_ref_sca_reduced_fm,projected.H_ref_sca_reduced_fm), ...
    'forward_projection_dsp_error',local_rel(forward.H_ref_sca_fm,projected.H_ref_sca_fm), ...
    'dense_fft_C_error',local_rel(dense.C_H,fft_stats.C_H), ...
    'dense_fft_P_error',local_rel(dense.P_H,fft_stats.P_H), ...
    'C_rotation_error',local_rel(dense.C_H,d.*dense.C_H_reduced.*conj(d.')), ...
    'P_rotation_error',local_rel(dense.P_H,d.*dense.P_H_reduced.*d.'));

%% Schema-1 conditional-model migration, including augmented statistics.
rng(810002,'twister'); Hred=randn(64,80)+1i*0.3*randn(64,80);
legacy_options=struct('frequency_axis_hz',f65(1:64), ...
    'H_direct_f',ones(64,1),'H_ref_coh_f',0.2*ones(64,1), ...
    'condition',struct('wind_speed_mps',5));
legacy_model=estimate_conditional_channel_stats_vertical(Hred,legacy_options);
legacy_model.schema_version='1.0.0';
legacy_model=rmfield(legacy_model,{'phase_reference_meta','nominal_reflection_delay_s'});
[upgraded,migration]=upgrade_conditional_channel_phase_vertical(legacy_model,geometry);
fm=legacy_model.frequency_axis;
[deterministic,migration_phase]=apply_pe_channel_phase_reference_vertical(fm, ...
    struct('direct_f',legacy_model.H_direct_f,'reflect_coh_f',legacy_model.H_ref_coh_f), ...
    geometry,'direct_dsp');
dm=migration_phase.reflect_dsp_factor_f;
reference_options=legacy_options; reference_options.H_direct_f=deterministic.direct_f;
reference_options.H_ref_coh_f=deterministic.reflect_coh_f;
reference_options.phase_reference_meta=migration_phase;
reference=estimate_conditional_channel_stats_vertical(dm.*Hred,reference_options);
result.migration=struct('meta',migration, ...
    'mean_error',local_rel(upgraded.stats.mu_scatter_f,dm.*legacy_model.stats.mu_scatter_f), ...
    'C_error',local_rel(upgraded.stats.C_scatter_f,reference.stats.C_scatter_f), ...
    'P_error',local_rel(upgraded.stats.P_scatter_f,reference.stats.P_scatter_f), ...
    'eigenvector_error',local_rel(upgraded.stats.eigenvectors,dm.*legacy_model.stats.eigenvectors), ...
    'augmented_mean_error',local_rel(upgraded.stats.augmented_mean, ...
    [diag(real(dm)),-diag(imag(dm));diag(imag(dm)),diag(real(dm))]*legacy_model.stats.augmented_mean), ...
    'augmented_error',local_rel(upgraded.stats.augmented_covariance, ...
    reference.stats.augmented_covariance), ...
    'augmented_eigenvector_error',local_rel(upgraded.stats.augmented_eigenvectors, ...
    [diag(real(dm)),-diag(imag(dm));diag(imag(dm)),diag(real(dm))]*legacy_model.stats.augmented_eigenvectors));

%% External H without project metadata remains DSP-ready.
[~,tap_meta]=build_communication_taps_vertical( ...
    struct('H_f',dsp.total_fm,'f_axis_hz',f65), ...
    struct('symbol_rate_hz',1000,'n_fft',256,'f_ref_hz',6000));
legacy_rejected=local_rejected(@()build_communication_taps_vertical( ...
    struct('H_f',dsp.total_fm,'f_axis_hz',f65, ...
    'phase_reference_meta',struct('target_reference','legacy_reduced')), ...
    struct('symbol_rate_hz',1000,'n_fft',256,'f_ref_hz',6000)), ...
    'build_communication_taps_vertical:LegacyReducedInput');
physical_rejected=local_rejected(@()build_communication_taps_vertical( ...
    struct('H_f',physical.total_fm,'f_axis_hz',f65, ...
    'phase_reference_meta',struct('target_reference','absolute_physical')), ...
    struct('symbol_rate_hz',1000,'n_fft',256,'f_ref_hz',6000)), ...
    'build_communication_taps_vertical:PhysicalInput');
cir_legacy_rejected=local_rejected(@()build_channel_cir_vertical( ...
    dsp.total_fm,f65,struct('input_reference','legacy_reduced')), ...
    'build_channel_cir_vertical:UnalignedReducedInput');
result.communication=struct('phase_reference',tap_meta.phase_reference, ...
    'phase_reference_source',tap_meta.phase_reference_source, ...
    'ifft_closure_error',tap_meta.frequency_ifft_closure_relative_error, ...
    'legacy_rejected',legacy_rejected, ...
    'physical_rejected',physical_rejected, ...
    'cir_legacy_rejected',cir_legacy_rejected);

tol=1e-10;
result.pass=struct( ...
    'analytic_delay',delay_error<=direct_cir.delay_axis_spacing_s, ...
    'analytic_magnitude',result.analytic.magnitude_error<=1e-12, ...
    'phase_roundtrip',max([result.analytic.direct_dsp_roundtrip_error, ...
        result.analytic.physical_roundtrip_error])<=1e-12, ...
    'public_branches',max([[public.phase_error],[public.component_error], ...
        [public.physical_component_error],[public.magnitude_error]])<=1e-12, ...
    'legacy',result.public.legacy_reproduction_error<=1e-12, ...
    'direct_only',result.public.direct_only_component_error<=1e-12, ...
    'cached_adjoint',max([result.research.forward_projection_reduced_error, ...
        result.research.forward_projection_dsp_error])<=tol, ...
    'dense_fft',max([result.research.dense_fft_C_error,result.research.dense_fft_P_error])<=tol, ...
    'statistics_rotation',max([result.research.C_rotation_error,result.research.P_rotation_error])<=1e-12, ...
    'migration',max([result.migration.mean_error,result.migration.C_error, ...
        result.migration.P_error,result.migration.eigenvector_error, ...
        result.migration.augmented_mean_error,result.migration.augmented_error, ...
        result.migration.augmented_eigenvector_error])<=1e-12, ...
    'communication_phase_policy',strcmp(tap_meta.phase_reference,'external_dsp_assumed') && ...
        legacy_rejected && physical_rejected && cir_legacy_rejected);
result.pass.all=all(structfun(@logical,result.pass));
result.schema_version='2.0.0';
result.phase_reference_meta=phase_meta;
result.validation_run_meta=validation_run_meta;
schema_version=result.schema_version;
phase_reference_meta=result.phase_reference_meta;
save(fullfile(out_dir,'pe_channel_phase_reference_validation.mat'),'result', ...
    'schema_version','phase_reference_meta','validation_run_meta');
local_write_summary(result,fullfile(out_dir,'pe_channel_phase_reference_summary.txt'));
if ~result.pass.all, error('PE channel phase-reference validation failed.'); end
fprintf('PE channel phase-reference validation passed. Outputs: %s\n',out_dir);

function p=local_public_params(f)
p=struct('f0',f,'enable_wideband',false,'c0',1500,'z_max',10, ...
    'z_tx',10,'z_rx',1,'xw',25,'yw',25,'nx',64,'ny',64, ...
    'sigma_src_m',0.4,'stepz_lamb',1,'enable_surface_reflection',true, ...
    'sea_hs_target',0,'show_figures',false,'enforce_1_over_R',false, ...
    'save_mode','rx_only','use_gpu',false);
end

function cfg=local_cached_cfg(f,n,w)
cfg=struct('f_axis_hz',f(:),'c0',1500,'xw',w,'yw',w,'nx',n,'ny',n, ...
    'x_tx',0,'y_tx',0,'z_tx',10,'x_rx',0,'y_rx',0,'z_rx',1, ...
    'sigma_src_m',0.4,'stepz_lamb',1,'sponge_ratio',0.12, ...
    'alpha_max_np_per_m',0.15,'reflect_coeff',-1, ...
    'env_mode','uniform','enable_bubbles',false);
end

function e=local_rel(a,b)
e=norm(a-b,'fro')/max(norm(a,'fro'),eps);
end

function rejected=local_rejected(action,expected_identifier)
rejected=false;
try
    action();
catch exception
    rejected=strcmp(exception.identifier,expected_identifier);
end
end

function local_write_summary(r,path)
fid=fopen(path,'w'); cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'PE channel phase-reference validation\n');
fprintf(fid,'created_at: %s\n',r.created_at);
fprintf(fid,'nominal_relative_delay_ms: %.12g\n',1e3*r.analytic.phase_meta.relative_delay_s);
fprintf(fid,'measured_relative_delay_ms: %.12g\n',1e3*(r.analytic.reflect_delay_s-r.analytic.direct_delay_s));
fprintf(fid,'cached_adjoint_dsp_error: %.6g\n',r.research.forward_projection_dsp_error);
fprintf(fid,'dense_fft_C_error: %.6g\n',r.research.dense_fft_C_error);
fprintf(fid,'dense_fft_P_error: %.6g\n',r.research.dense_fft_P_error);
fprintf(fid,'migration_C_error: %.6g\n',r.migration.C_error);
fprintf(fid,'migration_P_error: %.6g\n',r.migration.P_error);
fprintf(fid,'phase_roundtrip_pass: %d\n',r.pass.phase_roundtrip);
fprintf(fid,'communication_phase_policy_pass: %d\n',r.pass.communication_phase_policy);
fprintf(fid,'all_pass: %d\n',r.pass.all);
end
