function checks = validate_reflected_chain_diagnostics_regression_vertical(overrides)
%VALIDATE_REFLECTED_CHAIN_DIAGNOSTICS_REGRESSION_VERTICAL Reduced interface checks.
if nargin<1, overrides=struct(); end
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
run(fullfile(root,'scripts','bootstrap_project.m'));
cfg=struct('n',64,'width_m',16,'z_tx_m',20,'z_rx_m',2,'frequency_hz',4000, ...
    'hs_m',0.2,'seed',12345,'tolerance',1e-10);
n=fieldnames(overrides); for ii=1:numel(n),cfg.(n{ii})=overrides.(n{ii});end
p=local_params(cfg,false,[]); seeded=vertical_channel_model(p);
p.surface_elevation_override_xy=seeded.surface_elevation; overridden=vertical_channel_model(p);
p.surface_wavefield_diagnostics=true; diagnosed=vertical_channel_model(p);
m=diagnosed.surface_wavefield_meta;
checks=struct( ...
    'override_surface_max_abs',max(abs(overridden.surface_elevation(:)-seeded.surface_elevation(:))), ...
    'override_H_max_abs',max(abs(overridden.H_f-seeded.H_f)), ...
    'diagnostics_H_max_abs',max(abs(diagnosed.H_f-overridden.H_f)), ...
    'endpoint_max_abs',max(struct2array(m.endpoint_consistency)), ...
    'receiver_center_max_abs',abs(m.receiver_reflected_xy(diagnosed.rx_state_used.iy_rx,diagnosed.rx_state_used.ix_rx)-diagnosed.H_reflect_reduced_f(diagnosed.idx_f_ref)), ...
    'closure_max_abs',max(abs(diagnosed.H_f-diagnosed.H_direct_f-diagnosed.H_reflect_f)), ...
    'override_meta_enabled',diagnosed.roughness_meta.surface_realization_overridden, ...
    'energy_traces_enabled',m.incident_energy_trace.enabled && m.reflected_energy_trace.enabled);
numeric=struct2array(rmfield(checks,{'override_meta_enabled','energy_traces_enabled'}));
checks.all_passed=all(numeric<=cfg.tolerance) && checks.override_meta_enabled && checks.energy_traces_enabled;
if ~checks.all_passed, error('Reflected-chain diagnostics regression failed.'); end
end

function p=local_params(c,diag,eta)
p=struct('f0',c.frequency_hz,'z_max',c.z_tx_m,'z_tx',c.z_tx_m,'z_rx',c.z_rx_m, ...
    'xw',c.width_m,'yw',c.width_m,'nx',c.n,'ny',c.n,'show_figures',false, ...
    'enforce_1_over_R',false,'save_mode','rx_only','surface_boundary_model','kirchhoff_spatial', ...
    'surface_wavefield_diagnostics',diag,'surface_wavefield_max_z_samples',9, ...
    'validation_allow_extended_sponge_ratio',true,'sponge_ratio',0,'alpha_max_np_per_m',0, ...
    'sea_hs_target',c.hs_m,'sea_seed',c.seed);
if ~isempty(eta),p.surface_elevation_override_xy=eta;end
end
