function validation = validate_pe_bellhop_flat_surface_current_vertical(overrides)
%VALIDATE_PE_BELLHOP_FLAT_SURFACE_CURRENT_VERTICAL Current-version closure.
% Validation only: public PE marching, defaults, and communication are not changed.

if nargin<1 || isempty(overrides), overrides=struct(); end
this_file=mfilename('fullpath');
project_root=fileparts(fileparts(fileparts(this_file)));
addpath(project_root); setup_vertical_project();
addpath(fullfile(project_root,'scripts','reporting'));
cfg=local_defaults(); cfg=local_overrides(cfg,overrides); local_validate_cfg(cfg);

meta=pe_bellhop_current_run_meta_vertical(project_root,struct( ...
    'run_id',cfg.run_id,'bellhop_exe',cfg.bellhop_exe));
cfg.bellhop_exe=meta.bellhop_executable;
out_dir=meta.validation_output_dir; visual_dir=meta.visualization_output_dir;
phase_dir=fullfile(out_dir,'phase_audit');
fprintf('PE/Bellhop current validation: %s\n',meta.run_id);
fprintf('Bellhop: %s\n',cfg.bellhop_exe);

phase_audit=validate_pe_phase_convention_uniform_vertical(struct( ...
    'output_dir',phase_dir,'validation_run_meta',meta, ...
    'frequency_band_hz',cfg.frequency_band_hz, ...
    'frequency_count',cfg.phase_frequency_count, ...
    'f_ref_hz',cfg.f_ref_hz,'receiver_offsets_m',cfg.baseline_offsets_m));

f_axis_hz=linspace(cfg.frequency_band_hz(1),cfg.frequency_band_hz(2), ...
    cfg.frequency_count).';
[baseline_cases,path_table,closure]=local_baseline_cases(cfg,f_axis_hz,out_dir);
[path_table,amplitude_metrics]=local_amplitude_metrics(path_table,cfg);
small_offset=local_small_offset_cases(cfg,f_axis_hz,out_dir,baseline_cases);
source_audit=local_source_audit(cfg,baseline_cases,small_offset);
window_audit=local_window_sponge_audit(cfg,f_axis_hz);
public_regression=local_public_regression(cfg,f_axis_hz);

matrix_validation=local_matrix_compatibility(cfg,baseline_cases,path_table, ...
    phase_audit,meta,closure,window_audit,public_regression);
matrix_file=fullfile(out_dir,'pe_bellhop_current_matrix.mat');
validation_run_meta=meta; schema_version='1.0.0';
phase_reference_meta=baseline_cases(1).pe.phase_reference_meta;
validation=struct('schema_version',schema_version,'validation_run_meta',meta, ...
    'phase_reference_meta',phase_reference_meta,'config',cfg, ...
    'phase_audit',phase_audit,'baseline_cases',baseline_cases, ...
    'path_table',path_table,'closure',closure, ...
    'amplitude_metrics',amplitude_metrics,'small_offset',small_offset, ...
    'source_audit',source_audit,'window_audit',window_audit, ...
    'public_regression',public_regression,'matrix_validation',matrix_validation);
save(matrix_file,'validation','matrix_validation','schema_version', ...
    'phase_reference_meta','validation_run_meta','-v7.3');

field_dir=fullfile(visual_dir,'bellhop_fields_raw');
field_output=generate_bellhop_flat_surface_visuals_vertical(struct( ...
    'source_validation_mat',matrix_file,'output_dir',field_dir, ...
    'bellhop_exe',cfg.bellhop_exe,'show_figures',false));
validation.field_output=field_output;
validation=local_finalize(validation,cfg);

path_csv=fullfile(out_dir,'baseline_path_comparison.csv');
small_csv=fullfile(out_dir,'small_offset_comparison.csv');
source_csv=fullfile(out_dir,'source_directivity_audit.csv');
window_csv=fullfile(out_dir,'window_sponge_audit.csv');
checks_csv=fullfile(out_dir,'layered_acceptance_checks.csv');
writetable(validation.path_table,path_csv);
writetable(validation.small_offset.table,small_csv);
writetable(validation.source_audit.table,source_csv);
writetable(validation.window_audit.table,window_csv);
writetable(validation.checks,checks_csv);
validation.files=struct('mat',fullfile(out_dir,'pe_bellhop_current_validation.mat'), ...
    'path_csv',path_csv,'small_offset_csv',small_csv,'source_csv',source_csv, ...
    'window_csv',window_csv,'checks_csv',checks_csv,'matrix_mat',matrix_file);
save(validation.files.mat,'validation','schema_version','phase_reference_meta', ...
    'validation_run_meta','-v7.3');

atlas=generate_pe_bellhop_comparison_atlas_vertical(validation.files.mat);
validation.atlas=atlas;
validation.files.report=fullfile(project_root,'reports', ...
    'pe_bellhop_flat_surface_current_validation_report.md');
validation.files.summary=fullfile(out_dir,'pe_bellhop_current_summary.txt');
local_write_summary(validation.files.summary,validation);
local_write_report(validation.files.report,validation);
save(validation.files.mat,'validation','schema_version','phase_reference_meta', ...
    'validation_run_meta','-v7.3');
fprintf('PE/Bellhop current decision: %s; amplitude %s\n', ...
    validation.decision,validation.amplitude_status);
end

function cfg=local_defaults()
cfg=struct('run_id','','bellhop_exe',getenv('BELLHOP_EXE'), ...
    'water_depth_m',100,'c0_mps',1500,'z_tx_m',80,'z_rx_m',10, ...
    'f_ref_hz',4000,'frequency_band_hz',[3000 5000], ...
    'frequency_count',33,'phase_frequency_count',65, ...
    'baseline_offsets_m',[3 6 9],'small_offsets_m',[0 0.25 0.5 1 3], ...
    'nx',128,'ny',128,'width_m',32,'stepz_lamb',0.5, ...
    'sigma_src_m',0.3,'sponge_ratio',0.12,'alpha_max_np_per_m',0.15, ...
    'beam_count',10001,'small_offset_beam_count',20001, ...
    'angle_limits_deg',[-89.95 -60], ...
    'arrival_cluster_tolerance_ms',0.1,'zero_padding_factor',8, ...
    'time_tolerance_ms',0.25,'phase_tolerance_rad',0.15, ...
    'tl_tolerance_db',0.5,'closure_tolerance',1e-12, ...
    'amplitude_scale_spread_db',1,'amplitude_rms_db',1, ...
    'amplitude_max_db',2,'edge_level_limit_db',-40);
end

function cfg=local_overrides(cfg,over)
if ~isstruct(over), error('overrides must be a struct.'); end
names=fieldnames(over);
for ii=1:numel(names)
    if ~isfield(cfg,names{ii}), error('Unknown override: %s',names{ii}); end
    cfg.(names{ii})=over.(names{ii});
end
end

function local_validate_cfg(cfg)
if isempty(cfg.bellhop_exe), error('Set BELLHOP_EXE before the formal run.'); end
if cfg.z_rx_m<0 || cfg.z_rx_m>=cfg.z_tx_m, error('Require 0 <= z_rx < z_tx.'); end
if mod(cfg.frequency_count,2)~=1 || mod(cfg.phase_frequency_count,2)~=1
    error('Frequency counts must be odd.');
end
end

function [cases,table_out,closure]=local_baseline_cases(cfg,f,out_dir)
offsets=cfg.baseline_offsets_m(:);
case_template=struct('geometry',[],'pe',[],'bellhop',[], ...
    'direct_cir',[],'reflection_cir',[],'pe_total_cir',[], ...
    'bellhop_total_cir',[]);
cases=repmat(case_template,numel(offsets),1);
rows=repmat(local_path_row(),2*numel(offsets),1);
physical_errors=zeros(numel(offsets),1); dsp_errors=physical_errors; sum_errors=physical_errors;
for ii=1:numel(offsets)
    x=offsets(ii); fprintf('Baseline x = %.3f m\n',x);
    pe=vertical_channel_model(local_pe_params(cfg,f.',x,struct()));
    bell_cfg=local_bellhop_cfg(cfg,x,fullfile(out_dir, ...
        ['baseline_' local_offset_token(x)]),cfg.beam_count);
    bh=run_bellhop_flat_surface_arrivals_vertical(bell_cfg);
    geometry=local_geometry(cfg,x);
    [converted,~]=apply_pe_channel_phase_reference_vertical(f,struct( ...
        'direct_f',pe.H_direct_reduced_f(:),'reflect_fm',pe.H_reflect_reduced_f(:)), ...
        struct('z_tx',cfg.z_tx_m,'z_rx',cfg.z_rx_m,'z_surface',0,'c0',cfg.c0_mps), ...
        'absolute_physical');
    physical_errors(ii)=max(abs([converted.direct_f-pe.H_direct_physical_f(:); ...
        converted.reflect_fm-pe.H_reflect_physical_f(:)]));
    [converted_dsp,~]=apply_pe_channel_phase_reference_vertical(f,struct( ...
        'direct_f',pe.H_direct_reduced_f(:),'reflect_fm',pe.H_reflect_reduced_f(:)), ...
        struct('z_tx',cfg.z_tx_m,'z_rx',cfg.z_rx_m,'z_surface',0,'c0',cfg.c0_mps), ...
        'direct_dsp');
    dsp_errors(ii)=max(abs([converted_dsp.direct_f-pe.H_direct_f(:); ...
        converted_dsp.reflect_fm-pe.H_reflect_f(:)]));
    sum_errors(ii)=max(abs(pe.H_f(:)-pe.H_direct_f(:)-pe.H_reflect_f(:)));
    td0=(cfg.z_tx_m-cfg.z_rx_m)/cfg.c0_mps;
    tr0=(cfg.z_tx_m+cfg.z_rx_m)/cfg.c0_mps;
    direct_cir=local_path_cir(pe.H_direct_physical_f(:),f,td0,geometry.direct_time_s,cfg);
    reflect_cir=local_path_cir(pe.H_reflect_physical_f(:),f,tr0,geometry.surface_time_s,cfg);
    Hbh=bh.paths.amplitude_complex(1).*exp(1i*2*pi*f*bh.paths.delay_s(1))+ ...
        bh.paths.amplitude_complex(2).*exp(1i*2*pi*f*bh.paths.delay_s(2));
    pe_total=local_total_cir(pe.H_physical_f(:),f,td0,cfg);
    bh_total=local_total_cir(Hbh,f,td0,cfg);
    [~,iref]=min(abs(f-cfg.f_ref_hz));
    for pp=1:2
        r=2*(ii-1)+pp; names=["direct";"surface_reflection"];
        analytic=[geometry.direct_time_s;geometry.surface_time_s];
        pe_times=[direct_cir.peak_time_s;reflect_cir.peak_time_s];
        pe_amp=[abs(pe.H_direct_physical_f(iref));abs(pe.H_reflect_physical_f(iref))];
        rows(r)=struct('offset_m',x,'path_name',names(pp), ...
            'analytic_time_ms',1000*analytic(pp),'pe_time_ms',1000*pe_times(pp), ...
            'bellhop_time_ms',1000*bh.paths.delay_s(pp), ...
            'pe_minus_analytic_ms',1000*(pe_times(pp)-analytic(pp)), ...
            'bellhop_minus_analytic_ms',1000*(bh.paths.delay_s(pp)-analytic(pp)), ...
            'pe_minus_bellhop_ms',1000*(pe_times(pp)-bh.paths.delay_s(pp)), ...
            'pe_amplitude',pe_amp(pp),'bellhop_amplitude',bh.paths.amplitude(pp), ...
            'pe_tl_db',-20*log10(max(pe_amp(pp),realmin)), ...
            'bellhop_tl_db',-20*log10(max(bh.paths.amplitude(pp),realmin)), ...
            'source_angle_deg',bh.paths.source_angle_deg(pp), ...
            'cluster_size',bh.paths.cluster_size(pp),'scaled_tl_residual_db',NaN);
    end
    cases(ii)=struct('geometry',geometry,'pe',local_compact_pe(pe), ...
        'bellhop',bh,'direct_cir',direct_cir,'reflection_cir',reflect_cir, ...
        'pe_total_cir',pe_total,'bellhop_total_cir',bh_total);
end
table_out=struct2table(rows);
closure=struct('physical_from_reduced_max_error',max(physical_errors), ...
    'direct_dsp_from_reduced_max_error',max(dsp_errors), ...
    'component_sum_max_error',max(sum_errors));
end

function [t,m]=local_amplitude_metrics(t,cfg)
direct=t.path_name=="direct";
scale_each=t.bellhop_amplitude(direct)./t.pe_amplitude(direct);
global_scale=exp(mean(log(scale_each)));
t.scaled_tl_residual_db=-20*log10(max(global_scale*t.pe_amplitude,realmin))-t.bellhop_tl_db;
reflection=t.path_name=="surface_reflection";
m=struct('global_scale',global_scale, ...
    'scale_each',scale_each,'scale_spread_db', ...
    max(20*log10(scale_each))-min(20*log10(scale_each)), ...
    'reflection_rms_db',sqrt(mean(t.scaled_tl_residual_db(reflection).^2)), ...
    'reflection_max_db',max(abs(t.scaled_tl_residual_db(reflection))));
m.passed=m.scale_spread_db<=cfg.amplitude_scale_spread_db && ...
    m.reflection_rms_db<=cfg.amplitude_rms_db && ...
    m.reflection_max_db<=cfg.amplitude_max_db;
end

function output=local_small_offset_cases(cfg,f,out_dir,baseline)
offsets=cfg.small_offsets_m(:); rows=repmat(local_small_row(),2*numel(offsets),1);
case_template=struct('offset_m',[],'geometry',[],'pe',[],'bellhop',[], ...
    'direct_cir',[],'reflection_cir',[]);
cases=repmat(case_template,numel(offsets),1);
for ii=1:numel(offsets)
    x=offsets(ii); fprintf('Small-offset x = %.3f m\n',x);
    if any(abs(cfg.baseline_offsets_m-x)<eps(max(1,x)))
        ib=find(abs(cfg.baseline_offsets_m-x)<eps(max(1,x)),1);
        pe=baseline(ib).pe; bh=baseline(ib).bellhop;
    else
        pe_raw=vertical_channel_model(local_pe_params(cfg,f.',x,struct()));
        pe=local_compact_pe(pe_raw);
        if x>0
            bh=run_bellhop_flat_surface_arrivals_vertical(local_bellhop_cfg(cfg,x, ...
                fullfile(out_dir,['small_' local_offset_token(x)]), ...
                cfg.small_offset_beam_count));
        else
            bh=[];
        end
    end
    g=local_geometry(cfg,x); td0=(cfg.z_tx_m-cfg.z_rx_m)/cfg.c0_mps;
    tr0=(cfg.z_tx_m+cfg.z_rx_m)/cfg.c0_mps;
    dc=local_path_cir(pe.H_direct_physical_f(:),f,td0,g.direct_time_s,cfg);
    rc=local_path_cir(pe.H_reflect_physical_f(:),f,tr0,g.surface_time_s,cfg);
    [~,ir]=min(abs(f-cfg.f_ref_hz)); pe_amp=[abs(pe.H_direct_physical_f(ir));abs(pe.H_reflect_physical_f(ir))];
    for pp=1:2
        r=2*(ii-1)+pp; names=["direct";"surface_reflection"];
        analytic=[g.direct_time_s;g.surface_time_s]; pe_time=[dc.peak_time_s;rc.peak_time_s];
        if isempty(bh)
            bt=NaN; ba=NaN; angle=NaN;
        else
            bt=bh.paths.delay_s(pp); ba=bh.paths.amplitude(pp); angle=bh.paths.source_angle_deg(pp);
        end
        rows(r)=struct('offset_m',x,'path_name',names(pp), ...
            'analytic_time_ms',1000*analytic(pp),'pe_time_ms',1000*pe_time(pp), ...
            'bellhop_time_ms',1000*bt,'pe_residual_ms',1000*(pe_time(pp)-analytic(pp)), ...
            'bellhop_residual_ms',1000*(bt-analytic(pp)), ...
            'pe_amplitude',pe_amp(pp),'bellhop_amplitude',ba,'source_angle_deg',angle);
    end
    cases(ii)=struct('offset_m',x,'geometry',g,'pe',pe,'bellhop',bh, ...
        'direct_cir',dc,'reflection_cir',rc);
end
output=struct('table',struct2table(rows),'cases',cases);
end

function output=local_source_audit(cfg,baseline,small)
small_table=small.table; base_table=local_baseline_source_rows(baseline);
t=[small_table(:,{'offset_m','path_name','pe_amplitude','bellhop_amplitude','source_angle_deg'});base_table];
t=t(t.path_name=="direct" & t.offset_m>0,:); t=sortrows(t,'offset_m');
[~,ia]=unique(t.offset_m,'stable'); t=t(ia,:);
k0=2*pi*cfg.f_ref_hz/cfg.c0_mps;
kappa=k0*abs(cosd(t.source_angle_deg));
t.gaussian_weight=exp(-0.5*cfg.sigma_src_m^2*kappa.^2);
t.bellhop_source_aware_amplitude=t.bellhop_amplitude.*t.gaussian_weight;
raw_scale=exp(mean(log(t.bellhop_amplitude./t.pe_amplitude)));
aware_scale=exp(mean(log(t.bellhop_source_aware_amplitude./t.pe_amplitude)));
t.raw_residual_db=-20*log10(max(raw_scale*t.pe_amplitude,realmin))+ ...
    20*log10(max(t.bellhop_amplitude,realmin));
t.source_aware_residual_db=-20*log10(max(aware_scale*t.pe_amplitude,realmin))+ ...
    20*log10(max(t.bellhop_source_aware_amplitude,realmin));
output=struct('table',t,'raw_scale',raw_scale,'source_aware_scale',aware_scale, ...
    'raw_rms_db',sqrt(mean(t.raw_residual_db.^2)), ...
    'source_aware_rms_db',sqrt(mean(t.source_aware_residual_db.^2)), ...
    'interpretation','Diagnostic only; source-aware weighting never replaces raw Bellhop amplitudes.');
end

function t=local_baseline_source_rows(cases)
rows=repmat(struct('offset_m',0,'path_name',"direct",'pe_amplitude',0, ...
    'bellhop_amplitude',0,'source_angle_deg',0),numel(cases),1);
for ii=1:numel(cases)
    [~,ir]=min(abs(cases(ii).pe.f_axis-4000));
    rows(ii)=struct('offset_m',cases(ii).geometry.offset_m,'path_name',"direct", ...
        'pe_amplitude',abs(cases(ii).pe.H_direct_physical_f(ir)), ...
        'bellhop_amplitude',cases(ii).bellhop.paths.amplitude(1), ...
        'source_angle_deg',cases(ii).bellhop.paths.source_angle_deg(1));
end
t=struct2table(rows);
end

function output=local_window_sponge_audit(cfg,f)
defs={ ...
    'sampling_C0','sampling',128,32,0.5,0.12,0.15,'sampling_C0'; ...
    'sampling_C1','sampling',256,32,0.5,0.12,0.15,'sampling_C0'; ...
    'sampling_C3','sampling',128,32,0.25,0.12,0.15,'sampling_C0'; ...
    'sampling_C4','sampling',256,32,0.25,0.12,0.15,'sampling_C0'; ...
    'aperture_32','aperture',128,32,0.5,0.12,1e-14,'aperture_64'; ...
    'aperture_64','aperture',256,64,0.5,0.12,1e-14,'aperture_64'; ...
    'location_r010','sponge_location',256,64,0.5,0.10,0.15,'location_r012'; ...
    'location_r012','sponge_location',256,64,0.5,0.12,0.15,'location_r012'; ...
    'location_r015','sponge_location',256,64,0.5,0.15,0.15,'location_r012'; ...
    'strength_a005','sponge_strength',256,64,0.5,0.12,0.05,'strength_a015'; ...
    'strength_a015','sponge_strength',256,64,0.5,0.12,0.15,'strength_a015'; ...
    'strength_a030','sponge_strength',256,64,0.5,0.12,0.30,'strength_a015'};
rows=repmat(local_window_row(),size(defs,1),1); records=cell(size(defs,1),1);
for ii=1:size(defs,1)
    fprintf('Window/sponge %s\n',defs{ii,1});
    over=struct('nx',defs{ii,3},'ny',defs{ii,3},'width_m',defs{ii,4}, ...
        'stepz_lamb',defs{ii,5},'sponge_ratio',defs{ii,6}, ...
        'alpha_max_np_per_m',defs{ii,7},'save_mode','slice');
    pe=vertical_channel_model(local_pe_params(cfg,f.',6,over)); records{ii}=local_compact_pe(pe);
    field=pe.psifinal_xy; edge=local_edge_level_db(field);
    [~,ir]=min(abs(f-cfg.f_ref_hz));
    rows(ii)=struct('case_name',string(defs{ii,1}),'group_name',string(defs{ii,2}), ...
        'nx',defs{ii,3},'width_m',defs{ii,4},'stepz_lamb',defs{ii,5}, ...
        'sponge_ratio',defs{ii,6},'alpha_max_np_per_m',defs{ii,7}, ...
        'reference_case',string(defs{ii,8}),'phase_rms_rad',NaN, ...
        'relative_tl_db',NaN,'edge_level_db',edge,'passed',false);
end
t=struct2table(rows);
for ii=1:height(t)
    ref=find(t.case_name==t.reference_case(ii),1);
    H=records{ii}.H_reflect_physical_f(:); H0=records{ref}.H_reflect_physical_f(:);
    [~,ir]=min(abs(f-cfg.f_ref_hz));
    t.phase_rms_rad(ii)=local_phase_rms(H,H0,ir);
    t.relative_tl_db(ii)=20*log10(abs(H(ir))/max(abs(H0(ir)),realmin));
    edge_ok=true;
    if t.group_name(ii)=="aperture", edge_ok=t.edge_level_db(ii)<=cfg.edge_level_limit_db; end
    t.passed(ii)=t.phase_rms_rad(ii)<=cfg.phase_tolerance_rad && ...
        abs(t.relative_tl_db(ii))<=cfg.tl_tolerance_db && edge_ok;
end
output=struct('table',t,'records',{records}, ...
    'passed',all(t.passed),'aperture_complete', ...
    all(t.edge_level_db(t.group_name=="aperture")<=cfg.edge_level_limit_db));
end

function regression=local_public_regression(cfg,f)
p=local_pe_params(cfg,cfg.f_ref_hz,6,struct()); p.enable_surface_reflection=false;
direct=vertical_channel_model(p); p.enable_surface_reflection=true; reflected=vertical_channel_model(p);
wide=vertical_channel_model(local_pe_params(cfg,f.',6,struct()));
p_default=local_pe_params(cfg,cfg.f_ref_hz,6,struct());
p_default=rmfield(p_default,'surface_boundary_model');
default_case=vertical_channel_model(p_default);
regression=struct( ...
    'direct_only_reflection_error',max(abs(direct.H_reflect_f(:))), ...
    'direct_cross_mode_error',max(abs(direct.H_direct_f(:)-reflected.H_direct_f(:))), ...
    'scalar_sum_error',max(abs(reflected.H_f(:)-reflected.H_direct_f(:)-reflected.H_reflect_f(:))), ...
    'wideband_sum_error',max(abs(wide.H_f(:)-wide.H_direct_f(:)-wide.H_reflect_f(:))), ...
    'default_surface_model',default_case.config.surface_boundary_model, ...
    'default_phase_reference',default_case.config.channel_phase_reference);
end

function m=local_matrix_compatibility(cfg,cases,t,phase,meta,closure,window,regression)
case_template=struct('geometry',[],'pe',[],'bellhop_paths',[], ...
    'direct_cir',[],'reflection_cir',[],'delay_axis_s',[], ...
    'pe_total_power',[],'bellhop_total_power',[],'invariant_error',[]);
compat_cases=repmat(case_template,numel(cases),1);
for ii=1:numel(cases)
    compat_cases(ii)=struct('geometry',cases(ii).geometry,'pe',cases(ii).pe, ...
        'bellhop_paths',cases(ii).bellhop.paths, ...
        'direct_cir',cases(ii).direct_cir, ...
        'reflection_cir',cases(ii).reflection_cir, ...
        'delay_axis_s',cases(ii).pe_total_cir.delay_s, ...
        'pe_total_power',cases(ii).pe_total_cir.power, ...
        'bellhop_total_power',cases(ii).bellhop_total_cir.power, ...
        'invariant_error',max(abs(cases(ii).pe.H_f(:)- ...
        cases(ii).pe.H_direct_f(:)-cases(ii).pe.H_reflect_f(:))));
end
m=struct('config',local_matrix_config(cfg),'phase_audit_file',phase.files.mat, ...
    'bellhop_executable',cfg.bellhop_exe,'path_table',t,'cases',compat_cases, ...
    'raw_bellhop_arrivals',{arrayfun(@(c)c.bellhop.raw_arrivals,cases,'UniformOutput',false)}, ...
    'global_direct_scale',exp(mean(log(t.bellhop_amplitude(t.path_name=="direct")./ ...
        t.pe_amplitude(t.path_name=="direct")))),'direct_scale_each',[], ...
    'scale_spread_db',local_span(20*log10( ...
        t.bellhop_amplitude(t.path_name=="direct")./ ...
        t.pe_amplitude(t.path_name=="direct"))),'validation_run_meta',meta, ...
    'phase_reference_meta',cases(1).pe.phase_reference_meta,'closure',closure, ...
    'window_audit',window,'public_regression',regression,'passed',false);
end

function validation=local_finalize(validation,cfg)
t=validation.path_table; small=validation.small_offset.table; field=validation.field_output;
finite_bh=~isnan(small.bellhop_residual_ms);
core_names=["phase_audit";"phase_conversion";"component_closure"; ...
    "pe_analytic_delay";"pe_bellhop_delay";"bellhop_analytic_delay"; ...
    "small_offset_pe_delay";"small_offset_bellhop_delay";"path_clusters"; ...
    "bellhop_coherent_beams";"bellhop_incoherent_beams";"pe_numerical_convergence"; ...
    "public_regression";"public_defaults"];
coherent=field.convergence_table(field.convergence_table.mode=="coherent",:);
incoherent=field.convergence_table(field.convergence_table.mode=="incoherent",:);
cluster_error=max(abs(t.cluster_size-1));
pub=validation.public_regression;
public_error=max([pub.direct_only_reflection_error,pub.direct_cross_mode_error, ...
    pub.scalar_sum_error,pub.wideband_sum_error]);
values=[double(~validation.phase_audit.passed); ...
    max(validation.closure.physical_from_reduced_max_error, ...
        validation.closure.direct_dsp_from_reduced_max_error); ...
    validation.closure.component_sum_max_error;max(abs(t.pe_minus_analytic_ms)); ...
    max(abs(t.pe_minus_bellhop_ms));max(abs(t.bellhop_minus_analytic_ms)); ...
    max(abs(small.pe_residual_ms));max(abs(small.bellhop_residual_ms(finite_bh))); ...
    cluster_error;coherent.tl_rms_difference_db;incoherent.tl_rms_difference_db; ...
    double(~validation.window_audit.passed);public_error; ...
    double(~strcmp(pub.default_surface_model,'kirchhoff_spatial') || ...
        ~strcmp(pub.default_phase_reference,'direct_dsp'))];
limits=[0;cfg.closure_tolerance;cfg.closure_tolerance;cfg.time_tolerance_ms; ...
    cfg.time_tolerance_ms;cfg.time_tolerance_ms;cfg.time_tolerance_ms; ...
    cfg.time_tolerance_ms;0;1;0.5;0;cfg.closure_tolerance;0];
passed=values<=limits;
validation.checks=table(core_names,values,limits,passed, ...
    'VariableNames',{'check_name','value','limit','passed'});
validation.core_passed=all(passed);
if validation.core_passed, validation.decision='PASS_CORE'; else, validation.decision='FAIL_CORE'; end
if validation.amplitude_metrics.passed
    validation.amplitude_status='PASS';
else
    validation.amplitude_status='OPEN';
end
validation.matrix_validation.passed=validation.core_passed;
end

function p=local_pe_params(cfg,f,x,over)
p=struct('f0',f,'enable_wideband',false,'f_ref_hz',cfg.f_ref_hz, ...
    'c0',cfg.c0_mps,'z_max',cfg.water_depth_m,'stepz_lamb',cfg.stepz_lamb, ...
    'xw',cfg.width_m,'yw',cfg.width_m,'nx',cfg.nx,'ny',cfg.ny, ...
    'x_tx',0,'y_tx',0,'z_tx',cfg.z_tx_m,'x_rx',x,'y_rx',0,'z_rx',cfg.z_rx_m, ...
    'sigma_src_m',cfg.sigma_src_m,'sponge_ratio',cfg.sponge_ratio, ...
    'alpha_max_np_per_m',cfg.alpha_max_np_per_m,'env_mode','uniform', ...
    'show_figures',false,'enforce_1_over_R',true,'enable_surface_reflection',true, ...
    'surface_reflect_coeff',-1,'surface_phase_mode','normal', ...
    'surface_boundary_model','kirchhoff_spatial','sea_hs_target',0, ...
    'enable_bubbles',false,'save_mode','rx_only','use_gpu',false, ...
    'channel_phase_reference','direct_dsp');
names=fieldnames(over);
for ii=1:numel(names)
    switch names{ii}
        case 'width_m', p.xw=over.width_m; p.yw=over.width_m;
        otherwise, p.(names{ii})=over.(names{ii});
    end
end
end

function cfg_bh=local_bellhop_cfg(cfg,x,root,beam_count)
cfg_bh=struct('bellhop_exe',cfg.bellhop_exe,'case_root',root, ...
    'frequency_hz',cfg.f_ref_hz,'water_depth_m',cfg.water_depth_m, ...
    'c0_mps',cfg.c0_mps,'z_tx_m',cfg.z_tx_m,'z_rx_m',cfg.z_rx_m, ...
    'offset_m',x,'beam_count',beam_count,'angle_min_deg',cfg.angle_limits_deg(1), ...
    'angle_max_deg',cfg.angle_limits_deg(2), ...
    'arrival_cluster_tolerance_ms',cfg.arrival_cluster_tolerance_ms);
end

function g=local_geometry(cfg,x)
g=struct('offset_m',x,'direct_length_m',hypot(x,cfg.z_tx_m-cfg.z_rx_m), ...
    'surface_length_m',hypot(x,cfg.z_tx_m+cfg.z_rx_m));
g.direct_time_s=g.direct_length_m/cfg.c0_mps; g.surface_time_s=g.surface_length_m/cfg.c0_mps;
end

function token=local_offset_token(x)
token=['x' strrep(sprintf('%07.3f',x),'.','p') 'm'];
end

function cir=local_path_cir(H,f,tref,target,cfg)
cir=local_total_cir(H,f,tref,cfg); mask=abs(cir.delay_s-target)<=0.001;
idx=find(mask); if isempty(idx), error('Path peak window is empty.'); end
[~,j]=max(cir.power(mask)); cir.peak_time_s=cir.delay_s(idx(j));
end

function cir=local_total_cir(H,f,tref,cfg)
F=numel(f); n=(0:F-1).'; df=mean(diff(f)); N=cfg.zero_padding_factor*F;
w=0.5-0.5*cos(2*pi*n/(F-1));
h=fft(H(:).*exp(-1i*2*pi*f(:)*tref).*w,N)/N;
cir=struct('delay_s',tref+(0:N-1).'/(df*N),'h',h,'power',abs(h).^2, ...
    'reference_time_s',tref);
end

function value=local_phase_rms(H,H0,ir)
relative=(H/H(ir)).*conj(H0/H0(ir)); phase=unwrap(angle(relative));
phase=phase-phase(ir); value=sqrt(mean(phase.^2));
end

function db=local_edge_level_db(field)
if isempty(field), db=Inf; return; end
ny=size(field,1); nx=size(field,2); width=max(1,round(0.02*min(nx,ny)));
mask=false(ny,nx); mask(1:width,:)=true; mask(end-width+1:end,:)=true;
mask(:,1:width)=true; mask(:,end-width+1:end)=true;
db=20*log10(max(abs(field(mask)))/max(max(abs(field(:))),realmin));
end

function value=local_span(values)
value=max(values)-min(values);
end

function row=local_path_row()
row=struct('offset_m',NaN,'path_name',"",'analytic_time_ms',NaN, ...
    'pe_time_ms',NaN,'bellhop_time_ms',NaN,'pe_minus_analytic_ms',NaN, ...
    'bellhop_minus_analytic_ms',NaN,'pe_minus_bellhop_ms',NaN, ...
    'pe_amplitude',NaN,'bellhop_amplitude',NaN,'pe_tl_db',NaN, ...
    'bellhop_tl_db',NaN,'source_angle_deg',NaN,'cluster_size',0, ...
    'scaled_tl_residual_db',NaN);
end

function row=local_small_row()
row=struct('offset_m',NaN,'path_name',"",'analytic_time_ms',NaN, ...
    'pe_time_ms',NaN,'bellhop_time_ms',NaN,'pe_residual_ms',NaN, ...
    'bellhop_residual_ms',NaN,'pe_amplitude',NaN,'bellhop_amplitude',NaN, ...
    'source_angle_deg',NaN);
end

function row=local_window_row()
row=struct('case_name',"",'group_name',"",'nx',0,'width_m',0, ...
    'stepz_lamb',0,'sponge_ratio',0,'alpha_max_np_per_m',0, ...
    'reference_case',"",'phase_rms_rad',NaN,'relative_tl_db',NaN, ...
    'edge_level_db',NaN,'passed',false);
end

function c=local_compact_pe(p)
c=struct('H_direct_f',p.H_direct_f,'H_reflect_f',p.H_reflect_f,'H_f',p.H_f, ...
    'H_direct_reduced_f',p.H_direct_reduced_f,'H_reflect_reduced_f',p.H_reflect_reduced_f, ...
    'H_direct_physical_f',p.H_direct_physical_f,'H_reflect_physical_f',p.H_reflect_physical_f, ...
    'H_physical_f',p.H_physical_f,'phase_reference_meta',p.phase_reference_meta, ...
    'f_axis',p.f_axis,'idx_f_ref',p.idx_f_ref,'h_direct',p.h_direct, ...
    'h_reflect',p.h_reflect,'h_total',p.h_total,'pass_1_over_R',p.pass_1_over_R, ...
    'fit_slope',p.fit_slope,'fit_err_rms',p.fit_err_rms,'config',p.config);
end

function c=local_matrix_config(cfg)
c=struct('water_depth_m',cfg.water_depth_m,'c0_mps',cfg.c0_mps, ...
    'z_tx_m',cfg.z_tx_m,'z_rx_m',cfg.z_rx_m,'receiver_offsets_m',cfg.baseline_offsets_m, ...
    'convergence_offset_m',6,'f_ref_hz',cfg.f_ref_hz, ...
    'frequency_band_hz',cfg.frequency_band_hz,'frequency_count',cfg.frequency_count, ...
    'sigma_src_m',cfg.sigma_src_m,'sponge_ratio',cfg.sponge_ratio, ...
    'alpha_max_np_per_m',cfg.alpha_max_np_per_m,'bellhop_exe',cfg.bellhop_exe);
end

function local_write_summary(file,v)
fid=fopen(file,'w','n','UTF-8'); if fid<0,error('Cannot create %s',file);end
cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'PE/Bellhop current validation\nrun_id %s\ndecision %s\namplitude_status %s\n', ...
    v.validation_run_meta.run_id,v.decision,v.amplitude_status);
for ii=1:height(v.checks)
    fprintf(fid,'%s value %.12g limit %.12g passed %d\n',v.checks.check_name(ii), ...
        v.checks.value(ii),v.checks.limit(ii),v.checks.passed(ii));
end
clear cleanup
end

function local_write_report(file,v)
fid=fopen(file,'w','n','UTF-8'); if fid<0,error('Cannot create %s',file);end
cleanup=onCleanup(@()fclose(fid)); t=v.checks; a=v.amplitude_metrics;
fprintf(fid,'# PE/Bellhop current flat-surface validation\n\n');
fprintf(fid,'- run_id: `%s`\n- core decision: **%s**\n- amplitude status: **%s**\n', ...
    v.validation_run_meta.run_id,v.decision,v.amplitude_status);
fprintf(fid,'- Bellhop SHA-256: `%s`\n\n',v.validation_run_meta.bellhop_sha256);
fprintf(fid,'## Layered acceptance\n\n| Check | Value | Limit | Pass |\n|---|---:|---:|:---:|\n');
for ii=1:height(t)
    fprintf(fid,'| %s | %.8g | %.8g | %d |\n',t.check_name(ii),t.value(ii),t.limit(ii),t.passed(ii));
end
fprintf(fid,'\n## Amplitude diagnostic\n\n');
fprintf(fid,'Scale spread %.6g dB; reflection RMS %.6g dB; max %.6g dB. ', ...
    a.scale_spread_db,a.reflection_rms_db,a.reflection_max_db);
fprintf(fid,'Source-aware weighting is diagnostic and never replaces raw amplitudes.\n\n');
fprintf(fid,'## Interpretation\n\n');
fprintf(fid,'Physical PE fields are obtained through the public phase-reference layer; no validator adds a second carrier. ');
fprintf(fid,'The 4 kHz Bellhop arrivals are extended across 3--5 kHz only for delay/PDP diagnostics, not as a multifrequency Bellhop amplitude model.\n\n');
fprintf(fid,'The public PE core and default `kirchhoff_spatial` surface remain unchanged. ');
fprintf(fid,'See the same-run ten-figure atlas under `%s`.\n',v.validation_run_meta.visualization_output_dir);
clear cleanup
end
