function result=validate_cached_pe_public_consistency_vertical()
%VALIDATE_CACHED_PE_PUBLIC_CONSISTENCY_VERTICAL Same-input double test.
root_dir=fileparts(fileparts(fileparts(mfilename('fullpath')))); addpath(root_dir);
cfg=struct('f_axis_hz',linspace(4000,8000,32).','c0',1500, ...
    'xw',50,'yw',50,'nx',128,'ny',128,'x_tx',0,'y_tx',0, ...
    'z_tx',100,'x_rx',0,'y_rx',0,'z_rx',3,'sigma_src_m',0.4, ...
    'stepz_lamb',0.5,'sponge_ratio',0.12,'alpha_max_np_per_m',0.15, ...
    'reflect_coeff',-1,'env_mode','uniform','enable_bubbles',false);
seed=700001; spec=raw_pm_spectrum_grid_vertical(5,128,128,50,50);
cache=build_cached_joint_kstat_pe_executor_vertical(cfg,spec);
[eta,~]=sample_raw_pm_surface_vertical(spec,seed); F=numel(cfg.f_axis_hz);
delta=complex(zeros(cfg.ny,cfg.nx,F));
for ff=1:F
    alpha=4*pi*cfg.f_axis_hz(ff)/cfg.c0;
    delta(:,:,ff)=cfg.reflect_coeff*exp(1i*alpha*eta)-cache.R_coh_f(ff);
end
timer=tic; cached=run_cached_joint_kstat_pe_executor_vertical(cache,delta); cached_s=toc(timer);
params=struct('f0',cfg.f_axis_hz.','enable_wideband',false,'c0',cfg.c0, ...
    'z_max',cfg.z_tx,'z_tx',cfg.z_tx,'z_rx',cfg.z_rx,'xw',cfg.xw,'yw',cfg.yw, ...
    'nx',cfg.nx,'ny',cfg.ny,'x_tx',0,'y_tx',0,'x_rx',0,'y_rx',0, ...
    'sigma_src_m',cfg.sigma_src_m,'stepz_lamb',cfg.stepz_lamb, ...
    'sponge_ratio',cfg.sponge_ratio,'alpha_max_np_per_m',cfg.alpha_max_np_per_m, ...
    'env_mode','uniform','enable_bubbles',false,'enable_surface_reflection',true, ...
    'surface_reflect_coeff',-1,'surface_boundary_model','kirchhoff_kdomain', ...
    'surface_roughness_scale_mode','raw_pm','sea_wind_speed',5,'sea_seed',seed, ...
    'show_figures',false,'enforce_1_over_R',false,'save_mode','rx_only','use_gpu',false);
timer=tic; public=vertical_channel_model(params); public_s=toc(timer);
result=struct('seed',seed,'public_s',public_s,'cached_s',cached_s, ...
    'cache_build_s',cache.build_time_s,'speedup',public_s/cached_s, ...
    'max_abs_direct_error',max(abs(cached.H_direct_f-public.H_direct_f)), ...
    'max_abs_reflect_error',max(abs(cached.H_ref_coh_f+cached.H_ref_sca_fm-public.H_reflect_f)), ...
    'max_abs_total_error',max(abs(cached.H_total_fm-public.H_f)), ...
    'component_sum_max_abs_error',cached.component_sum_max_abs_error, ...
    'precision','double deltaG input');
out_dir=fullfile(root_dir,'results','validation','cached_joint_kstat_pe_receiver');
save(fullfile(out_dir,'cached_public_consistency_double.mat'),'result');
fprintf('public %.6f s, cached %.6f s, speedup %.3fx, total error %.3g\n', ...
    public_s,cached_s,result.speedup,result.max_abs_total_error);
end
