%% Reduced-grid public direct-only / direct-plus-reflect regression
clear; clc;
root=fileparts(fileparts(fileparts(mfilename('fullpath')))); addpath(root);
p=struct('f0',6000,'enable_wideband',false,'c0',1500,'z_max',100, ...
    'stepz_lamb',0.5,'xw',50,'yw',50,'nx',128,'ny',128, ...
    'x_tx',0,'y_tx',0,'z_tx',100,'x_rx',0,'y_rx',0,'z_rx',3, ...
    'nout',2,'sigma_src_m',0.4,'sponge_ratio',0.12, ...
    'alpha_max_np_per_m',0.15,'env_mode','uniform','enforce_1_over_R',false, ...
    'show_figures',false,'save_mode','rx_only','use_gpu',false, ...
    'sea_wind_speed',5,'sea_seed',34567,'surface_reflect_coeff',-1, ...
    'surface_boundary_model','kirchhoff_kstat', ...
    'surface_roughness_scale_mode','raw_pm','surface_kstat_random_scatter',true);
p.enable_surface_reflection=false; direct_only=vertical_channel_model(p);
p.enable_surface_reflection=true; direct_plus_reflect=vertical_channel_model(p);
result=struct();
result.direct_only_reflect_max_abs=max(abs(direct_only.H_reflect_f));
result.direct_only_total_error=max(abs(direct_only.H_f-direct_only.H_direct_f));
result.direct_plus_reflect_sum_error=max(abs(direct_plus_reflect.H_f- ...
    direct_plus_reflect.H_direct_f-direct_plus_reflect.H_reflect_f));
result.direct_path_cross_mode_error=max(abs(direct_only.H_direct_f-direct_plus_reflect.H_direct_f));
result.pass=result.direct_only_reflect_max_abs<=1e-12 && ...
    result.direct_only_total_error<=1e-12 && ...
    result.direct_plus_reflect_sum_error<=1e-10 && ...
    result.direct_path_cross_mode_error<=1e-12;
out_dir=fullfile(root,'results','validation');
save(fullfile(out_dir,'validate_public_channel_modes_vertical_result.mat'),'result');
disp(result); assert(result.pass,'Public direct/reflection mode regression failed.');
